-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cifar10_cnn_conv_relu_pool_3_16_32_9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_chw_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_chw_ce0 : OUT STD_LOGIC;
    input_chw_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    stage1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    stage1_ce1 : OUT STD_LOGIC;
    stage1_we1 : OUT STD_LOGIC;
    stage1_d1 : OUT STD_LOGIC_VECTOR (6 downto 0) );
end;


architecture behav of cifar10_cnn_conv_relu_pool_3_16_32_9_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_1B : STD_LOGIC_VECTOR (8 downto 0) := "000011011";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv7_6C : STD_LOGIC_VECTOR (6 downto 0) := "1101100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv11_39 : STD_LOGIC_VECTOR (10 downto 0) := "00000111001";
    constant ap_const_lv9_16 : STD_LOGIC_VECTOR (8 downto 0) := "000010110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_const_lv33_100 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000100000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal CONV1_BIAS_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal CONV1_BIAS_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal CONV1_WEIGHT_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal CONV1_WEIGHT_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_reg_248 : STD_LOGIC_VECTOR (6 downto 0);
    signal k_reg_259 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_reg_270 : STD_LOGIC_VECTOR (2 downto 0);
    signal maximum_reg_281 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln50_38_reg_293 : STD_LOGIC_VECTOR (19 downto 0);
    signal accumulator_3_reg_305 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal phi_mul_load_reg_898 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln27_1_fu_368_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln27_1_reg_903 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln27_fu_380_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln27_reg_911 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln57_fu_391_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln57_reg_921 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln50_3_fu_395_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln50_3_reg_926 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln29_fu_405_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln29_reg_935 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal first_iter_3_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_3_reg_940 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln57_2_fu_417_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln57_2_reg_944 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln31_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln31_fu_435_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln31_reg_954 : STD_LOGIC_VECTOR (4 downto 0);
    signal first_iter_2_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_reg_965 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln31_fu_447_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln31_reg_969 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln37_fu_451_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln37_reg_974 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln34_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln34_reg_979_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_979_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln34_fu_461_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln39_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_988_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal k_mid2_fu_473_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal k_mid2_reg_996 : STD_LOGIC_VECTOR (4 downto 0);
    signal k_mid2_reg_996_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal k_mid2_reg_996_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal k_mid2_reg_996_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal k_mid2_reg_996_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal k_mid2_reg_996_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal k_mid2_reg_996_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal k_mid2_reg_996_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal first_iter_0_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1004_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln39_fu_499_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln39_reg_1008 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln39_2_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_2_reg_1013_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_fu_529_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1017 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1017_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1017_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1017_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_fu_536_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln34_reg_1021 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal icmp_ln34_2_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_2_reg_1028 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_2_reg_1028_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_2_reg_1028_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_2_reg_1028_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_2_reg_1028_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_1032 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_2_fu_757_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal grp_fu_874_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter11_state17 : STD_LOGIC;
    signal sext_ln50_35_reg_202 : STD_LOGIC_VECTOR (19 downto 0);
    signal oy_reg_214 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln50_36_reg_225 : STD_LOGIC_VECTOR (19 downto 0);
    signal icmp_ln29_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ox_reg_237 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_k_phi_fu_263_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_p_phi_fu_274_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_sext_ln50_38_phi_fu_297_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_mux_accumulator_3_phi_fu_308_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter11_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_predicate_pred369_state17 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter1_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter2_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter3_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter4_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter5_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter6_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter7_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter9_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter10_sext_ln50_39_reg_315 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_mux_sext_ln50_31_phi_fu_339_p10 : STD_LOGIC_VECTOR (19 downto 0);
    signal accumulator_3_mid2_fu_743_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter11_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter0_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter1_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter2_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter3_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter4_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter5_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter6_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter7_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter9_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter10_sext_ln50_31_reg_336 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln27_fu_386_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln27_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln48_fu_713_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln50_fu_723_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_fu_864_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_mul_fu_134 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal oc_fu_138 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal maximum_4_fu_142 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal maximum_5_fu_850_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal CONV1_BIAS_ce0_local : STD_LOGIC;
    signal input_chw_ce0_local : STD_LOGIC;
    signal CONV1_WEIGHT_ce0_local : STD_LOGIC;
    signal stage1_we1_local : STD_LOGIC;
    signal stage1_ce1_local : STD_LOGIC;
    signal grp_fu_493_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln34_2_fu_511_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal first_iter_1_mid1_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_120_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln41_fu_565_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln41_fu_565_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_487_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln42_fu_575_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln42_fu_575_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_fu_575_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_493_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_552_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_595_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln42_2_fu_581_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln44_fu_606_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln44_fu_612_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln44_fu_602_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln34_fu_549_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_622_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln43_fu_591_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln45_fu_633_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln45_fu_639_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln45_fu_629_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ix_fu_643_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal iy_fu_616_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln47_fu_653_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_4_fu_659_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln41_fu_565_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_675_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln3_fu_685_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln48_fu_693_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln48_2_fu_699_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln45_2_fu_649_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln48_2_fu_707_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln39_fu_559_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln50_fu_718_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal pixel_2_fu_728_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1075_fu_777_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1075_fu_780_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1076_fu_784_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_5_fu_790_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln1074_fu_772_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_icmp_ln1074_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1078_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1078_cast_fu_822_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln9_fu_806_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal value_fu_836_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln55_fu_844_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_764_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln57_fu_859_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal mul_ln41_fu_565_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_fu_575_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_condition_412 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component cifar10_cnn_urem_5ns_5ns_5_9_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component cifar10_cnn_urem_5ns_3ns_2_9_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component cifar10_cnn_mul_5ns_7ns_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component cifar10_cnn_mul_5ns_6ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component cifar10_cnn_mac_muladd_8s_8s_20s_20_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (19 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component cifar10_cnn_conv_relu_pool_3_16_32_9_s_CONV1_BIAS_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component cifar10_cnn_conv_relu_pool_3_16_32_9_s_CONV1_WEIGHT_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    CONV1_BIAS_U : component cifar10_cnn_conv_relu_pool_3_16_32_9_s_CONV1_BIAS_ROM_AUTO_1R
    generic map (
        DataWidth => 14,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => CONV1_BIAS_address0,
        ce0 => CONV1_BIAS_ce0_local,
        q0 => CONV1_BIAS_q0);

    CONV1_WEIGHT_U : component cifar10_cnn_conv_relu_pool_3_16_32_9_s_CONV1_WEIGHT_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 432,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => CONV1_WEIGHT_address0,
        ce0 => CONV1_WEIGHT_ce0_local,
        q0 => CONV1_WEIGHT_q0);

    urem_5ns_5ns_5_9_1_U5 : component cifar10_cnn_urem_5ns_5ns_5_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        dout_WIDTH => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => k_mid2_fu_473_p3,
        din1 => ap_const_lv5_9,
        ce => ap_const_logic_1,
        dout => grp_fu_487_p2);

    urem_5ns_3ns_2_9_1_U6 : component cifar10_cnn_urem_5ns_3ns_2_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => k_mid2_fu_473_p3,
        din1 => grp_fu_493_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_493_p2);

    mul_5ns_7ns_11_1_1_U7 : component cifar10_cnn_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln41_fu_565_p0,
        din1 => mul_ln41_fu_565_p1,
        dout => mul_ln41_fu_565_p2);

    mul_5ns_6ns_9_1_1_U8 : component cifar10_cnn_mul_5ns_6ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 6,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln42_fu_575_p0,
        din1 => mul_ln42_fu_575_p1,
        dout => mul_ln42_fu_575_p2);

    mac_muladd_8s_8s_20s_20_4_1_U9 : component cifar10_cnn_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => CONV1_WEIGHT_q0,
        din1 => pixel_2_fu_728_p3,
        din2 => ap_phi_mux_sext_ln50_31_phi_fu_339_p10,
        ce => ap_const_logic_1,
        dout => grp_fu_874_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                elsif ((((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter11_state17) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0)))) then 
                    ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter11_state17) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter10;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    accumulator_3_reg_305_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_reg_979_pp0_iter11_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                accumulator_3_reg_305 <= grp_fu_874_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0))) then 
                accumulator_3_reg_305 <= sext_ln50_36_reg_225;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_412)) then 
                    ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336 <= sext_ln50_3_reg_926;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter7_sext_ln50_31_reg_336;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_412)) then 
                    ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315 <= sext_ln50_3_reg_926;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter7_sext_ln50_39_reg_315;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln34_fu_455_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_248 <= add_ln34_fu_461_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_248 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    k_reg_259_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln34_reg_979 = ap_const_lv1_0))) then 
                k_reg_259 <= add_ln39_reg_1008;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0))) then 
                k_reg_259 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    maximum_reg_281_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_reg_979_pp0_iter11_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                maximum_reg_281 <= select_ln34_2_fu_757_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0))) then 
                maximum_reg_281 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    oc_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                oc_fu_138 <= ap_const_lv5_0;
            elsif (((icmp_ln29_fu_399_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                oc_fu_138 <= add_ln27_reg_911;
            end if; 
        end if;
    end process;

    ox_reg_237_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                ox_reg_237 <= add_ln31_reg_954;
            elsif (((icmp_ln29_fu_399_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                ox_reg_237 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    oy_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_1))) then 
                oy_reg_214 <= add_ln29_reg_935;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                oy_reg_214 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    p_reg_270_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (icmp_ln34_reg_979_pp0_iter7_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                p_reg_270 <= select_ln34_reg_1021;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0))) then 
                p_reg_270 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    phi_mul_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                phi_mul_fu_134 <= ap_const_lv9_0;
            elsif (((icmp_ln29_fu_399_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                phi_mul_fu_134 <= add_ln27_1_reg_903;
            end if; 
        end if;
    end process;

    sext_ln50_36_reg_225_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                sext_ln50_36_reg_225 <= sext_ln50_38_reg_293;
            elsif (((icmp_ln29_fu_399_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                sext_ln50_36_reg_225 <= sext_ln50_35_reg_202;
            end if; 
        end if;
    end process;

    sext_ln50_38_reg_293_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_reg_979_pp0_iter11_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sext_ln50_38_reg_293 <= sext_ln50_39_reg_315;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_0))) then 
                sext_ln50_38_reg_293 <= sext_ln50_36_reg_225;
            end if; 
        end if;
    end process;

    sext_ln50_39_reg_315_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_predicate_pred369_state17 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (first_iter_1_mid2_reg_1017_pp0_iter10_reg = ap_const_lv1_1) and (first_iter_0_reg_1004_pp0_iter10_reg = ap_const_lv1_1) and (icmp_ln34_reg_979_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (first_iter_2_reg_965 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (first_iter_1_mid2_reg_1017_pp0_iter10_reg = ap_const_lv1_0) and (first_iter_0_reg_1004_pp0_iter10_reg = ap_const_lv1_1) and (icmp_ln34_reg_979_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (first_iter_0_reg_1004_pp0_iter10_reg = ap_const_lv1_0) and (icmp_ln34_reg_979_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                sext_ln50_39_reg_315 <= ap_phi_mux_sext_ln50_38_phi_fu_297_p4;
            elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter11_sext_ln50_39_reg_315;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln27_1_reg_903 <= add_ln27_1_fu_368_p2;
                add_ln27_reg_911 <= add_ln27_fu_380_p2;
                phi_mul_load_reg_898 <= phi_mul_fu_134;
                trunc_ln57_reg_921 <= trunc_ln57_fu_391_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln29_reg_935 <= add_ln29_fu_405_p2;
                first_iter_3_reg_940 <= first_iter_3_fu_411_p2;
                trunc_ln57_2_reg_944 <= trunc_ln57_2_fu_417_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln31_reg_954 <= add_ln31_fu_435_p2;
                first_iter_2_reg_965 <= first_iter_2_fu_441_p2;
                trunc_ln37_reg_974 <= trunc_ln37_fu_451_p1;
                    zext_ln31_reg_969(4 downto 0) <= zext_ln31_fu_447_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln39_reg_1008 <= add_ln39_fu_499_p2;
                ap_phi_reg_pp0_iter1_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter0_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter1_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter0_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter10_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter9_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter10_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter9_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter11_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter10_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter11_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter10_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter2_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter1_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter2_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter1_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter3_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter2_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter3_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter2_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter4_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter3_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter4_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter3_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter5_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter4_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter5_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter4_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter6_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter5_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter6_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter5_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter7_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter6_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter7_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter6_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter9_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336;
                ap_phi_reg_pp0_iter9_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    ap_predicate_pred369_state17 <= ((first_iter_1_mid2_reg_1017_pp0_iter9_reg = ap_const_lv1_1) and (first_iter_0_reg_1004_pp0_iter9_reg = ap_const_lv1_1) and (icmp_ln34_reg_979_pp0_iter9_reg = ap_const_lv1_0) and (first_iter_2_reg_965 = ap_const_lv1_1) and (first_iter_3_reg_940 = ap_const_lv1_0));
                first_iter_0_reg_1004_pp0_iter10_reg <= first_iter_0_reg_1004_pp0_iter9_reg;
                first_iter_0_reg_1004_pp0_iter2_reg <= first_iter_0_reg_1004_pp0_iter1_reg;
                first_iter_0_reg_1004_pp0_iter3_reg <= first_iter_0_reg_1004_pp0_iter2_reg;
                first_iter_0_reg_1004_pp0_iter4_reg <= first_iter_0_reg_1004_pp0_iter3_reg;
                first_iter_0_reg_1004_pp0_iter5_reg <= first_iter_0_reg_1004_pp0_iter4_reg;
                first_iter_0_reg_1004_pp0_iter6_reg <= first_iter_0_reg_1004_pp0_iter5_reg;
                first_iter_0_reg_1004_pp0_iter7_reg <= first_iter_0_reg_1004_pp0_iter6_reg;
                first_iter_0_reg_1004_pp0_iter8_reg <= first_iter_0_reg_1004_pp0_iter7_reg;
                first_iter_0_reg_1004_pp0_iter9_reg <= first_iter_0_reg_1004_pp0_iter8_reg;
                first_iter_1_mid2_reg_1017 <= first_iter_1_mid2_fu_529_p3;
                first_iter_1_mid2_reg_1017_pp0_iter10_reg <= first_iter_1_mid2_reg_1017_pp0_iter9_reg;
                first_iter_1_mid2_reg_1017_pp0_iter8_reg <= first_iter_1_mid2_reg_1017;
                first_iter_1_mid2_reg_1017_pp0_iter9_reg <= first_iter_1_mid2_reg_1017_pp0_iter8_reg;
                icmp_ln34_2_reg_1028 <= icmp_ln34_2_fu_543_p2;
                icmp_ln34_2_reg_1028_pp0_iter10_reg <= icmp_ln34_2_reg_1028_pp0_iter9_reg;
                icmp_ln34_2_reg_1028_pp0_iter11_reg <= icmp_ln34_2_reg_1028_pp0_iter10_reg;
                icmp_ln34_2_reg_1028_pp0_iter8_reg <= icmp_ln34_2_reg_1028;
                icmp_ln34_2_reg_1028_pp0_iter9_reg <= icmp_ln34_2_reg_1028_pp0_iter8_reg;
                icmp_ln34_reg_979_pp0_iter10_reg <= icmp_ln34_reg_979_pp0_iter9_reg;
                icmp_ln34_reg_979_pp0_iter11_reg <= icmp_ln34_reg_979_pp0_iter10_reg;
                icmp_ln34_reg_979_pp0_iter2_reg <= icmp_ln34_reg_979_pp0_iter1_reg;
                icmp_ln34_reg_979_pp0_iter3_reg <= icmp_ln34_reg_979_pp0_iter2_reg;
                icmp_ln34_reg_979_pp0_iter4_reg <= icmp_ln34_reg_979_pp0_iter3_reg;
                icmp_ln34_reg_979_pp0_iter5_reg <= icmp_ln34_reg_979_pp0_iter4_reg;
                icmp_ln34_reg_979_pp0_iter6_reg <= icmp_ln34_reg_979_pp0_iter5_reg;
                icmp_ln34_reg_979_pp0_iter7_reg <= icmp_ln34_reg_979_pp0_iter6_reg;
                icmp_ln34_reg_979_pp0_iter8_reg <= icmp_ln34_reg_979_pp0_iter7_reg;
                icmp_ln34_reg_979_pp0_iter9_reg <= icmp_ln34_reg_979_pp0_iter8_reg;
                icmp_ln39_2_reg_1013_pp0_iter10_reg <= icmp_ln39_2_reg_1013_pp0_iter9_reg;
                icmp_ln39_2_reg_1013_pp0_iter11_reg <= icmp_ln39_2_reg_1013_pp0_iter10_reg;
                icmp_ln39_2_reg_1013_pp0_iter2_reg <= icmp_ln39_2_reg_1013_pp0_iter1_reg;
                icmp_ln39_2_reg_1013_pp0_iter3_reg <= icmp_ln39_2_reg_1013_pp0_iter2_reg;
                icmp_ln39_2_reg_1013_pp0_iter4_reg <= icmp_ln39_2_reg_1013_pp0_iter3_reg;
                icmp_ln39_2_reg_1013_pp0_iter5_reg <= icmp_ln39_2_reg_1013_pp0_iter4_reg;
                icmp_ln39_2_reg_1013_pp0_iter6_reg <= icmp_ln39_2_reg_1013_pp0_iter5_reg;
                icmp_ln39_2_reg_1013_pp0_iter7_reg <= icmp_ln39_2_reg_1013_pp0_iter6_reg;
                icmp_ln39_2_reg_1013_pp0_iter8_reg <= icmp_ln39_2_reg_1013_pp0_iter7_reg;
                icmp_ln39_2_reg_1013_pp0_iter9_reg <= icmp_ln39_2_reg_1013_pp0_iter8_reg;
                icmp_ln39_reg_988_pp0_iter10_reg <= icmp_ln39_reg_988_pp0_iter9_reg;
                icmp_ln39_reg_988_pp0_iter11_reg <= icmp_ln39_reg_988_pp0_iter10_reg;
                icmp_ln39_reg_988_pp0_iter2_reg <= icmp_ln39_reg_988_pp0_iter1_reg;
                icmp_ln39_reg_988_pp0_iter3_reg <= icmp_ln39_reg_988_pp0_iter2_reg;
                icmp_ln39_reg_988_pp0_iter4_reg <= icmp_ln39_reg_988_pp0_iter3_reg;
                icmp_ln39_reg_988_pp0_iter5_reg <= icmp_ln39_reg_988_pp0_iter4_reg;
                icmp_ln39_reg_988_pp0_iter6_reg <= icmp_ln39_reg_988_pp0_iter5_reg;
                icmp_ln39_reg_988_pp0_iter7_reg <= icmp_ln39_reg_988_pp0_iter6_reg;
                icmp_ln39_reg_988_pp0_iter8_reg <= icmp_ln39_reg_988_pp0_iter7_reg;
                icmp_ln39_reg_988_pp0_iter9_reg <= icmp_ln39_reg_988_pp0_iter8_reg;
                icmp_ln47_reg_1032 <= icmp_ln47_fu_669_p2;
                k_mid2_reg_996_pp0_iter2_reg <= k_mid2_reg_996_pp0_iter1_reg;
                k_mid2_reg_996_pp0_iter3_reg <= k_mid2_reg_996_pp0_iter2_reg;
                k_mid2_reg_996_pp0_iter4_reg <= k_mid2_reg_996_pp0_iter3_reg;
                k_mid2_reg_996_pp0_iter5_reg <= k_mid2_reg_996_pp0_iter4_reg;
                k_mid2_reg_996_pp0_iter6_reg <= k_mid2_reg_996_pp0_iter5_reg;
                k_mid2_reg_996_pp0_iter7_reg <= k_mid2_reg_996_pp0_iter6_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                first_iter_0_reg_1004 <= first_iter_0_fu_481_p2;
                first_iter_0_reg_1004_pp0_iter1_reg <= first_iter_0_reg_1004;
                icmp_ln34_reg_979 <= icmp_ln34_fu_455_p2;
                icmp_ln34_reg_979_pp0_iter1_reg <= icmp_ln34_reg_979;
                icmp_ln39_2_reg_1013 <= icmp_ln39_2_fu_505_p2;
                icmp_ln39_2_reg_1013_pp0_iter1_reg <= icmp_ln39_2_reg_1013;
                icmp_ln39_reg_988 <= icmp_ln39_fu_467_p2;
                icmp_ln39_reg_988_pp0_iter1_reg <= icmp_ln39_reg_988;
                k_mid2_reg_996 <= k_mid2_fu_473_p3;
                k_mid2_reg_996_pp0_iter1_reg <= k_mid2_reg_996;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_reg_979_pp0_iter11_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                maximum_4_fu_142 <= maximum_5_fu_850_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln34_reg_1021 <= select_ln34_fu_536_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_1))) then
                sext_ln50_35_reg_202 <= sext_ln50_36_reg_225;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                sext_ln50_3_reg_926 <= sext_ln50_3_fu_395_p1;
            end if;
        end if;
    end process;
    zext_ln31_reg_969(11 downto 5) <= "0000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, icmp_ln31_fu_429_p2, ap_CS_fsm_state5, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, icmp_ln29_fu_399_p2, icmp_ln27_fu_374_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln27_fu_374_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln29_fu_399_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_429_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    CONV1_BIAS_address0 <= zext_ln27_fu_386_p1(4 - 1 downto 0);

    CONV1_BIAS_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            CONV1_BIAS_ce0_local <= ap_const_logic_1;
        else 
            CONV1_BIAS_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    CONV1_WEIGHT_address0 <= zext_ln50_fu_723_p1(9 - 1 downto 0);

    CONV1_WEIGHT_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            CONV1_WEIGHT_ce0_local <= ap_const_logic_1;
        else 
            CONV1_WEIGHT_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    accumulator_3_mid2_fu_743_p3 <= 
        ap_phi_mux_sext_ln50_38_phi_fu_297_p4 when (icmp_ln39_reg_988_pp0_iter10_reg(0) = '1') else 
        ap_phi_mux_accumulator_3_phi_fu_308_p4;
    add_ln1076_fu_784_p2 <= std_logic_vector(unsigned(zext_ln1075_fu_780_p1) + unsigned(ap_const_lv33_100));
    add_ln27_1_fu_368_p2 <= std_logic_vector(unsigned(phi_mul_fu_134) + unsigned(ap_const_lv9_1B));
    add_ln27_fu_380_p2 <= std_logic_vector(unsigned(oc_fu_138) + unsigned(ap_const_lv5_1));
    add_ln29_fu_405_p2 <= std_logic_vector(unsigned(oy_reg_214) + unsigned(ap_const_lv5_1));
    add_ln31_fu_435_p2 <= std_logic_vector(unsigned(ox_reg_237) + unsigned(ap_const_lv5_1));
    add_ln34_2_fu_511_p2 <= std_logic_vector(unsigned(ap_phi_mux_p_phi_fu_274_p4) + unsigned(ap_const_lv3_1));
    add_ln34_fu_461_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_248) + unsigned(ap_const_lv7_1));
    add_ln39_fu_499_p2 <= std_logic_vector(unsigned(k_mid2_fu_473_p3) + unsigned(ap_const_lv5_1));
    add_ln44_fu_606_p2 <= std_logic_vector(unsigned(trunc_ln42_2_fu_581_p4) + unsigned(ap_const_lv2_3));
    add_ln45_fu_633_p2 <= std_logic_vector(unsigned(trunc_ln43_fu_591_p1) + unsigned(ap_const_lv2_3));
    add_ln48_2_fu_707_p2 <= std_logic_vector(unsigned(shl_ln48_2_fu_699_p3) + unsigned(sext_ln45_2_fu_649_p1));
    add_ln48_fu_693_p2 <= std_logic_vector(unsigned(iy_fu_616_p2) + unsigned(shl_ln3_fu_685_p3));
    add_ln50_fu_718_p2 <= std_logic_vector(unsigned(zext_ln39_fu_559_p1) + unsigned(phi_mul_load_reg_898));
    add_ln57_fu_859_p2 <= std_logic_vector(unsigned(zext_ln31_reg_969) + unsigned(shl_ln_fu_764_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(5);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state19 <= ap_CS_fsm(6);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_412_assign_proc : process(first_iter_3_reg_940, first_iter_2_reg_965, icmp_ln34_reg_979_pp0_iter6_reg, first_iter_0_reg_1004_pp0_iter6_reg, first_iter_1_mid2_fu_529_p3)
    begin
                ap_condition_412 <= ((first_iter_1_mid2_fu_529_p3 = ap_const_lv1_1) and (first_iter_0_reg_1004_pp0_iter6_reg = ap_const_lv1_1) and (icmp_ln34_reg_979_pp0_iter6_reg = ap_const_lv1_0) and (first_iter_2_reg_965 = ap_const_lv1_1) and (first_iter_3_reg_940 = ap_const_lv1_1));
    end process;


    ap_condition_pp0_exit_iter11_state17_assign_proc : process(ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter11_state17 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter11_state17 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(icmp_ln34_fu_455_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln34_fu_455_p2 = ap_const_lv1_1))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln27_fu_374_p2)
    begin
        if ((((icmp_ln27_fu_374_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_accumulator_3_phi_fu_308_p4_assign_proc : process(accumulator_3_reg_305, icmp_ln34_reg_979_pp0_iter11_reg, ap_enable_reg_pp0_iter12, grp_fu_874_p3, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_reg_979_pp0_iter11_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_accumulator_3_phi_fu_308_p4 <= grp_fu_874_p3;
        else 
            ap_phi_mux_accumulator_3_phi_fu_308_p4 <= accumulator_3_reg_305;
        end if; 
    end process;


    ap_phi_mux_k_phi_fu_263_p4_assign_proc : process(k_reg_259, icmp_ln34_reg_979, ap_CS_fsm_pp0_stage0, add_ln39_reg_1008, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln34_reg_979 = ap_const_lv1_0))) then 
            ap_phi_mux_k_phi_fu_263_p4 <= add_ln39_reg_1008;
        else 
            ap_phi_mux_k_phi_fu_263_p4 <= k_reg_259;
        end if; 
    end process;


    ap_phi_mux_p_phi_fu_274_p4_assign_proc : process(p_reg_270, icmp_ln34_reg_979_pp0_iter7_reg, select_ln34_reg_1021, ap_enable_reg_pp0_iter8, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (icmp_ln34_reg_979_pp0_iter7_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_p_phi_fu_274_p4 <= select_ln34_reg_1021;
        else 
            ap_phi_mux_p_phi_fu_274_p4 <= p_reg_270;
        end if; 
    end process;


    ap_phi_mux_sext_ln50_31_phi_fu_339_p10_assign_proc : process(first_iter_3_reg_940, first_iter_2_reg_965, icmp_ln34_reg_979_pp0_iter10_reg, first_iter_0_reg_1004_pp0_iter10_reg, first_iter_1_mid2_reg_1017_pp0_iter10_reg, accumulator_3_mid2_fu_743_p3, ap_phi_reg_pp0_iter11_sext_ln50_31_reg_336)
    begin
        if ((((first_iter_1_mid2_reg_1017_pp0_iter10_reg = ap_const_lv1_1) and (first_iter_0_reg_1004_pp0_iter10_reg = ap_const_lv1_1) and (icmp_ln34_reg_979_pp0_iter10_reg = ap_const_lv1_0) and (first_iter_2_reg_965 = ap_const_lv1_1) and (first_iter_3_reg_940 = ap_const_lv1_0)) or ((first_iter_1_mid2_reg_1017_pp0_iter10_reg = ap_const_lv1_1) and (first_iter_0_reg_1004_pp0_iter10_reg = ap_const_lv1_1) and (icmp_ln34_reg_979_pp0_iter10_reg = ap_const_lv1_0) and (first_iter_2_reg_965 = ap_const_lv1_0)) or ((first_iter_1_mid2_reg_1017_pp0_iter10_reg = ap_const_lv1_0) and (first_iter_0_reg_1004_pp0_iter10_reg = ap_const_lv1_1) and (icmp_ln34_reg_979_pp0_iter10_reg = ap_const_lv1_0)) or ((first_iter_0_reg_1004_pp0_iter10_reg = ap_const_lv1_0) and (icmp_ln34_reg_979_pp0_iter10_reg = ap_const_lv1_0)))) then 
            ap_phi_mux_sext_ln50_31_phi_fu_339_p10 <= accumulator_3_mid2_fu_743_p3;
        else 
            ap_phi_mux_sext_ln50_31_phi_fu_339_p10 <= ap_phi_reg_pp0_iter11_sext_ln50_31_reg_336;
        end if; 
    end process;


    ap_phi_mux_sext_ln50_38_phi_fu_297_p4_assign_proc : process(sext_ln50_38_reg_293, sext_ln50_39_reg_315, icmp_ln34_reg_979_pp0_iter11_reg, ap_enable_reg_pp0_iter12, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_reg_979_pp0_iter11_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_sext_ln50_38_phi_fu_297_p4 <= sext_ln50_39_reg_315;
        else 
            ap_phi_mux_sext_ln50_38_phi_fu_297_p4 <= sext_ln50_38_reg_293;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_sext_ln50_31_reg_336 <= "XXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_sext_ln50_39_reg_315 <= "XXXXXXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln27_fu_374_p2)
    begin
        if (((icmp_ln27_fu_374_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_830_p2 <= (icmp_ln1078_fu_800_p2 or icmp_ln1074_fu_772_p2);
    first_iter_0_fu_481_p2 <= "1" when (k_mid2_fu_473_p3 = ap_const_lv5_0) else "0";
    first_iter_120_fu_523_p2 <= "1" when (ap_phi_mux_p_phi_fu_274_p4 = ap_const_lv3_0) else "0";
    first_iter_1_mid1_fu_517_p2 <= "1" when (add_ln34_2_fu_511_p2 = ap_const_lv3_0) else "0";
    first_iter_1_mid2_fu_529_p3 <= 
        first_iter_1_mid1_fu_517_p2 when (icmp_ln39_reg_988_pp0_iter6_reg(0) = '1') else 
        first_iter_120_fu_523_p2;
    first_iter_2_fu_441_p2 <= "1" when (ox_reg_237 = ap_const_lv5_0) else "0";
    first_iter_3_fu_411_p2 <= "1" when (oy_reg_214 = ap_const_lv5_0) else "0";
    grp_fu_493_p1 <= ap_const_lv5_3(3 - 1 downto 0);
    icmp_ln1074_fu_772_p2 <= "1" when (signed(grp_fu_874_p3) < signed(ap_const_lv20_1)) else "0";
    icmp_ln1078_fu_800_p2 <= "0" when (tmp_5_fu_790_p4 = ap_const_lv17_0) else "1";
    icmp_ln27_fu_374_p2 <= "1" when (oc_fu_138 = ap_const_lv5_10) else "0";
    icmp_ln29_fu_399_p2 <= "1" when (oy_reg_214 = ap_const_lv5_10) else "0";
    icmp_ln31_fu_429_p2 <= "1" when (ox_reg_237 = ap_const_lv5_10) else "0";
    icmp_ln34_2_fu_543_p2 <= "1" when (select_ln34_fu_536_p3 = ap_const_lv3_3) else "0";
    icmp_ln34_fu_455_p2 <= "1" when (indvar_flatten_reg_248 = ap_const_lv7_6C) else "0";
    icmp_ln39_2_fu_505_p2 <= "1" when (add_ln39_fu_499_p2 = ap_const_lv5_1B) else "0";
    icmp_ln39_fu_467_p2 <= "1" when (ap_phi_mux_k_phi_fu_263_p4 = ap_const_lv5_1B) else "0";
    icmp_ln47_fu_669_p2 <= "1" when (tmp_4_fu_659_p4 = ap_const_lv2_0) else "0";
    icmp_ln55_fu_844_p2 <= "1" when (unsigned(value_fu_836_p3) > unsigned(select_ln34_2_fu_757_p3)) else "0";
    input_chw_address0 <= zext_ln48_fu_713_p1(12 - 1 downto 0);
    input_chw_ce0 <= input_chw_ce0_local;

    input_chw_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_chw_ce0_local <= ap_const_logic_1;
        else 
            input_chw_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    ix_fu_643_p2 <= std_logic_vector(signed(sext_ln45_fu_639_p1) + signed(zext_ln45_fu_629_p1));
    iy_fu_616_p2 <= std_logic_vector(signed(sext_ln44_fu_612_p1) + signed(zext_ln44_fu_602_p1));
    k_mid2_fu_473_p3 <= 
        ap_const_lv5_0 when (icmp_ln39_fu_467_p2(0) = '1') else 
        ap_phi_mux_k_phi_fu_263_p4;
    maximum_5_fu_850_p3 <= 
        value_fu_836_p3 when (icmp_ln55_fu_844_p2(0) = '1') else 
        select_ln34_2_fu_757_p3;
    mul_ln41_fu_565_p0 <= mul_ln41_fu_565_p00(5 - 1 downto 0);
    mul_ln41_fu_565_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_reg_996_pp0_iter7_reg),11));
    mul_ln41_fu_565_p1 <= ap_const_lv11_39(7 - 1 downto 0);
    mul_ln42_fu_575_p0 <= mul_ln42_fu_575_p00(5 - 1 downto 0);
    mul_ln42_fu_575_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_487_p2),9));
    mul_ln42_fu_575_p1 <= ap_const_lv9_16(6 - 1 downto 0);
    not_icmp_ln1074_fu_816_p2 <= (icmp_ln1074_fu_772_p2 xor ap_const_lv1_1);
    or_ln47_fu_653_p2 <= (iy_fu_616_p2 or ix_fu_643_p2);
    pixel_2_fu_728_p3 <= 
        input_chw_q0 when (icmp_ln47_reg_1032(0) = '1') else 
        ap_const_lv8_0;
    select_ln1078_cast_fu_822_p3 <= 
        ap_const_lv7_7F when (not_icmp_ln1074_fu_816_p2(0) = '1') else 
        ap_const_lv7_0;
    select_ln34_2_fu_757_p3 <= 
        maximum_4_fu_142 when (icmp_ln39_reg_988_pp0_iter11_reg(0) = '1') else 
        maximum_reg_281;
    select_ln34_fu_536_p3 <= 
        add_ln34_2_fu_511_p2 when (icmp_ln39_reg_988_pp0_iter6_reg(0) = '1') else 
        ap_phi_mux_p_phi_fu_274_p4;
        sext_ln1075_fu_777_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_874_p3),32));

        sext_ln44_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln44_fu_606_p2),7));

        sext_ln45_2_fu_649_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ix_fu_643_p2),12));

        sext_ln45_fu_639_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_fu_633_p2),7));

        sext_ln50_3_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(CONV1_BIAS_q0),20));

    shl_ln3_fu_685_p3 <= (tmp_2_fu_675_p4 & ap_const_lv5_0);
    shl_ln48_2_fu_699_p3 <= (add_ln48_fu_693_p2 & ap_const_lv5_0);
    shl_ln_fu_764_p4 <= ((trunc_ln57_reg_921 & trunc_ln57_2_reg_944) & ap_const_lv4_0);
    stage1_address1 <= zext_ln57_fu_864_p1(12 - 1 downto 0);
    stage1_ce1 <= stage1_ce1_local;

    stage1_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stage1_ce1_local <= ap_const_logic_1;
        else 
            stage1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    stage1_d1 <= maximum_5_fu_850_p3;
    stage1_we1 <= stage1_we1_local;

    stage1_we1_local_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln39_2_reg_1013_pp0_iter11_reg, icmp_ln34_2_reg_1028_pp0_iter11_reg, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_2_reg_1028_pp0_iter11_reg = ap_const_lv1_1) and (icmp_ln39_2_reg_1013_pp0_iter11_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stage1_we1_local <= ap_const_logic_1;
        else 
            stage1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_595_p3 <= (trunc_ln57_2_reg_944 & tmp_fu_552_p3);
    tmp4_fu_622_p3 <= (trunc_ln37_reg_974 & trunc_ln34_fu_549_p1);
    tmp_2_fu_675_p4 <= mul_ln41_fu_565_p2(10 downto 9);
    tmp_4_fu_659_p4 <= or_ln47_fu_653_p2(6 downto 5);
    tmp_5_fu_790_p4 <= add_ln1076_fu_784_p2(32 downto 16);
    tmp_fu_552_p3 <= select_ln34_reg_1021(1 downto 1);
    trunc_ln34_fu_549_p1 <= select_ln34_reg_1021(1 - 1 downto 0);
    trunc_ln37_fu_451_p1 <= ox_reg_237(4 - 1 downto 0);
    trunc_ln42_2_fu_581_p4 <= mul_ln42_fu_575_p2(7 downto 6);
    trunc_ln43_fu_591_p1 <= grp_fu_493_p2(2 - 1 downto 0);
    trunc_ln57_2_fu_417_p1 <= oy_reg_214(4 - 1 downto 0);
    trunc_ln57_fu_391_p1 <= oc_fu_138(4 - 1 downto 0);
    trunc_ln9_fu_806_p4 <= add_ln1076_fu_784_p2(15 downto 9);
    value_fu_836_p3 <= 
        select_ln1078_cast_fu_822_p3 when (empty_fu_830_p2(0) = '1') else 
        trunc_ln9_fu_806_p4;
    zext_ln1075_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1075_fu_777_p1),33));
    zext_ln27_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oc_fu_138),64));
    zext_ln31_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ox_reg_237),12));
    zext_ln39_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_reg_996_pp0_iter7_reg),9));
    zext_ln44_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_595_p3),7));
    zext_ln45_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_fu_622_p3),7));
    zext_ln48_fu_713_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln48_2_fu_707_p2),64));
    zext_ln50_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln50_fu_718_p2),64));
    zext_ln57_fu_864_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln57_fu_859_p2),64));
end behav;
