// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cifar10_cnn_conv_relu_pool_3_16_32_9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_chw_address0,
        input_chw_ce0,
        input_chw_q0,
        stage1_address1,
        stage1_ce1,
        stage1_we1,
        stage1_d1
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_pp0_stage0 = 7'd32;
parameter    ap_ST_fsm_state19 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] input_chw_address0;
output   input_chw_ce0;
input  [7:0] input_chw_q0;
output  [11:0] stage1_address1;
output   stage1_ce1;
output   stage1_we1;
output  [6:0] stage1_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] CONV1_BIAS_address0;
wire   [13:0] CONV1_BIAS_q0;
wire   [8:0] CONV1_WEIGHT_address0;
wire  signed [7:0] CONV1_WEIGHT_q0;
reg   [6:0] indvar_flatten_reg_248;
reg   [4:0] k_reg_259;
reg   [2:0] p_reg_270;
reg   [6:0] maximum_reg_281;
reg   [19:0] sext_ln50_38_reg_293;
reg   [19:0] accumulator_3_reg_305;
reg   [19:0] sext_ln50_39_reg_315;
reg   [8:0] phi_mul_load_reg_898;
wire    ap_CS_fsm_state2;
wire   [8:0] add_ln27_1_fu_368_p2;
reg   [8:0] add_ln27_1_reg_903;
wire   [4:0] add_ln27_fu_380_p2;
reg   [4:0] add_ln27_reg_911;
wire   [3:0] trunc_ln57_fu_391_p1;
reg   [3:0] trunc_ln57_reg_921;
wire  signed [19:0] sext_ln50_3_fu_395_p1;
reg  signed [19:0] sext_ln50_3_reg_926;
wire    ap_CS_fsm_state3;
wire   [4:0] add_ln29_fu_405_p2;
reg   [4:0] add_ln29_reg_935;
wire    ap_CS_fsm_state4;
wire   [0:0] first_iter_3_fu_411_p2;
reg   [0:0] first_iter_3_reg_940;
wire   [3:0] trunc_ln57_2_fu_417_p1;
reg   [3:0] trunc_ln57_2_reg_944;
wire   [0:0] icmp_ln31_fu_429_p2;
wire    ap_CS_fsm_state5;
wire   [4:0] add_ln31_fu_435_p2;
reg   [4:0] add_ln31_reg_954;
wire   [0:0] first_iter_2_fu_441_p2;
reg   [0:0] first_iter_2_reg_965;
wire   [11:0] zext_ln31_fu_447_p1;
reg   [11:0] zext_ln31_reg_969;
wire   [3:0] trunc_ln37_fu_451_p1;
reg   [3:0] trunc_ln37_reg_974;
wire   [0:0] icmp_ln34_fu_455_p2;
reg   [0:0] icmp_ln34_reg_979;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln34_reg_979_pp0_iter1_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter2_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter3_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter4_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter5_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter6_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter7_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter8_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter9_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter10_reg;
reg   [0:0] icmp_ln34_reg_979_pp0_iter11_reg;
wire   [6:0] add_ln34_fu_461_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln39_fu_467_p2;
reg   [0:0] icmp_ln39_reg_988;
reg   [0:0] icmp_ln39_reg_988_pp0_iter1_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter2_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter3_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter4_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter5_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter6_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter7_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter8_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter9_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter10_reg;
reg   [0:0] icmp_ln39_reg_988_pp0_iter11_reg;
wire   [4:0] k_mid2_fu_473_p3;
reg   [4:0] k_mid2_reg_996;
reg   [4:0] k_mid2_reg_996_pp0_iter1_reg;
reg   [4:0] k_mid2_reg_996_pp0_iter2_reg;
reg   [4:0] k_mid2_reg_996_pp0_iter3_reg;
reg   [4:0] k_mid2_reg_996_pp0_iter4_reg;
reg   [4:0] k_mid2_reg_996_pp0_iter5_reg;
reg   [4:0] k_mid2_reg_996_pp0_iter6_reg;
reg   [4:0] k_mid2_reg_996_pp0_iter7_reg;
wire   [0:0] first_iter_0_fu_481_p2;
reg   [0:0] first_iter_0_reg_1004;
reg   [0:0] first_iter_0_reg_1004_pp0_iter1_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter2_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter3_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter4_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter5_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter6_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter7_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter8_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter9_reg;
reg   [0:0] first_iter_0_reg_1004_pp0_iter10_reg;
wire   [4:0] add_ln39_fu_499_p2;
reg   [4:0] add_ln39_reg_1008;
wire   [0:0] icmp_ln39_2_fu_505_p2;
reg   [0:0] icmp_ln39_2_reg_1013;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter1_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter2_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter3_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter4_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter5_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter6_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter7_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter8_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter9_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter10_reg;
reg   [0:0] icmp_ln39_2_reg_1013_pp0_iter11_reg;
wire   [0:0] first_iter_1_mid2_fu_529_p3;
reg   [0:0] first_iter_1_mid2_reg_1017;
reg   [0:0] first_iter_1_mid2_reg_1017_pp0_iter8_reg;
reg   [0:0] first_iter_1_mid2_reg_1017_pp0_iter9_reg;
reg   [0:0] first_iter_1_mid2_reg_1017_pp0_iter10_reg;
wire   [2:0] select_ln34_fu_536_p3;
reg   [2:0] select_ln34_reg_1021;
reg    ap_enable_reg_pp0_iter7;
wire   [0:0] icmp_ln34_2_fu_543_p2;
reg   [0:0] icmp_ln34_2_reg_1028;
reg   [0:0] icmp_ln34_2_reg_1028_pp0_iter8_reg;
reg   [0:0] icmp_ln34_2_reg_1028_pp0_iter9_reg;
reg   [0:0] icmp_ln34_2_reg_1028_pp0_iter10_reg;
reg   [0:0] icmp_ln34_2_reg_1028_pp0_iter11_reg;
wire   [0:0] icmp_ln47_fu_669_p2;
reg   [0:0] icmp_ln47_reg_1032;
wire   [6:0] select_ln34_2_fu_757_p3;
reg    ap_enable_reg_pp0_iter12;
wire  signed [19:0] grp_fu_874_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_condition_pp0_exit_iter11_state17;
reg   [19:0] sext_ln50_35_reg_202;
reg   [4:0] oy_reg_214;
reg   [19:0] sext_ln50_36_reg_225;
wire   [0:0] icmp_ln29_fu_399_p2;
wire    ap_CS_fsm_state19;
reg   [4:0] ox_reg_237;
reg   [4:0] ap_phi_mux_k_phi_fu_263_p4;
wire    ap_block_pp0_stage0;
reg   [2:0] ap_phi_mux_p_phi_fu_274_p4;
reg   [19:0] ap_phi_mux_sext_ln50_38_phi_fu_297_p4;
reg   [19:0] ap_phi_mux_accumulator_3_phi_fu_308_p4;
reg   [19:0] ap_phi_reg_pp0_iter11_sext_ln50_39_reg_315;
reg    ap_predicate_pred369_state17;
wire   [19:0] ap_phi_reg_pp0_iter0_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter1_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter2_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter3_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter4_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter5_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter6_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter7_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter9_sext_ln50_39_reg_315;
reg   [19:0] ap_phi_reg_pp0_iter10_sext_ln50_39_reg_315;
reg  signed [19:0] ap_phi_mux_sext_ln50_31_phi_fu_339_p10;
wire   [19:0] accumulator_3_mid2_fu_743_p3;
reg   [19:0] ap_phi_reg_pp0_iter11_sext_ln50_31_reg_336;
wire   [19:0] ap_phi_reg_pp0_iter0_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter1_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter2_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter3_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter4_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter5_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter6_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter7_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter9_sext_ln50_31_reg_336;
reg   [19:0] ap_phi_reg_pp0_iter10_sext_ln50_31_reg_336;
wire   [63:0] zext_ln27_fu_386_p1;
wire   [0:0] icmp_ln27_fu_374_p2;
wire   [63:0] zext_ln48_fu_713_p1;
wire   [63:0] zext_ln50_fu_723_p1;
wire   [63:0] zext_ln57_fu_864_p1;
reg   [8:0] phi_mul_fu_134;
reg   [4:0] oc_fu_138;
reg   [6:0] maximum_4_fu_142;
wire   [6:0] maximum_5_fu_850_p3;
reg    CONV1_BIAS_ce0_local;
reg    input_chw_ce0_local;
reg    CONV1_WEIGHT_ce0_local;
reg    stage1_we1_local;
reg    stage1_ce1_local;
wire   [2:0] grp_fu_493_p1;
wire   [2:0] add_ln34_2_fu_511_p2;
wire   [0:0] first_iter_1_mid1_fu_517_p2;
wire   [0:0] first_iter_120_fu_523_p2;
wire   [4:0] mul_ln41_fu_565_p0;
wire   [6:0] mul_ln41_fu_565_p1;
wire   [4:0] grp_fu_487_p2;
wire   [4:0] mul_ln42_fu_575_p0;
wire   [5:0] mul_ln42_fu_575_p1;
wire   [8:0] mul_ln42_fu_575_p2;
wire   [1:0] grp_fu_493_p2;
wire   [0:0] tmp_fu_552_p3;
wire   [4:0] tmp1_fu_595_p3;
wire   [1:0] trunc_ln42_2_fu_581_p4;
wire   [1:0] add_ln44_fu_606_p2;
wire  signed [6:0] sext_ln44_fu_612_p1;
wire   [6:0] zext_ln44_fu_602_p1;
wire   [0:0] trunc_ln34_fu_549_p1;
wire   [4:0] tmp4_fu_622_p3;
wire   [1:0] trunc_ln43_fu_591_p1;
wire   [1:0] add_ln45_fu_633_p2;
wire  signed [6:0] sext_ln45_fu_639_p1;
wire   [6:0] zext_ln45_fu_629_p1;
wire  signed [6:0] ix_fu_643_p2;
wire   [6:0] iy_fu_616_p2;
wire   [6:0] or_ln47_fu_653_p2;
wire   [1:0] tmp_4_fu_659_p4;
wire   [10:0] mul_ln41_fu_565_p2;
wire   [1:0] tmp_2_fu_675_p4;
wire   [6:0] shl_ln3_fu_685_p3;
wire   [6:0] add_ln48_fu_693_p2;
wire   [11:0] shl_ln48_2_fu_699_p3;
wire  signed [11:0] sext_ln45_2_fu_649_p1;
wire   [11:0] add_ln48_2_fu_707_p2;
wire   [8:0] zext_ln39_fu_559_p1;
wire   [8:0] add_ln50_fu_718_p2;
wire  signed [7:0] pixel_2_fu_728_p3;
wire  signed [31:0] sext_ln1075_fu_777_p1;
wire   [32:0] zext_ln1075_fu_780_p1;
wire   [32:0] add_ln1076_fu_784_p2;
wire   [16:0] tmp_5_fu_790_p4;
wire   [0:0] icmp_ln1074_fu_772_p2;
wire   [0:0] not_icmp_ln1074_fu_816_p2;
wire   [0:0] icmp_ln1078_fu_800_p2;
wire   [0:0] empty_fu_830_p2;
wire   [6:0] select_ln1078_cast_fu_822_p3;
wire   [6:0] trunc_ln9_fu_806_p4;
wire   [6:0] value_fu_836_p3;
wire   [0:0] icmp_ln55_fu_844_p2;
wire   [11:0] shl_ln_fu_764_p4;
wire   [11:0] add_ln57_fu_859_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [10:0] mul_ln41_fu_565_p00;
wire   [8:0] mul_ln42_fu_575_p00;
reg    ap_condition_412;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 phi_mul_fu_134 = 9'd0;
#0 oc_fu_138 = 5'd0;
#0 maximum_4_fu_142 = 7'd0;
end

cifar10_cnn_conv_relu_pool_3_16_32_9_s_CONV1_BIAS_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
CONV1_BIAS_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONV1_BIAS_address0),
    .ce0(CONV1_BIAS_ce0_local),
    .q0(CONV1_BIAS_q0)
);

cifar10_cnn_conv_relu_pool_3_16_32_9_s_CONV1_WEIGHT_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 432 ),
    .AddressWidth( 9 ))
CONV1_WEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONV1_WEIGHT_address0),
    .ce0(CONV1_WEIGHT_ce0_local),
    .q0(CONV1_WEIGHT_q0)
);

cifar10_cnn_urem_5ns_5ns_5_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 5 ))
urem_5ns_5ns_5_9_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(k_mid2_fu_473_p3),
    .din1(5'd9),
    .ce(1'b1),
    .dout(grp_fu_487_p2)
);

cifar10_cnn_urem_5ns_3ns_2_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(k_mid2_fu_473_p3),
    .din1(grp_fu_493_p1),
    .ce(1'b1),
    .dout(grp_fu_493_p2)
);

cifar10_cnn_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U7(
    .din0(mul_ln41_fu_565_p0),
    .din1(mul_ln41_fu_565_p1),
    .dout(mul_ln41_fu_565_p2)
);

cifar10_cnn_mul_5ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_5ns_6ns_9_1_1_U8(
    .din0(mul_ln42_fu_575_p0),
    .din1(mul_ln42_fu_575_p1),
    .dout(mul_ln42_fu_575_p2)
);

cifar10_cnn_mac_muladd_8s_8s_20s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 20 ))
mac_muladd_8s_8s_20s_20_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(CONV1_WEIGHT_q0),
    .din1(pixel_2_fu_728_p3),
    .din2(ap_phi_mux_sext_ln50_31_phi_fu_339_p10),
    .ce(1'b1),
    .dout(grp_fu_874_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end else if ((((ap_enable_reg_pp0_iter10 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter11_state17) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0)))) begin
            ap_enable_reg_pp0_iter11 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter11_state17) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter10;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter12 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_reg_979_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accumulator_3_reg_305 <= grp_fu_874_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0))) begin
        accumulator_3_reg_305 <= sext_ln50_36_reg_225;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_412)) begin
            ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336 <= sext_ln50_3_reg_926;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter7_sext_ln50_31_reg_336;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_412)) begin
            ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315 <= sext_ln50_3_reg_926;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter7_sext_ln50_39_reg_315;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_fu_455_p2 == 1'd0))) begin
        indvar_flatten_reg_248 <= add_ln34_fu_461_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0))) begin
        indvar_flatten_reg_248 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_979 == 1'd0))) begin
        k_reg_259 <= add_ln39_reg_1008;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0))) begin
        k_reg_259 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_reg_979_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        maximum_reg_281 <= select_ln34_2_fu_757_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0))) begin
        maximum_reg_281 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        oc_fu_138 <= 5'd0;
    end else if (((icmp_ln29_fu_399_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        oc_fu_138 <= add_ln27_reg_911;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        ox_reg_237 <= add_ln31_reg_954;
    end else if (((icmp_ln29_fu_399_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ox_reg_237 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd1))) begin
        oy_reg_214 <= add_ln29_reg_935;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        oy_reg_214 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln34_reg_979_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_reg_270 <= select_ln34_reg_1021;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0))) begin
        p_reg_270 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_fu_134 <= 9'd0;
    end else if (((icmp_ln29_fu_399_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_mul_fu_134 <= add_ln27_1_reg_903;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        sext_ln50_36_reg_225 <= sext_ln50_38_reg_293;
    end else if (((icmp_ln29_fu_399_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sext_ln50_36_reg_225 <= sext_ln50_35_reg_202;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_reg_979_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sext_ln50_38_reg_293 <= sext_ln50_39_reg_315;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd0))) begin
        sext_ln50_38_reg_293 <= sext_ln50_36_reg_225;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_pred369_state17 == 1'b1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (first_iter_1_mid2_reg_1017_pp0_iter10_reg == 1'd1) & (first_iter_0_reg_1004_pp0_iter10_reg == 1'd1) & (icmp_ln34_reg_979_pp0_iter10_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_2_reg_965 == 1'd0)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (first_iter_1_mid2_reg_1017_pp0_iter10_reg == 1'd0) & (first_iter_0_reg_1004_pp0_iter10_reg == 1'd1) & (icmp_ln34_reg_979_pp0_iter10_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (first_iter_0_reg_1004_pp0_iter10_reg == 1'd0) & (icmp_ln34_reg_979_pp0_iter10_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sext_ln50_39_reg_315 <= ap_phi_mux_sext_ln50_38_phi_fu_297_p4;
    end else if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter11_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln27_1_reg_903 <= add_ln27_1_fu_368_p2;
        add_ln27_reg_911 <= add_ln27_fu_380_p2;
        phi_mul_load_reg_898 <= phi_mul_fu_134;
        trunc_ln57_reg_921 <= trunc_ln57_fu_391_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln29_reg_935 <= add_ln29_fu_405_p2;
        first_iter_3_reg_940 <= first_iter_3_fu_411_p2;
        trunc_ln57_2_reg_944 <= trunc_ln57_2_fu_417_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln31_reg_954 <= add_ln31_fu_435_p2;
        first_iter_2_reg_965 <= first_iter_2_fu_441_p2;
        trunc_ln37_reg_974 <= trunc_ln37_fu_451_p1;
        zext_ln31_reg_969[4 : 0] <= zext_ln31_fu_447_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln39_reg_1008 <= add_ln39_fu_499_p2;
        ap_phi_reg_pp0_iter1_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter0_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter1_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter0_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter9_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter10_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter9_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter10_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter11_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter10_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter1_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter2_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter1_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter2_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter3_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter2_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter3_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter4_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter3_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter4_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter5_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter4_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter5_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter6_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter5_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter6_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter7_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter6_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_sext_ln50_31_reg_336 <= ap_phi_reg_pp0_iter8_sext_ln50_31_reg_336;
        ap_phi_reg_pp0_iter9_sext_ln50_39_reg_315 <= ap_phi_reg_pp0_iter8_sext_ln50_39_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_predicate_pred369_state17 <= ((first_iter_1_mid2_reg_1017_pp0_iter9_reg == 1'd1) & (first_iter_0_reg_1004_pp0_iter9_reg == 1'd1) & (icmp_ln34_reg_979_pp0_iter9_reg == 1'd0) & (first_iter_2_reg_965 == 1'd1) & (first_iter_3_reg_940 == 1'd0));
        first_iter_0_reg_1004_pp0_iter10_reg <= first_iter_0_reg_1004_pp0_iter9_reg;
        first_iter_0_reg_1004_pp0_iter2_reg <= first_iter_0_reg_1004_pp0_iter1_reg;
        first_iter_0_reg_1004_pp0_iter3_reg <= first_iter_0_reg_1004_pp0_iter2_reg;
        first_iter_0_reg_1004_pp0_iter4_reg <= first_iter_0_reg_1004_pp0_iter3_reg;
        first_iter_0_reg_1004_pp0_iter5_reg <= first_iter_0_reg_1004_pp0_iter4_reg;
        first_iter_0_reg_1004_pp0_iter6_reg <= first_iter_0_reg_1004_pp0_iter5_reg;
        first_iter_0_reg_1004_pp0_iter7_reg <= first_iter_0_reg_1004_pp0_iter6_reg;
        first_iter_0_reg_1004_pp0_iter8_reg <= first_iter_0_reg_1004_pp0_iter7_reg;
        first_iter_0_reg_1004_pp0_iter9_reg <= first_iter_0_reg_1004_pp0_iter8_reg;
        first_iter_1_mid2_reg_1017 <= first_iter_1_mid2_fu_529_p3;
        first_iter_1_mid2_reg_1017_pp0_iter10_reg <= first_iter_1_mid2_reg_1017_pp0_iter9_reg;
        first_iter_1_mid2_reg_1017_pp0_iter8_reg <= first_iter_1_mid2_reg_1017;
        first_iter_1_mid2_reg_1017_pp0_iter9_reg <= first_iter_1_mid2_reg_1017_pp0_iter8_reg;
        icmp_ln34_2_reg_1028 <= icmp_ln34_2_fu_543_p2;
        icmp_ln34_2_reg_1028_pp0_iter10_reg <= icmp_ln34_2_reg_1028_pp0_iter9_reg;
        icmp_ln34_2_reg_1028_pp0_iter11_reg <= icmp_ln34_2_reg_1028_pp0_iter10_reg;
        icmp_ln34_2_reg_1028_pp0_iter8_reg <= icmp_ln34_2_reg_1028;
        icmp_ln34_2_reg_1028_pp0_iter9_reg <= icmp_ln34_2_reg_1028_pp0_iter8_reg;
        icmp_ln34_reg_979_pp0_iter10_reg <= icmp_ln34_reg_979_pp0_iter9_reg;
        icmp_ln34_reg_979_pp0_iter11_reg <= icmp_ln34_reg_979_pp0_iter10_reg;
        icmp_ln34_reg_979_pp0_iter2_reg <= icmp_ln34_reg_979_pp0_iter1_reg;
        icmp_ln34_reg_979_pp0_iter3_reg <= icmp_ln34_reg_979_pp0_iter2_reg;
        icmp_ln34_reg_979_pp0_iter4_reg <= icmp_ln34_reg_979_pp0_iter3_reg;
        icmp_ln34_reg_979_pp0_iter5_reg <= icmp_ln34_reg_979_pp0_iter4_reg;
        icmp_ln34_reg_979_pp0_iter6_reg <= icmp_ln34_reg_979_pp0_iter5_reg;
        icmp_ln34_reg_979_pp0_iter7_reg <= icmp_ln34_reg_979_pp0_iter6_reg;
        icmp_ln34_reg_979_pp0_iter8_reg <= icmp_ln34_reg_979_pp0_iter7_reg;
        icmp_ln34_reg_979_pp0_iter9_reg <= icmp_ln34_reg_979_pp0_iter8_reg;
        icmp_ln39_2_reg_1013_pp0_iter10_reg <= icmp_ln39_2_reg_1013_pp0_iter9_reg;
        icmp_ln39_2_reg_1013_pp0_iter11_reg <= icmp_ln39_2_reg_1013_pp0_iter10_reg;
        icmp_ln39_2_reg_1013_pp0_iter2_reg <= icmp_ln39_2_reg_1013_pp0_iter1_reg;
        icmp_ln39_2_reg_1013_pp0_iter3_reg <= icmp_ln39_2_reg_1013_pp0_iter2_reg;
        icmp_ln39_2_reg_1013_pp0_iter4_reg <= icmp_ln39_2_reg_1013_pp0_iter3_reg;
        icmp_ln39_2_reg_1013_pp0_iter5_reg <= icmp_ln39_2_reg_1013_pp0_iter4_reg;
        icmp_ln39_2_reg_1013_pp0_iter6_reg <= icmp_ln39_2_reg_1013_pp0_iter5_reg;
        icmp_ln39_2_reg_1013_pp0_iter7_reg <= icmp_ln39_2_reg_1013_pp0_iter6_reg;
        icmp_ln39_2_reg_1013_pp0_iter8_reg <= icmp_ln39_2_reg_1013_pp0_iter7_reg;
        icmp_ln39_2_reg_1013_pp0_iter9_reg <= icmp_ln39_2_reg_1013_pp0_iter8_reg;
        icmp_ln39_reg_988_pp0_iter10_reg <= icmp_ln39_reg_988_pp0_iter9_reg;
        icmp_ln39_reg_988_pp0_iter11_reg <= icmp_ln39_reg_988_pp0_iter10_reg;
        icmp_ln39_reg_988_pp0_iter2_reg <= icmp_ln39_reg_988_pp0_iter1_reg;
        icmp_ln39_reg_988_pp0_iter3_reg <= icmp_ln39_reg_988_pp0_iter2_reg;
        icmp_ln39_reg_988_pp0_iter4_reg <= icmp_ln39_reg_988_pp0_iter3_reg;
        icmp_ln39_reg_988_pp0_iter5_reg <= icmp_ln39_reg_988_pp0_iter4_reg;
        icmp_ln39_reg_988_pp0_iter6_reg <= icmp_ln39_reg_988_pp0_iter5_reg;
        icmp_ln39_reg_988_pp0_iter7_reg <= icmp_ln39_reg_988_pp0_iter6_reg;
        icmp_ln39_reg_988_pp0_iter8_reg <= icmp_ln39_reg_988_pp0_iter7_reg;
        icmp_ln39_reg_988_pp0_iter9_reg <= icmp_ln39_reg_988_pp0_iter8_reg;
        icmp_ln47_reg_1032 <= icmp_ln47_fu_669_p2;
        k_mid2_reg_996_pp0_iter2_reg <= k_mid2_reg_996_pp0_iter1_reg;
        k_mid2_reg_996_pp0_iter3_reg <= k_mid2_reg_996_pp0_iter2_reg;
        k_mid2_reg_996_pp0_iter4_reg <= k_mid2_reg_996_pp0_iter3_reg;
        k_mid2_reg_996_pp0_iter5_reg <= k_mid2_reg_996_pp0_iter4_reg;
        k_mid2_reg_996_pp0_iter6_reg <= k_mid2_reg_996_pp0_iter5_reg;
        k_mid2_reg_996_pp0_iter7_reg <= k_mid2_reg_996_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_1004 <= first_iter_0_fu_481_p2;
        first_iter_0_reg_1004_pp0_iter1_reg <= first_iter_0_reg_1004;
        icmp_ln34_reg_979 <= icmp_ln34_fu_455_p2;
        icmp_ln34_reg_979_pp0_iter1_reg <= icmp_ln34_reg_979;
        icmp_ln39_2_reg_1013 <= icmp_ln39_2_fu_505_p2;
        icmp_ln39_2_reg_1013_pp0_iter1_reg <= icmp_ln39_2_reg_1013;
        icmp_ln39_reg_988 <= icmp_ln39_fu_467_p2;
        icmp_ln39_reg_988_pp0_iter1_reg <= icmp_ln39_reg_988;
        k_mid2_reg_996 <= k_mid2_fu_473_p3;
        k_mid2_reg_996_pp0_iter1_reg <= k_mid2_reg_996;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_reg_979_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        maximum_4_fu_142 <= maximum_5_fu_850_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln34_reg_1021 <= select_ln34_fu_536_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd1))) begin
        sext_ln50_35_reg_202 <= sext_ln50_36_reg_225;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sext_ln50_3_reg_926 <= sext_ln50_3_fu_395_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        CONV1_BIAS_ce0_local = 1'b1;
    end else begin
        CONV1_BIAS_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        CONV1_WEIGHT_ce0_local = 1'b1;
    end else begin
        CONV1_WEIGHT_ce0_local = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b0))) begin
        ap_condition_pp0_exit_iter11_state17 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter11_state17 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln34_fu_455_p2 == 1'd1))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln27_fu_374_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_reg_979_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_accumulator_3_phi_fu_308_p4 = grp_fu_874_p3;
    end else begin
        ap_phi_mux_accumulator_3_phi_fu_308_p4 = accumulator_3_reg_305;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln34_reg_979 == 1'd0))) begin
        ap_phi_mux_k_phi_fu_263_p4 = add_ln39_reg_1008;
    end else begin
        ap_phi_mux_k_phi_fu_263_p4 = k_reg_259;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln34_reg_979_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_phi_fu_274_p4 = select_ln34_reg_1021;
    end else begin
        ap_phi_mux_p_phi_fu_274_p4 = p_reg_270;
    end
end

always @ (*) begin
    if ((((first_iter_1_mid2_reg_1017_pp0_iter10_reg == 1'd1) & (first_iter_0_reg_1004_pp0_iter10_reg == 1'd1) & (icmp_ln34_reg_979_pp0_iter10_reg == 1'd0) & (first_iter_2_reg_965 == 1'd1) & (first_iter_3_reg_940 == 1'd0)) | ((first_iter_1_mid2_reg_1017_pp0_iter10_reg == 1'd1) & (first_iter_0_reg_1004_pp0_iter10_reg == 1'd1) & (icmp_ln34_reg_979_pp0_iter10_reg == 1'd0) & (first_iter_2_reg_965 == 1'd0)) | ((first_iter_1_mid2_reg_1017_pp0_iter10_reg == 1'd0) & (first_iter_0_reg_1004_pp0_iter10_reg == 1'd1) & (icmp_ln34_reg_979_pp0_iter10_reg == 1'd0)) | ((first_iter_0_reg_1004_pp0_iter10_reg == 1'd0) & (icmp_ln34_reg_979_pp0_iter10_reg == 1'd0)))) begin
        ap_phi_mux_sext_ln50_31_phi_fu_339_p10 = accumulator_3_mid2_fu_743_p3;
    end else begin
        ap_phi_mux_sext_ln50_31_phi_fu_339_p10 = ap_phi_reg_pp0_iter11_sext_ln50_31_reg_336;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_reg_979_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_sext_ln50_38_phi_fu_297_p4 = sext_ln50_39_reg_315;
    end else begin
        ap_phi_mux_sext_ln50_38_phi_fu_297_p4 = sext_ln50_38_reg_293;
    end
end

always @ (*) begin
    if (((icmp_ln27_fu_374_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_chw_ce0_local = 1'b1;
    end else begin
        input_chw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stage1_ce1_local = 1'b1;
    end else begin
        stage1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_2_reg_1028_pp0_iter11_reg == 1'd1) & (icmp_ln39_2_reg_1013_pp0_iter11_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stage1_we1_local = 1'b1;
    end else begin
        stage1_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln27_fu_374_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln29_fu_399_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_429_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CONV1_BIAS_address0 = zext_ln27_fu_386_p1;

assign CONV1_WEIGHT_address0 = zext_ln50_fu_723_p1;

assign accumulator_3_mid2_fu_743_p3 = ((icmp_ln39_reg_988_pp0_iter10_reg[0:0] == 1'b1) ? ap_phi_mux_sext_ln50_38_phi_fu_297_p4 : ap_phi_mux_accumulator_3_phi_fu_308_p4);

assign add_ln1076_fu_784_p2 = (zext_ln1075_fu_780_p1 + 33'd256);

assign add_ln27_1_fu_368_p2 = (phi_mul_fu_134 + 9'd27);

assign add_ln27_fu_380_p2 = (oc_fu_138 + 5'd1);

assign add_ln29_fu_405_p2 = (oy_reg_214 + 5'd1);

assign add_ln31_fu_435_p2 = (ox_reg_237 + 5'd1);

assign add_ln34_2_fu_511_p2 = (ap_phi_mux_p_phi_fu_274_p4 + 3'd1);

assign add_ln34_fu_461_p2 = (indvar_flatten_reg_248 + 7'd1);

assign add_ln39_fu_499_p2 = (k_mid2_fu_473_p3 + 5'd1);

assign add_ln44_fu_606_p2 = ($signed(trunc_ln42_2_fu_581_p4) + $signed(2'd3));

assign add_ln45_fu_633_p2 = ($signed(trunc_ln43_fu_591_p1) + $signed(2'd3));

assign add_ln48_2_fu_707_p2 = ($signed(shl_ln48_2_fu_699_p3) + $signed(sext_ln45_2_fu_649_p1));

assign add_ln48_fu_693_p2 = (iy_fu_616_p2 + shl_ln3_fu_685_p3);

assign add_ln50_fu_718_p2 = (zext_ln39_fu_559_p1 + phi_mul_load_reg_898);

assign add_ln57_fu_859_p2 = (zext_ln31_reg_969 + shl_ln_fu_764_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_412 = ((first_iter_1_mid2_fu_529_p3 == 1'd1) & (first_iter_0_reg_1004_pp0_iter6_reg == 1'd1) & (icmp_ln34_reg_979_pp0_iter6_reg == 1'd0) & (first_iter_2_reg_965 == 1'd1) & (first_iter_3_reg_940 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_sext_ln50_31_reg_336 = 'bx;

assign ap_phi_reg_pp0_iter0_sext_ln50_39_reg_315 = 'bx;

assign empty_fu_830_p2 = (icmp_ln1078_fu_800_p2 | icmp_ln1074_fu_772_p2);

assign first_iter_0_fu_481_p2 = ((k_mid2_fu_473_p3 == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_120_fu_523_p2 = ((ap_phi_mux_p_phi_fu_274_p4 == 3'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid1_fu_517_p2 = ((add_ln34_2_fu_511_p2 == 3'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid2_fu_529_p3 = ((icmp_ln39_reg_988_pp0_iter6_reg[0:0] == 1'b1) ? first_iter_1_mid1_fu_517_p2 : first_iter_120_fu_523_p2);

assign first_iter_2_fu_441_p2 = ((ox_reg_237 == 5'd0) ? 1'b1 : 1'b0);

assign first_iter_3_fu_411_p2 = ((oy_reg_214 == 5'd0) ? 1'b1 : 1'b0);

assign grp_fu_493_p1 = 5'd3;

assign icmp_ln1074_fu_772_p2 = (($signed(grp_fu_874_p3) < $signed(20'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1078_fu_800_p2 = ((tmp_5_fu_790_p4 != 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_374_p2 = ((oc_fu_138 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_399_p2 = ((oy_reg_214 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_429_p2 = ((ox_reg_237 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln34_2_fu_543_p2 = ((select_ln34_fu_536_p3 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_455_p2 = ((indvar_flatten_reg_248 == 7'd108) ? 1'b1 : 1'b0);

assign icmp_ln39_2_fu_505_p2 = ((add_ln39_fu_499_p2 == 5'd27) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_467_p2 = ((ap_phi_mux_k_phi_fu_263_p4 == 5'd27) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_669_p2 = ((tmp_4_fu_659_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_844_p2 = ((value_fu_836_p3 > select_ln34_2_fu_757_p3) ? 1'b1 : 1'b0);

assign input_chw_address0 = zext_ln48_fu_713_p1;

assign input_chw_ce0 = input_chw_ce0_local;

assign ix_fu_643_p2 = ($signed(sext_ln45_fu_639_p1) + $signed(zext_ln45_fu_629_p1));

assign iy_fu_616_p2 = ($signed(sext_ln44_fu_612_p1) + $signed(zext_ln44_fu_602_p1));

assign k_mid2_fu_473_p3 = ((icmp_ln39_fu_467_p2[0:0] == 1'b1) ? 5'd0 : ap_phi_mux_k_phi_fu_263_p4);

assign maximum_5_fu_850_p3 = ((icmp_ln55_fu_844_p2[0:0] == 1'b1) ? value_fu_836_p3 : select_ln34_2_fu_757_p3);

assign mul_ln41_fu_565_p0 = mul_ln41_fu_565_p00;

assign mul_ln41_fu_565_p00 = k_mid2_reg_996_pp0_iter7_reg;

assign mul_ln41_fu_565_p1 = 11'd57;

assign mul_ln42_fu_575_p0 = mul_ln42_fu_575_p00;

assign mul_ln42_fu_575_p00 = grp_fu_487_p2;

assign mul_ln42_fu_575_p1 = 9'd22;

assign not_icmp_ln1074_fu_816_p2 = (icmp_ln1074_fu_772_p2 ^ 1'd1);

assign or_ln47_fu_653_p2 = (iy_fu_616_p2 | ix_fu_643_p2);

assign pixel_2_fu_728_p3 = ((icmp_ln47_reg_1032[0:0] == 1'b1) ? input_chw_q0 : 8'd0);

assign select_ln1078_cast_fu_822_p3 = ((not_icmp_ln1074_fu_816_p2[0:0] == 1'b1) ? 7'd127 : 7'd0);

assign select_ln34_2_fu_757_p3 = ((icmp_ln39_reg_988_pp0_iter11_reg[0:0] == 1'b1) ? maximum_4_fu_142 : maximum_reg_281);

assign select_ln34_fu_536_p3 = ((icmp_ln39_reg_988_pp0_iter6_reg[0:0] == 1'b1) ? add_ln34_2_fu_511_p2 : ap_phi_mux_p_phi_fu_274_p4);

assign sext_ln1075_fu_777_p1 = grp_fu_874_p3;

assign sext_ln44_fu_612_p1 = $signed(add_ln44_fu_606_p2);

assign sext_ln45_2_fu_649_p1 = ix_fu_643_p2;

assign sext_ln45_fu_639_p1 = $signed(add_ln45_fu_633_p2);

assign sext_ln50_3_fu_395_p1 = $signed(CONV1_BIAS_q0);

assign shl_ln3_fu_685_p3 = {{tmp_2_fu_675_p4}, {5'd0}};

assign shl_ln48_2_fu_699_p3 = {{add_ln48_fu_693_p2}, {5'd0}};

assign shl_ln_fu_764_p4 = {{{trunc_ln57_reg_921}, {trunc_ln57_2_reg_944}}, {4'd0}};

assign stage1_address1 = zext_ln57_fu_864_p1;

assign stage1_ce1 = stage1_ce1_local;

assign stage1_d1 = maximum_5_fu_850_p3;

assign stage1_we1 = stage1_we1_local;

assign tmp1_fu_595_p3 = {{trunc_ln57_2_reg_944}, {tmp_fu_552_p3}};

assign tmp4_fu_622_p3 = {{trunc_ln37_reg_974}, {trunc_ln34_fu_549_p1}};

assign tmp_2_fu_675_p4 = {{mul_ln41_fu_565_p2[10:9]}};

assign tmp_4_fu_659_p4 = {{or_ln47_fu_653_p2[6:5]}};

assign tmp_5_fu_790_p4 = {{add_ln1076_fu_784_p2[32:16]}};

assign tmp_fu_552_p3 = select_ln34_reg_1021[32'd1];

assign trunc_ln34_fu_549_p1 = select_ln34_reg_1021[0:0];

assign trunc_ln37_fu_451_p1 = ox_reg_237[3:0];

assign trunc_ln42_2_fu_581_p4 = {{mul_ln42_fu_575_p2[7:6]}};

assign trunc_ln43_fu_591_p1 = grp_fu_493_p2[1:0];

assign trunc_ln57_2_fu_417_p1 = oy_reg_214[3:0];

assign trunc_ln57_fu_391_p1 = oc_fu_138[3:0];

assign trunc_ln9_fu_806_p4 = {{add_ln1076_fu_784_p2[15:9]}};

assign value_fu_836_p3 = ((empty_fu_830_p2[0:0] == 1'b1) ? select_ln1078_cast_fu_822_p3 : trunc_ln9_fu_806_p4);

assign zext_ln1075_fu_780_p1 = $unsigned(sext_ln1075_fu_777_p1);

assign zext_ln27_fu_386_p1 = oc_fu_138;

assign zext_ln31_fu_447_p1 = ox_reg_237;

assign zext_ln39_fu_559_p1 = k_mid2_reg_996_pp0_iter7_reg;

assign zext_ln44_fu_602_p1 = tmp1_fu_595_p3;

assign zext_ln45_fu_629_p1 = tmp4_fu_622_p3;

assign zext_ln48_fu_713_p1 = add_ln48_2_fu_707_p2;

assign zext_ln50_fu_723_p1 = add_ln50_fu_718_p2;

assign zext_ln57_fu_864_p1 = add_ln57_fu_859_p2;

always @ (posedge ap_clk) begin
    zext_ln31_reg_969[11:5] <= 7'b0000000;
end

endmodule //cifar10_cnn_conv_relu_pool_3_16_32_9_s
