-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cifar10_cnn_cifar10_cnn_Pipeline_VITIS_LOOP_83_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_in_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_in_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_in_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_in_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_in_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_in_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_in_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_in_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_in_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_in_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    image_r : IN STD_LOGIC_VECTOR (63 downto 0);
    input_chw_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_chw_ce1 : OUT STD_LOGIC;
    input_chw_we1 : OUT STD_LOGIC;
    input_chw_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of cifar10_cnn_cifar10_cnn_Pipeline_VITIS_LOOP_83_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv12_C00 : STD_LOGIC_VECTOR (11 downto 0) := "110000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_const_lv25_1556 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001010101010110";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv12_A : STD_LOGIC_VECTOR (11 downto 0) := "000000001010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln83_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal INPUT_LUT_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal INPUT_LUT_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem_in_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal gmem_in_addr_read_reg_278 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln87_fu_171_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal zext_ln87_1_fu_233_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal channel_fu_76 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal select_ln84_fu_193_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_mul_fu_80 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    signal add_ln85_fu_201_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal index_fu_84 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln83_fu_154_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_index_1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal INPUT_LUT_ce0_local : STD_LOGIC;
    signal input_chw_we1_local : STD_LOGIC;
    signal input_chw_ce1_local : STD_LOGIC;
    signal icmp_ln84_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln84_fu_181_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_207_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln87_fu_221_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal pixel_fu_217_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln87_fu_227_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cifar10_cnn_cifar10_cnn_Pipeline_VITIS_LOOP_83_1_INPUT_LUT_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component cifar10_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    INPUT_LUT_U : component cifar10_cnn_cifar10_cnn_Pipeline_VITIS_LOOP_83_1_INPUT_LUT_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => INPUT_LUT_address0,
        ce0 => INPUT_LUT_ce0_local,
        q0 => INPUT_LUT_q0);

    flow_control_loop_pipe_sequential_init_U : component cifar10_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    channel_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    channel_fu_76 <= ap_const_lv12_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    channel_fu_76 <= select_ln84_fu_193_p3;
                end if;
            end if; 
        end if;
    end process;

    index_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln83_fu_148_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    index_fu_84 <= add_ln83_fu_154_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    index_fu_84 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    phi_mul_fu_80 <= ap_const_lv25_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    phi_mul_fu_80 <= add_ln85_fu_201_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                gmem_in_addr_read_reg_278 <= m_axi_gmem_in_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    INPUT_LUT_address0 <= zext_ln87_fu_171_p1(8 - 1 downto 0);

    INPUT_LUT_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            INPUT_LUT_ce0_local <= ap_const_logic_1;
        else 
            INPUT_LUT_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln83_fu_154_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_index_1) + unsigned(ap_const_lv12_1));
    add_ln84_fu_181_p2 <= std_logic_vector(unsigned(channel_fu_76) + unsigned(ap_const_lv12_1));
    add_ln85_fu_201_p2 <= std_logic_vector(unsigned(phi_mul_fu_80) + unsigned(ap_const_lv25_1556));
    add_ln87_fu_227_p2 <= std_logic_vector(unsigned(shl_ln87_fu_221_p2) + unsigned(pixel_fu_217_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_in_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem_in_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_in_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem_in_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_in_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem_in_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln83_fu_148_p2)
    begin
        if (((icmp_ln83_fu_148_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_index_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, index_fu_84, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_index_1 <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_index_1 <= index_fu_84;
        end if; 
    end process;


    gmem_in_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_in_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_in_blk_n_R <= m_axi_gmem_in_0_RVALID;
        else 
            gmem_in_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln83_fu_148_p2 <= "1" when (ap_sig_allocacmp_index_1 = ap_const_lv12_C00) else "0";
    icmp_ln84_fu_187_p2 <= "1" when (channel_fu_76 = ap_const_lv12_2) else "0";
    input_chw_address1 <= zext_ln87_1_fu_233_p1(12 - 1 downto 0);
    input_chw_ce1 <= input_chw_ce1_local;

    input_chw_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            input_chw_ce1_local <= ap_const_logic_1;
        else 
            input_chw_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    input_chw_d1 <= INPUT_LUT_q0;
    input_chw_we1 <= input_chw_we1_local;

    input_chw_we1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            input_chw_we1_local <= ap_const_logic_1;
        else 
            input_chw_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_in_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_in_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_in_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_in_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_in_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_in_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_in_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_in_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_in_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_in_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_in_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_in_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_in_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_in_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_in_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_in_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_in_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_in_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem_in_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_in_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_in_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem_in_0_WID <= ap_const_lv1_0;
    m_axi_gmem_in_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_in_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem_in_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_WVALID <= ap_const_logic_0;
    pixel_fu_217_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_207_p4),12));
    select_ln84_fu_193_p3 <= 
        ap_const_lv12_0 when (icmp_ln84_fu_187_p2(0) = '1') else 
        add_ln84_fu_181_p2;
    shl_ln87_fu_221_p2 <= std_logic_vector(shift_left(unsigned(channel_fu_76),to_integer(unsigned('0' & ap_const_lv12_A(12-1 downto 0)))));
    tmp_fu_207_p4 <= phi_mul_fu_80(24 downto 14);
    zext_ln87_1_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln87_fu_227_p2),64));
    zext_ln87_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gmem_in_addr_read_reg_278),64));
end behav;
