-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cifar10_cnn_conv_relu_pool_16_32_16_8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stage1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    stage1_ce0 : OUT STD_LOGIC;
    stage1_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    stage2_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    stage2_ce1 : OUT STD_LOGIC;
    stage2_we1 : OUT STD_LOGIC;
    stage2_d1 : OUT STD_LOGIC_VECTOR (6 downto 0) );
end;


architecture behav of cifar10_cnn_conv_relu_pool_16_32_16_8_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv10_240 : STD_LOGIC_VECTOR (9 downto 0) := "1001000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_90 : STD_LOGIC_VECTOR (7 downto 0) := "10010000";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv17_1C8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000111001000";
    constant ap_const_lv9_16 : STD_LOGIC_VECTOR (8 downto 0) := "000010110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv23_1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";
    constant ap_const_lv33_80 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000010000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal CONV2_BIAS_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal CONV2_BIAS_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal CONV2_WEIGHT_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal CONV2_WEIGHT_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_reg_256 : STD_LOGIC_VECTOR (9 downto 0);
    signal k_reg_267 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_reg_278 : STD_LOGIC_VECTOR (2 downto 0);
    signal maximum_reg_289 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln50_48_reg_301 : STD_LOGIC_VECTOR (22 downto 0);
    signal accumulator_5_reg_313 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln27_fu_374_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln27_reg_914 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln50_4_fu_385_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln50_4_reg_924 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln57_2_fu_407_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln57_2_reg_930 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln57_fu_413_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln57_reg_935 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln29_fu_422_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln29_reg_943 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal first_iter_3_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_3_reg_948 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln57_3_fu_434_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln57_3_reg_952 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln31_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln31_fu_448_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln31_reg_962 : STD_LOGIC_VECTOR (3 downto 0);
    signal first_iter_2_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_reg_973 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln31_fu_460_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln31_reg_977 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln37_fu_464_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln37_reg_982 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln34_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln34_reg_987_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_987_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln34_fu_474_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln39_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_996_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal k_mid2_fu_486_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal k_mid2_reg_1004_pp0_iter10_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal first_iter_0_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1012_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln39_fu_512_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln39_reg_1016 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln39_3_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_3_reg_1021_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_fu_542_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1025 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1025_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1025_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1025_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_fu_549_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln34_reg_1029 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal icmp_ln34_3_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_3_reg_1036 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_3_reg_1036_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_3_reg_1036_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_3_reg_1036_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_3_reg_1036_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_1040 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_3_fu_774_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal grp_fu_891_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter14_state20 : STD_LOGIC;
    signal sext_ln50_45_reg_210 : STD_LOGIC_VECTOR (22 downto 0);
    signal oy_reg_222 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln50_46_reg_233 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln29_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal ox_reg_245 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_k_phi_fu_271_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_p_phi_fu_282_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_sext_ln50_48_phi_fu_305_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_mux_accumulator_5_phi_fu_316_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter14_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_predicate_pred393_state20 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter1_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter2_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter3_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter4_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter5_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter6_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter7_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter8_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter9_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter10_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter12_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter13_sext_ln50_49_reg_323 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_mux_sext_ln50_41_phi_fu_347_p10 : STD_LOGIC_VECTOR (22 downto 0);
    signal accumulator_5_mid2_fu_760_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter14_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter0_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter1_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter2_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter3_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter4_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter5_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter6_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter7_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter8_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter9_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter10_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter12_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter13_sext_ln50_41_reg_344 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln27_fu_380_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln27_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln48_fu_730_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln50_2_fu_740_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_2_fu_881_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal oc_fu_146 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal maximum_6_fu_150 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal maximum_7_fu_867_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal CONV2_BIAS_ce0_local : STD_LOGIC;
    signal stage1_ce0_local : STD_LOGIC;
    signal CONV2_WEIGHT_ce0_local : STD_LOGIC;
    signal stage2_we1_local : STD_LOGIC;
    signal stage2_ce1_local : STD_LOGIC;
    signal tmp_fu_396_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl_fu_389_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln57_fu_403_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_500_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_506_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln34_3_fu_524_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal first_iter_1_mid1_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_120_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln41_fu_578_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln41_fu_578_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_500_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln42_fu_588_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln42_fu_588_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_fu_588_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_506_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_565_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_608_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln42_3_fu_594_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln44_fu_619_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln44_fu_625_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln44_fu_615_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln34_fu_562_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_635_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln43_fu_604_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln45_fu_646_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln45_fu_652_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln45_fu_642_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ix_fu_656_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal iy_fu_629_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln47_fu_666_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_7_fu_672_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln41_fu_578_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_688_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln48_fu_706_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln4_fu_698_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln48_fu_710_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln48_3_fu_716_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln45_3_fu_662_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln48_3_fu_724_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln39_fu_572_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln50_fu_735_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal pixel_3_fu_745_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln1075_fu_794_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1075_fu_797_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1076_fu_801_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_8_fu_807_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln1074_fu_789_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_icmp_ln1074_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1078_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1078_cast_fu_839_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln_fu_823_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal value_fu_853_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln55_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_781_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln57_fu_876_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_891_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_891_p10 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln41_fu_578_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln42_fu_588_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_condition_445 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component cifar10_cnn_urem_8ns_5ns_8_12_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component cifar10_cnn_urem_8ns_3ns_2_12_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component cifar10_cnn_mul_8ns_10ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component cifar10_cnn_mul_5ns_6ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component cifar10_cnn_mac_muladd_8s_7ns_23s_23_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (22 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component cifar10_cnn_conv_relu_pool_16_32_16_8_s_CONV2_BIAS_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component cifar10_cnn_conv_relu_pool_16_32_16_8_s_CONV2_WEIGHT_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    CONV2_BIAS_U : component cifar10_cnn_conv_relu_pool_16_32_16_8_s_CONV2_BIAS_ROM_AUTO_1R
    generic map (
        DataWidth => 11,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => CONV2_BIAS_address0,
        ce0 => CONV2_BIAS_ce0_local,
        q0 => CONV2_BIAS_q0);

    CONV2_WEIGHT_U : component cifar10_cnn_conv_relu_pool_16_32_16_8_s_CONV2_WEIGHT_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 4608,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => CONV2_WEIGHT_address0,
        ce0 => CONV2_WEIGHT_ce0_local,
        q0 => CONV2_WEIGHT_q0);

    urem_8ns_5ns_8_12_1_U19 : component cifar10_cnn_urem_8ns_5ns_8_12_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => k_mid2_fu_486_p3,
        din1 => grp_fu_500_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_500_p2);

    urem_8ns_3ns_2_12_1_U20 : component cifar10_cnn_urem_8ns_3ns_2_12_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 8,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => k_mid2_fu_486_p3,
        din1 => grp_fu_506_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_506_p2);

    mul_8ns_10ns_17_1_1_U21 : component cifar10_cnn_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln41_fu_578_p0,
        din1 => mul_ln41_fu_578_p1,
        dout => mul_ln41_fu_578_p2);

    mul_5ns_6ns_9_1_1_U22 : component cifar10_cnn_mul_5ns_6ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 6,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln42_fu_588_p0,
        din1 => mul_ln42_fu_588_p1,
        dout => mul_ln42_fu_588_p2);

    mac_muladd_8s_7ns_23s_23_4_1_U23 : component cifar10_cnn_mac_muladd_8s_7ns_23s_23_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 23,
        dout_WIDTH => 23)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => CONV2_WEIGHT_q0,
        din1 => grp_fu_891_p1,
        din2 => ap_phi_mux_sext_ln50_41_phi_fu_347_p10,
        ce => ap_const_logic_1,
        dout => grp_fu_891_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                elsif ((((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter14_state20) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0)))) then 
                    ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter14_state20) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter13;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    accumulator_5_reg_313_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln34_reg_987_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                accumulator_5_reg_313 <= grp_fu_891_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0))) then 
                accumulator_5_reg_313 <= sext_ln50_46_reg_233;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_445)) then 
                    ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344 <= sext_ln50_4_reg_924;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter10_sext_ln50_41_reg_344;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_445)) then 
                    ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323 <= sext_ln50_4_reg_924;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter10_sext_ln50_49_reg_323;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln34_fu_468_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_256 <= add_ln34_fu_474_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_256 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    k_reg_267_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln34_reg_987 = ap_const_lv1_0))) then 
                k_reg_267 <= add_ln39_reg_1016;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0))) then 
                k_reg_267 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    maximum_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln34_reg_987_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                maximum_reg_289 <= select_ln34_3_fu_774_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0))) then 
                maximum_reg_289 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    oc_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                oc_fu_146 <= ap_const_lv6_0;
            elsif (((icmp_ln29_fu_416_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                oc_fu_146 <= add_ln27_reg_914;
            end if; 
        end if;
    end process;

    ox_reg_245_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                ox_reg_245 <= add_ln31_reg_962;
            elsif (((icmp_ln29_fu_416_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                ox_reg_245 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    oy_reg_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_1))) then 
                oy_reg_222 <= add_ln29_reg_943;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                oy_reg_222 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    p_reg_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (icmp_ln34_reg_987_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                p_reg_278 <= select_ln34_reg_1029;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0))) then 
                p_reg_278 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    sext_ln50_46_reg_233_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                sext_ln50_46_reg_233 <= sext_ln50_48_reg_301;
            elsif (((icmp_ln29_fu_416_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                sext_ln50_46_reg_233 <= sext_ln50_45_reg_210;
            end if; 
        end if;
    end process;

    sext_ln50_48_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln34_reg_987_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sext_ln50_48_reg_301 <= sext_ln50_49_reg_323;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_0))) then 
                sext_ln50_48_reg_301 <= sext_ln50_46_reg_233;
            end if; 
        end if;
    end process;

    sext_ln50_49_reg_323_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_predicate_pred393_state20 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (first_iter_1_mid2_reg_1025_pp0_iter13_reg = ap_const_lv1_1) and (first_iter_0_reg_1012_pp0_iter13_reg = ap_const_lv1_1) and (icmp_ln34_reg_987_pp0_iter13_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (first_iter_2_reg_973 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (first_iter_1_mid2_reg_1025_pp0_iter13_reg = ap_const_lv1_0) and (first_iter_0_reg_1012_pp0_iter13_reg = ap_const_lv1_1) and (icmp_ln34_reg_987_pp0_iter13_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (first_iter_0_reg_1012_pp0_iter13_reg = ap_const_lv1_0) and (icmp_ln34_reg_987_pp0_iter13_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                sext_ln50_49_reg_323 <= ap_phi_mux_sext_ln50_48_phi_fu_305_p4;
            elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter14_sext_ln50_49_reg_323;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln27_reg_914 <= add_ln27_fu_374_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln29_reg_943 <= add_ln29_fu_422_p2;
                first_iter_3_reg_948 <= first_iter_3_fu_428_p2;
                trunc_ln57_3_reg_952 <= trunc_ln57_3_fu_434_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln31_reg_962 <= add_ln31_fu_448_p2;
                first_iter_2_reg_973 <= first_iter_2_fu_454_p2;
                trunc_ln37_reg_982 <= trunc_ln37_fu_464_p1;
                    zext_ln31_reg_977(3 downto 0) <= zext_ln31_fu_460_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln39_reg_1016 <= add_ln39_fu_512_p2;
                ap_phi_reg_pp0_iter1_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter0_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter1_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter0_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    add_ln57_2_reg_930(12 downto 4) <= add_ln57_2_fu_407_p2(12 downto 4);
                sext_ln50_4_reg_924 <= sext_ln50_4_fu_385_p1;
                trunc_ln57_reg_935 <= trunc_ln57_fu_413_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter10_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter9_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter10_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter9_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter12_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter12_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter13_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter12_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter13_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter12_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter14_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter13_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter14_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter13_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter2_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter1_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter2_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter1_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter3_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter2_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter3_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter2_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter4_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter3_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter4_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter3_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter5_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter4_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter5_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter4_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter6_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter5_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter6_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter5_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter7_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter6_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter7_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter6_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter8_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter7_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter8_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter7_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter9_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter8_sext_ln50_41_reg_344;
                ap_phi_reg_pp0_iter9_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter8_sext_ln50_49_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    ap_predicate_pred393_state20 <= ((first_iter_3_reg_948 = ap_const_lv1_0) and (first_iter_1_mid2_reg_1025_pp0_iter12_reg = ap_const_lv1_1) and (first_iter_0_reg_1012_pp0_iter12_reg = ap_const_lv1_1) and (icmp_ln34_reg_987_pp0_iter12_reg = ap_const_lv1_0) and (first_iter_2_reg_973 = ap_const_lv1_1));
                first_iter_0_reg_1012_pp0_iter10_reg <= first_iter_0_reg_1012_pp0_iter9_reg;
                first_iter_0_reg_1012_pp0_iter11_reg <= first_iter_0_reg_1012_pp0_iter10_reg;
                first_iter_0_reg_1012_pp0_iter12_reg <= first_iter_0_reg_1012_pp0_iter11_reg;
                first_iter_0_reg_1012_pp0_iter13_reg <= first_iter_0_reg_1012_pp0_iter12_reg;
                first_iter_0_reg_1012_pp0_iter2_reg <= first_iter_0_reg_1012_pp0_iter1_reg;
                first_iter_0_reg_1012_pp0_iter3_reg <= first_iter_0_reg_1012_pp0_iter2_reg;
                first_iter_0_reg_1012_pp0_iter4_reg <= first_iter_0_reg_1012_pp0_iter3_reg;
                first_iter_0_reg_1012_pp0_iter5_reg <= first_iter_0_reg_1012_pp0_iter4_reg;
                first_iter_0_reg_1012_pp0_iter6_reg <= first_iter_0_reg_1012_pp0_iter5_reg;
                first_iter_0_reg_1012_pp0_iter7_reg <= first_iter_0_reg_1012_pp0_iter6_reg;
                first_iter_0_reg_1012_pp0_iter8_reg <= first_iter_0_reg_1012_pp0_iter7_reg;
                first_iter_0_reg_1012_pp0_iter9_reg <= first_iter_0_reg_1012_pp0_iter8_reg;
                first_iter_1_mid2_reg_1025 <= first_iter_1_mid2_fu_542_p3;
                first_iter_1_mid2_reg_1025_pp0_iter11_reg <= first_iter_1_mid2_reg_1025;
                first_iter_1_mid2_reg_1025_pp0_iter12_reg <= first_iter_1_mid2_reg_1025_pp0_iter11_reg;
                first_iter_1_mid2_reg_1025_pp0_iter13_reg <= first_iter_1_mid2_reg_1025_pp0_iter12_reg;
                icmp_ln34_3_reg_1036 <= icmp_ln34_3_fu_556_p2;
                icmp_ln34_3_reg_1036_pp0_iter11_reg <= icmp_ln34_3_reg_1036;
                icmp_ln34_3_reg_1036_pp0_iter12_reg <= icmp_ln34_3_reg_1036_pp0_iter11_reg;
                icmp_ln34_3_reg_1036_pp0_iter13_reg <= icmp_ln34_3_reg_1036_pp0_iter12_reg;
                icmp_ln34_3_reg_1036_pp0_iter14_reg <= icmp_ln34_3_reg_1036_pp0_iter13_reg;
                icmp_ln34_reg_987_pp0_iter10_reg <= icmp_ln34_reg_987_pp0_iter9_reg;
                icmp_ln34_reg_987_pp0_iter11_reg <= icmp_ln34_reg_987_pp0_iter10_reg;
                icmp_ln34_reg_987_pp0_iter12_reg <= icmp_ln34_reg_987_pp0_iter11_reg;
                icmp_ln34_reg_987_pp0_iter13_reg <= icmp_ln34_reg_987_pp0_iter12_reg;
                icmp_ln34_reg_987_pp0_iter14_reg <= icmp_ln34_reg_987_pp0_iter13_reg;
                icmp_ln34_reg_987_pp0_iter2_reg <= icmp_ln34_reg_987_pp0_iter1_reg;
                icmp_ln34_reg_987_pp0_iter3_reg <= icmp_ln34_reg_987_pp0_iter2_reg;
                icmp_ln34_reg_987_pp0_iter4_reg <= icmp_ln34_reg_987_pp0_iter3_reg;
                icmp_ln34_reg_987_pp0_iter5_reg <= icmp_ln34_reg_987_pp0_iter4_reg;
                icmp_ln34_reg_987_pp0_iter6_reg <= icmp_ln34_reg_987_pp0_iter5_reg;
                icmp_ln34_reg_987_pp0_iter7_reg <= icmp_ln34_reg_987_pp0_iter6_reg;
                icmp_ln34_reg_987_pp0_iter8_reg <= icmp_ln34_reg_987_pp0_iter7_reg;
                icmp_ln34_reg_987_pp0_iter9_reg <= icmp_ln34_reg_987_pp0_iter8_reg;
                icmp_ln39_3_reg_1021_pp0_iter10_reg <= icmp_ln39_3_reg_1021_pp0_iter9_reg;
                icmp_ln39_3_reg_1021_pp0_iter11_reg <= icmp_ln39_3_reg_1021_pp0_iter10_reg;
                icmp_ln39_3_reg_1021_pp0_iter12_reg <= icmp_ln39_3_reg_1021_pp0_iter11_reg;
                icmp_ln39_3_reg_1021_pp0_iter13_reg <= icmp_ln39_3_reg_1021_pp0_iter12_reg;
                icmp_ln39_3_reg_1021_pp0_iter14_reg <= icmp_ln39_3_reg_1021_pp0_iter13_reg;
                icmp_ln39_3_reg_1021_pp0_iter2_reg <= icmp_ln39_3_reg_1021_pp0_iter1_reg;
                icmp_ln39_3_reg_1021_pp0_iter3_reg <= icmp_ln39_3_reg_1021_pp0_iter2_reg;
                icmp_ln39_3_reg_1021_pp0_iter4_reg <= icmp_ln39_3_reg_1021_pp0_iter3_reg;
                icmp_ln39_3_reg_1021_pp0_iter5_reg <= icmp_ln39_3_reg_1021_pp0_iter4_reg;
                icmp_ln39_3_reg_1021_pp0_iter6_reg <= icmp_ln39_3_reg_1021_pp0_iter5_reg;
                icmp_ln39_3_reg_1021_pp0_iter7_reg <= icmp_ln39_3_reg_1021_pp0_iter6_reg;
                icmp_ln39_3_reg_1021_pp0_iter8_reg <= icmp_ln39_3_reg_1021_pp0_iter7_reg;
                icmp_ln39_3_reg_1021_pp0_iter9_reg <= icmp_ln39_3_reg_1021_pp0_iter8_reg;
                icmp_ln39_reg_996_pp0_iter10_reg <= icmp_ln39_reg_996_pp0_iter9_reg;
                icmp_ln39_reg_996_pp0_iter11_reg <= icmp_ln39_reg_996_pp0_iter10_reg;
                icmp_ln39_reg_996_pp0_iter12_reg <= icmp_ln39_reg_996_pp0_iter11_reg;
                icmp_ln39_reg_996_pp0_iter13_reg <= icmp_ln39_reg_996_pp0_iter12_reg;
                icmp_ln39_reg_996_pp0_iter14_reg <= icmp_ln39_reg_996_pp0_iter13_reg;
                icmp_ln39_reg_996_pp0_iter2_reg <= icmp_ln39_reg_996_pp0_iter1_reg;
                icmp_ln39_reg_996_pp0_iter3_reg <= icmp_ln39_reg_996_pp0_iter2_reg;
                icmp_ln39_reg_996_pp0_iter4_reg <= icmp_ln39_reg_996_pp0_iter3_reg;
                icmp_ln39_reg_996_pp0_iter5_reg <= icmp_ln39_reg_996_pp0_iter4_reg;
                icmp_ln39_reg_996_pp0_iter6_reg <= icmp_ln39_reg_996_pp0_iter5_reg;
                icmp_ln39_reg_996_pp0_iter7_reg <= icmp_ln39_reg_996_pp0_iter6_reg;
                icmp_ln39_reg_996_pp0_iter8_reg <= icmp_ln39_reg_996_pp0_iter7_reg;
                icmp_ln39_reg_996_pp0_iter9_reg <= icmp_ln39_reg_996_pp0_iter8_reg;
                icmp_ln47_reg_1040 <= icmp_ln47_fu_682_p2;
                k_mid2_reg_1004_pp0_iter10_reg <= k_mid2_reg_1004_pp0_iter9_reg;
                k_mid2_reg_1004_pp0_iter2_reg <= k_mid2_reg_1004_pp0_iter1_reg;
                k_mid2_reg_1004_pp0_iter3_reg <= k_mid2_reg_1004_pp0_iter2_reg;
                k_mid2_reg_1004_pp0_iter4_reg <= k_mid2_reg_1004_pp0_iter3_reg;
                k_mid2_reg_1004_pp0_iter5_reg <= k_mid2_reg_1004_pp0_iter4_reg;
                k_mid2_reg_1004_pp0_iter6_reg <= k_mid2_reg_1004_pp0_iter5_reg;
                k_mid2_reg_1004_pp0_iter7_reg <= k_mid2_reg_1004_pp0_iter6_reg;
                k_mid2_reg_1004_pp0_iter8_reg <= k_mid2_reg_1004_pp0_iter7_reg;
                k_mid2_reg_1004_pp0_iter9_reg <= k_mid2_reg_1004_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                first_iter_0_reg_1012 <= first_iter_0_fu_494_p2;
                first_iter_0_reg_1012_pp0_iter1_reg <= first_iter_0_reg_1012;
                icmp_ln34_reg_987 <= icmp_ln34_fu_468_p2;
                icmp_ln34_reg_987_pp0_iter1_reg <= icmp_ln34_reg_987;
                icmp_ln39_3_reg_1021 <= icmp_ln39_3_fu_518_p2;
                icmp_ln39_3_reg_1021_pp0_iter1_reg <= icmp_ln39_3_reg_1021;
                icmp_ln39_reg_996 <= icmp_ln39_fu_480_p2;
                icmp_ln39_reg_996_pp0_iter1_reg <= icmp_ln39_reg_996;
                k_mid2_reg_1004 <= k_mid2_fu_486_p3;
                k_mid2_reg_1004_pp0_iter1_reg <= k_mid2_reg_1004;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln34_reg_987_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                maximum_6_fu_150 <= maximum_7_fu_867_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln34_reg_1029 <= select_ln34_fu_549_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_1))) then
                sext_ln50_45_reg_210 <= sext_ln50_46_reg_233;
            end if;
        end if;
    end process;
    add_ln57_2_reg_930(3 downto 0) <= "0000";
    zext_ln31_reg_977(10 downto 4) <= "0000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, icmp_ln31_fu_442_p2, ap_CS_fsm_state5, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, icmp_ln29_fu_416_p2, icmp_ln27_fu_368_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln27_fu_368_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln29_fu_416_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_442_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    CONV2_BIAS_address0 <= zext_ln27_fu_380_p1(5 - 1 downto 0);

    CONV2_BIAS_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            CONV2_BIAS_ce0_local <= ap_const_logic_1;
        else 
            CONV2_BIAS_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    CONV2_WEIGHT_address0 <= zext_ln50_2_fu_740_p1(13 - 1 downto 0);

    CONV2_WEIGHT_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            CONV2_WEIGHT_ce0_local <= ap_const_logic_1;
        else 
            CONV2_WEIGHT_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    accumulator_5_mid2_fu_760_p3 <= 
        ap_phi_mux_sext_ln50_48_phi_fu_305_p4 when (icmp_ln39_reg_996_pp0_iter13_reg(0) = '1') else 
        ap_phi_mux_accumulator_5_phi_fu_316_p4;
    add_ln1076_fu_801_p2 <= std_logic_vector(unsigned(zext_ln1075_fu_797_p1) + unsigned(ap_const_lv33_80));
    add_ln27_fu_374_p2 <= std_logic_vector(unsigned(oc_fu_146) + unsigned(ap_const_lv6_1));
    add_ln29_fu_422_p2 <= std_logic_vector(unsigned(oy_reg_222) + unsigned(ap_const_lv4_1));
    add_ln31_fu_448_p2 <= std_logic_vector(unsigned(ox_reg_245) + unsigned(ap_const_lv4_1));
    add_ln34_3_fu_524_p2 <= std_logic_vector(unsigned(ap_phi_mux_p_phi_fu_282_p4) + unsigned(ap_const_lv3_1));
    add_ln34_fu_474_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_256) + unsigned(ap_const_lv10_1));
    add_ln39_fu_512_p2 <= std_logic_vector(unsigned(k_mid2_fu_486_p3) + unsigned(ap_const_lv8_1));
    add_ln44_fu_619_p2 <= std_logic_vector(unsigned(trunc_ln42_3_fu_594_p4) + unsigned(ap_const_lv2_3));
    add_ln45_fu_646_p2 <= std_logic_vector(unsigned(trunc_ln43_fu_604_p1) + unsigned(ap_const_lv2_3));
    add_ln48_3_fu_724_p2 <= std_logic_vector(unsigned(shl_ln48_3_fu_716_p3) + unsigned(sext_ln45_3_fu_662_p1));
    add_ln48_fu_710_p2 <= std_logic_vector(signed(sext_ln48_fu_706_p1) + signed(shl_ln4_fu_698_p3));
    add_ln50_fu_735_p2 <= std_logic_vector(unsigned(zext_ln39_fu_572_p1) + unsigned(add_ln57_2_reg_930));
    add_ln57_2_fu_407_p2 <= std_logic_vector(unsigned(p_shl_fu_389_p3) + unsigned(zext_ln57_fu_403_p1));
    add_ln57_fu_876_p2 <= std_logic_vector(unsigned(zext_ln31_reg_977) + unsigned(shl_ln_fu_781_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(5);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state22 <= ap_CS_fsm(6);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_445_assign_proc : process(first_iter_3_reg_948, first_iter_2_reg_973, icmp_ln34_reg_987_pp0_iter9_reg, first_iter_0_reg_1012_pp0_iter9_reg, first_iter_1_mid2_fu_542_p3)
    begin
                ap_condition_445 <= ((first_iter_3_reg_948 = ap_const_lv1_1) and (first_iter_1_mid2_fu_542_p3 = ap_const_lv1_1) and (first_iter_0_reg_1012_pp0_iter9_reg = ap_const_lv1_1) and (icmp_ln34_reg_987_pp0_iter9_reg = ap_const_lv1_0) and (first_iter_2_reg_973 = ap_const_lv1_1));
    end process;


    ap_condition_pp0_exit_iter14_state20_assign_proc : process(ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter14_state20 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter14_state20 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(icmp_ln34_fu_468_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln34_fu_468_p2 = ap_const_lv1_1))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln27_fu_368_p2)
    begin
        if ((((icmp_ln27_fu_368_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_accumulator_5_phi_fu_316_p4_assign_proc : process(accumulator_5_reg_313, icmp_ln34_reg_987_pp0_iter14_reg, ap_enable_reg_pp0_iter15, grp_fu_891_p3, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln34_reg_987_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_accumulator_5_phi_fu_316_p4 <= grp_fu_891_p3;
        else 
            ap_phi_mux_accumulator_5_phi_fu_316_p4 <= accumulator_5_reg_313;
        end if; 
    end process;


    ap_phi_mux_k_phi_fu_271_p4_assign_proc : process(k_reg_267, icmp_ln34_reg_987, ap_CS_fsm_pp0_stage0, add_ln39_reg_1016, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln34_reg_987 = ap_const_lv1_0))) then 
            ap_phi_mux_k_phi_fu_271_p4 <= add_ln39_reg_1016;
        else 
            ap_phi_mux_k_phi_fu_271_p4 <= k_reg_267;
        end if; 
    end process;


    ap_phi_mux_p_phi_fu_282_p4_assign_proc : process(p_reg_278, icmp_ln34_reg_987_pp0_iter10_reg, select_ln34_reg_1029, ap_enable_reg_pp0_iter11, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (icmp_ln34_reg_987_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_p_phi_fu_282_p4 <= select_ln34_reg_1029;
        else 
            ap_phi_mux_p_phi_fu_282_p4 <= p_reg_278;
        end if; 
    end process;


    ap_phi_mux_sext_ln50_41_phi_fu_347_p10_assign_proc : process(first_iter_3_reg_948, first_iter_2_reg_973, icmp_ln34_reg_987_pp0_iter13_reg, first_iter_0_reg_1012_pp0_iter13_reg, first_iter_1_mid2_reg_1025_pp0_iter13_reg, accumulator_5_mid2_fu_760_p3, ap_phi_reg_pp0_iter14_sext_ln50_41_reg_344)
    begin
        if ((((first_iter_3_reg_948 = ap_const_lv1_0) and (first_iter_1_mid2_reg_1025_pp0_iter13_reg = ap_const_lv1_1) and (first_iter_0_reg_1012_pp0_iter13_reg = ap_const_lv1_1) and (icmp_ln34_reg_987_pp0_iter13_reg = ap_const_lv1_0) and (first_iter_2_reg_973 = ap_const_lv1_1)) or ((first_iter_1_mid2_reg_1025_pp0_iter13_reg = ap_const_lv1_1) and (first_iter_0_reg_1012_pp0_iter13_reg = ap_const_lv1_1) and (icmp_ln34_reg_987_pp0_iter13_reg = ap_const_lv1_0) and (first_iter_2_reg_973 = ap_const_lv1_0)) or ((first_iter_1_mid2_reg_1025_pp0_iter13_reg = ap_const_lv1_0) and (first_iter_0_reg_1012_pp0_iter13_reg = ap_const_lv1_1) and (icmp_ln34_reg_987_pp0_iter13_reg = ap_const_lv1_0)) or ((first_iter_0_reg_1012_pp0_iter13_reg = ap_const_lv1_0) and (icmp_ln34_reg_987_pp0_iter13_reg = ap_const_lv1_0)))) then 
            ap_phi_mux_sext_ln50_41_phi_fu_347_p10 <= accumulator_5_mid2_fu_760_p3;
        else 
            ap_phi_mux_sext_ln50_41_phi_fu_347_p10 <= ap_phi_reg_pp0_iter14_sext_ln50_41_reg_344;
        end if; 
    end process;


    ap_phi_mux_sext_ln50_48_phi_fu_305_p4_assign_proc : process(sext_ln50_48_reg_301, sext_ln50_49_reg_323, icmp_ln34_reg_987_pp0_iter14_reg, ap_enable_reg_pp0_iter15, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln34_reg_987_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_sext_ln50_48_phi_fu_305_p4 <= sext_ln50_49_reg_323;
        else 
            ap_phi_mux_sext_ln50_48_phi_fu_305_p4 <= sext_ln50_48_reg_301;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_sext_ln50_41_reg_344 <= "XXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_sext_ln50_49_reg_323 <= "XXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln27_fu_368_p2)
    begin
        if (((icmp_ln27_fu_368_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_847_p2 <= (icmp_ln1078_fu_817_p2 or icmp_ln1074_fu_789_p2);
    first_iter_0_fu_494_p2 <= "1" when (k_mid2_fu_486_p3 = ap_const_lv8_0) else "0";
    first_iter_120_fu_536_p2 <= "1" when (ap_phi_mux_p_phi_fu_282_p4 = ap_const_lv3_0) else "0";
    first_iter_1_mid1_fu_530_p2 <= "1" when (add_ln34_3_fu_524_p2 = ap_const_lv3_0) else "0";
    first_iter_1_mid2_fu_542_p3 <= 
        first_iter_1_mid1_fu_530_p2 when (icmp_ln39_reg_996_pp0_iter9_reg(0) = '1') else 
        first_iter_120_fu_536_p2;
    first_iter_2_fu_454_p2 <= "1" when (ox_reg_245 = ap_const_lv4_0) else "0";
    first_iter_3_fu_428_p2 <= "1" when (oy_reg_222 = ap_const_lv4_0) else "0";
    grp_fu_500_p1 <= ap_const_lv8_9(5 - 1 downto 0);
    grp_fu_506_p1 <= ap_const_lv8_3(3 - 1 downto 0);
    grp_fu_891_p1 <= grp_fu_891_p10(7 - 1 downto 0);
    grp_fu_891_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pixel_3_fu_745_p3),15));
    icmp_ln1074_fu_789_p2 <= "1" when (signed(grp_fu_891_p3) < signed(ap_const_lv23_1)) else "0";
    icmp_ln1078_fu_817_p2 <= "0" when (tmp_8_fu_807_p4 = ap_const_lv18_0) else "1";
    icmp_ln27_fu_368_p2 <= "1" when (oc_fu_146 = ap_const_lv6_20) else "0";
    icmp_ln29_fu_416_p2 <= "1" when (oy_reg_222 = ap_const_lv4_8) else "0";
    icmp_ln31_fu_442_p2 <= "1" when (ox_reg_245 = ap_const_lv4_8) else "0";
    icmp_ln34_3_fu_556_p2 <= "1" when (select_ln34_fu_549_p3 = ap_const_lv3_3) else "0";
    icmp_ln34_fu_468_p2 <= "1" when (indvar_flatten_reg_256 = ap_const_lv10_240) else "0";
    icmp_ln39_3_fu_518_p2 <= "1" when (add_ln39_fu_512_p2 = ap_const_lv8_90) else "0";
    icmp_ln39_fu_480_p2 <= "1" when (ap_phi_mux_k_phi_fu_271_p4 = ap_const_lv8_90) else "0";
    icmp_ln47_fu_682_p2 <= "1" when (tmp_7_fu_672_p4 = ap_const_lv2_0) else "0";
    icmp_ln55_fu_861_p2 <= "1" when (unsigned(value_fu_853_p3) > unsigned(select_ln34_3_fu_774_p3)) else "0";
    ix_fu_656_p2 <= std_logic_vector(signed(sext_ln45_fu_652_p1) + signed(zext_ln45_fu_642_p1));
    iy_fu_629_p2 <= std_logic_vector(signed(sext_ln44_fu_625_p1) + signed(zext_ln44_fu_615_p1));
    k_mid2_fu_486_p3 <= 
        ap_const_lv8_0 when (icmp_ln39_fu_480_p2(0) = '1') else 
        ap_phi_mux_k_phi_fu_271_p4;
    maximum_7_fu_867_p3 <= 
        value_fu_853_p3 when (icmp_ln55_fu_861_p2(0) = '1') else 
        select_ln34_3_fu_774_p3;
    mul_ln41_fu_578_p0 <= mul_ln41_fu_578_p00(8 - 1 downto 0);
    mul_ln41_fu_578_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_reg_1004_pp0_iter10_reg),17));
    mul_ln41_fu_578_p1 <= ap_const_lv17_1C8(10 - 1 downto 0);
    mul_ln42_fu_588_p0 <= mul_ln42_fu_588_p00(5 - 1 downto 0);
    mul_ln42_fu_588_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_500_p2),9));
    mul_ln42_fu_588_p1 <= ap_const_lv9_16(6 - 1 downto 0);
    not_icmp_ln1074_fu_833_p2 <= (icmp_ln1074_fu_789_p2 xor ap_const_lv1_1);
    or_ln47_fu_666_p2 <= (iy_fu_629_p2 or ix_fu_656_p2);
    p_shl_fu_389_p3 <= (oc_fu_146 & ap_const_lv7_0);
    pixel_3_fu_745_p3 <= 
        stage1_q0 when (icmp_ln47_reg_1040(0) = '1') else 
        ap_const_lv7_0;
    select_ln1078_cast_fu_839_p3 <= 
        ap_const_lv7_7F when (not_icmp_ln1074_fu_833_p2(0) = '1') else 
        ap_const_lv7_0;
    select_ln34_3_fu_774_p3 <= 
        maximum_6_fu_150 when (icmp_ln39_reg_996_pp0_iter14_reg(0) = '1') else 
        maximum_reg_289;
    select_ln34_fu_549_p3 <= 
        add_ln34_3_fu_524_p2 when (icmp_ln39_reg_996_pp0_iter9_reg(0) = '1') else 
        ap_phi_mux_p_phi_fu_282_p4;
        sext_ln1075_fu_794_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_891_p3),32));

        sext_ln44_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln44_fu_619_p2),6));

        sext_ln45_3_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ix_fu_656_p2),12));

        sext_ln45_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_fu_646_p2),6));

        sext_ln48_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(iy_fu_629_p2),8));

        sext_ln50_4_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(CONV2_BIAS_q0),23));

    shl_ln48_3_fu_716_p3 <= (add_ln48_fu_710_p2 & ap_const_lv4_0);
    shl_ln4_fu_698_p3 <= (tmp_3_fu_688_p4 & ap_const_lv4_0);
    shl_ln_fu_781_p4 <= ((trunc_ln57_reg_935 & trunc_ln57_3_reg_952) & ap_const_lv3_0);
    stage1_address0 <= zext_ln48_fu_730_p1(12 - 1 downto 0);
    stage1_ce0 <= stage1_ce0_local;

    stage1_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stage1_ce0_local <= ap_const_logic_1;
        else 
            stage1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    stage2_address1 <= zext_ln57_2_fu_881_p1(11 - 1 downto 0);
    stage2_ce1 <= stage2_ce1_local;

    stage2_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stage2_ce1_local <= ap_const_logic_1;
        else 
            stage2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    stage2_d1 <= maximum_7_fu_867_p3;
    stage2_we1 <= stage2_we1_local;

    stage2_we1_local_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln39_3_reg_1021_pp0_iter14_reg, icmp_ln34_3_reg_1036_pp0_iter14_reg, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln34_3_reg_1036_pp0_iter14_reg = ap_const_lv1_1) and (icmp_ln39_3_reg_1021_pp0_iter14_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stage2_we1_local <= ap_const_logic_1;
        else 
            stage2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_608_p3 <= (trunc_ln57_3_reg_952 & tmp_6_fu_565_p3);
    tmp4_fu_635_p3 <= (trunc_ln37_reg_982 & trunc_ln34_fu_562_p1);
    tmp_3_fu_688_p4 <= mul_ln41_fu_578_p2(15 downto 12);
    tmp_6_fu_565_p3 <= select_ln34_reg_1029(1 downto 1);
    tmp_7_fu_672_p4 <= or_ln47_fu_666_p2(5 downto 4);
    tmp_8_fu_807_p4 <= add_ln1076_fu_801_p2(32 downto 15);
    tmp_fu_396_p3 <= (oc_fu_146 & ap_const_lv4_0);
    trunc_ln34_fu_562_p1 <= select_ln34_reg_1029(1 - 1 downto 0);
    trunc_ln37_fu_464_p1 <= ox_reg_245(3 - 1 downto 0);
    trunc_ln42_3_fu_594_p4 <= mul_ln42_fu_588_p2(7 downto 6);
    trunc_ln43_fu_604_p1 <= grp_fu_506_p2(2 - 1 downto 0);
    trunc_ln57_3_fu_434_p1 <= oy_reg_222(3 - 1 downto 0);
    trunc_ln57_fu_413_p1 <= oc_fu_146(5 - 1 downto 0);
    trunc_ln_fu_823_p4 <= add_ln1076_fu_801_p2(14 downto 8);
    value_fu_853_p3 <= 
        select_ln1078_cast_fu_839_p3 when (empty_fu_847_p2(0) = '1') else 
        trunc_ln_fu_823_p4;
    zext_ln1075_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1075_fu_794_p1),33));
    zext_ln27_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oc_fu_146),64));
    zext_ln31_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ox_reg_245),11));
    zext_ln39_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_reg_1004_pp0_iter10_reg),13));
    zext_ln44_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_608_p3),6));
    zext_ln45_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_fu_635_p3),6));
    zext_ln48_fu_730_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln48_3_fu_724_p2),64));
    zext_ln50_2_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln50_fu_735_p2),64));
    zext_ln57_2_fu_881_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln57_fu_876_p2),64));
    zext_ln57_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_396_p3),13));
end behav;
