-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cifar10_cnn_conv_relu_pool_32_64_8_7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stage2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    stage2_ce0 : OUT STD_LOGIC;
    stage2_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    stage3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    stage3_ce1 : OUT STD_LOGIC;
    stage3_we1 : OUT STD_LOGIC;
    stage3_d1 : OUT STD_LOGIC_VECTOR (6 downto 0) );
end;


architecture behav of cifar10_cnn_conv_relu_pool_32_64_8_7_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv11_480 : STD_LOGIC_VECTOR (10 downto 0) := "10010000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv9_120 : STD_LOGIC_VECTOR (8 downto 0) := "100100000";
    constant ap_const_lv9_9 : STD_LOGIC_VECTOR (8 downto 0) := "000001001";
    constant ap_const_lv9_3 : STD_LOGIC_VECTOR (8 downto 0) := "000000011";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv19_38F : STD_LOGIC_VECTOR (18 downto 0) := "0000000001110001111";
    constant ap_const_lv9_16 : STD_LOGIC_VECTOR (8 downto 0) := "000010110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv23_1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";
    constant ap_const_lv33_40 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000001000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal CONV3_BIAS_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal CONV3_BIAS_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal CONV3_WEIGHT_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal CONV3_WEIGHT_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_reg_254 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_reg_265 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_reg_276 : STD_LOGIC_VECTOR (2 downto 0);
    signal maximum_reg_287 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln50_18_reg_299 : STD_LOGIC_VECTOR (22 downto 0);
    signal accumulator_1_reg_311 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln27_fu_372_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln27_reg_918 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln50_1_fu_383_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln50_1_reg_928 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln57_1_fu_405_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln57_1_reg_934 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln57_fu_411_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln57_reg_939 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln29_fu_420_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln29_reg_947 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal first_iter_3_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_3_reg_952 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln57_1_fu_432_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln57_1_reg_956 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln36_fu_436_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln36_reg_961 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln31_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln31_fu_452_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln31_reg_970 : STD_LOGIC_VECTOR (2 downto 0);
    signal first_iter_2_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_reg_981 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln31_fu_464_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln31_reg_985 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln37_fu_468_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln37_reg_990 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln34_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln34_reg_995_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_995_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln34_fu_478_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln39_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_1004_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal k_mid2_fu_490_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012 : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter3_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter6_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter7_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter8_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter9_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter10_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal k_mid2_reg_1012_pp0_iter11_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal first_iter_0_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1020_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln39_fu_516_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln39_reg_1024 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln39_1_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_1_reg_1029_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_fu_546_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1033 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1033_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1033_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_1_mid2_reg_1033_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_fu_553_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln34_reg_1037 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal icmp_ln34_1_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_reg_1044 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_reg_1044_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_reg_1044_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_reg_1044_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_reg_1044_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_686_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_1048 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_1_fu_778_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal grp_fu_895_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter15_state21 : STD_LOGIC;
    signal sext_ln50_15_reg_208 : STD_LOGIC_VECTOR (22 downto 0);
    signal oy_reg_220 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln50_16_reg_231 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln29_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal ox_reg_243 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_k_phi_fu_269_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_p_phi_fu_280_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_sext_ln50_18_phi_fu_303_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_mux_accumulator_1_phi_fu_314_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter15_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_predicate_pred402_state21 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter1_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter2_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter3_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter4_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter5_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter6_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter7_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter8_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter9_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter10_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter11_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter13_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter14_sext_ln50_19_reg_321 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_mux_sext_ln50_11_phi_fu_345_p10 : STD_LOGIC_VECTOR (22 downto 0);
    signal accumulator_1_mid2_fu_764_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter15_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter0_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter1_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter2_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter3_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter4_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter5_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter6_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter7_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter8_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter9_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter10_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter11_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter13_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_phi_reg_pp0_iter14_sext_ln50_11_reg_342 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln27_fu_378_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln27_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln48_fu_734_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln50_1_fu_744_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_1_fu_885_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal oc_fu_144 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal maximum_2_fu_148 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal maximum_3_fu_871_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal CONV3_BIAS_ce0_local : STD_LOGIC;
    signal stage2_ce0_local : STD_LOGIC;
    signal CONV3_WEIGHT_ce0_local : STD_LOGIC;
    signal stage3_we1_local : STD_LOGIC;
    signal stage3_ce1_local : STD_LOGIC;
    signal tmp_fu_394_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl_fu_387_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln57_fu_401_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_504_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_510_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln34_1_fu_528_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal first_iter_1_mid1_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_120_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln_fu_569_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln41_fu_588_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln41_fu_588_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_fu_594_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_504_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln42_fu_594_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_fu_594_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_510_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln36_fu_578_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln44_fu_614_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln42_1_fu_600_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln44_1_fu_623_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln44_fu_629_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln44_fu_619_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln34_fu_566_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_639_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln43_fu_610_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln45_fu_650_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln45_fu_656_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln45_fu_646_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ix_fu_660_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal iy_fu_633_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln47_fu_670_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_676_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln41_fu_588_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_1_fu_692_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln48_fu_710_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln2_fu_702_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln48_fu_714_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln48_1_fu_720_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln45_1_fu_666_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln48_1_fu_728_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln39_fu_582_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln50_fu_739_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal pixel_1_fu_749_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln1075_fu_798_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1075_fu_801_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1076_fu_805_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_3_fu_811_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln1074_fu_793_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_icmp_ln1074_fu_837_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1078_fu_821_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1078_cast_fu_843_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln5_fu_827_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal value_fu_857_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln55_fu_865_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln1_fu_785_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln57_fu_880_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_895_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_895_p10 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln41_fu_588_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_condition_457 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component cifar10_cnn_urem_9ns_5ns_9_13_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component cifar10_cnn_urem_9ns_3ns_2_13_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component cifar10_cnn_mul_9ns_11ns_19_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component cifar10_cnn_mul_5s_6ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component cifar10_cnn_mac_muladd_8s_7ns_23s_23_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (22 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component cifar10_cnn_conv_relu_pool_32_64_8_7_s_CONV3_BIAS_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component cifar10_cnn_conv_relu_pool_32_64_8_7_s_CONV3_WEIGHT_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    CONV3_BIAS_U : component cifar10_cnn_conv_relu_pool_32_64_8_7_s_CONV3_BIAS_ROM_AUTO_1R
    generic map (
        DataWidth => 9,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => CONV3_BIAS_address0,
        ce0 => CONV3_BIAS_ce0_local,
        q0 => CONV3_BIAS_q0);

    CONV3_WEIGHT_U : component cifar10_cnn_conv_relu_pool_32_64_8_7_s_CONV3_WEIGHT_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 18432,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => CONV3_WEIGHT_address0,
        ce0 => CONV3_WEIGHT_ce0_local,
        q0 => CONV3_WEIGHT_q0);

    urem_9ns_5ns_9_13_1_U32 : component cifar10_cnn_urem_9ns_5ns_9_13_1
    generic map (
        ID => 1,
        NUM_STAGE => 13,
        din0_WIDTH => 9,
        din1_WIDTH => 5,
        dout_WIDTH => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => k_mid2_fu_490_p3,
        din1 => grp_fu_504_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_504_p2);

    urem_9ns_3ns_2_13_1_U33 : component cifar10_cnn_urem_9ns_3ns_2_13_1
    generic map (
        ID => 1,
        NUM_STAGE => 13,
        din0_WIDTH => 9,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => k_mid2_fu_490_p3,
        din1 => grp_fu_510_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_510_p2);

    mul_9ns_11ns_19_1_1_U34 : component cifar10_cnn_mul_9ns_11ns_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln41_fu_588_p0,
        din1 => mul_ln41_fu_588_p1,
        dout => mul_ln41_fu_588_p2);

    mul_5s_6ns_9_1_1_U35 : component cifar10_cnn_mul_5s_6ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 6,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln42_fu_594_p0,
        din1 => mul_ln42_fu_594_p1,
        dout => mul_ln42_fu_594_p2);

    mac_muladd_8s_7ns_23s_23_4_1_U36 : component cifar10_cnn_mac_muladd_8s_7ns_23s_23_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 23,
        dout_WIDTH => 23)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => CONV3_WEIGHT_q0,
        din1 => grp_fu_895_p1,
        din2 => ap_phi_mux_sext_ln50_11_phi_fu_345_p10,
        ce => ap_const_logic_1,
        dout => grp_fu_895_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                elsif ((((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter15_state21) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0)))) then 
                    ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter15_state21) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter14;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    accumulator_1_reg_311_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln34_reg_995_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                accumulator_1_reg_311 <= grp_fu_895_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0))) then 
                accumulator_1_reg_311 <= sext_ln50_16_reg_231;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_457)) then 
                    ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342 <= sext_ln50_1_reg_928;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter11_sext_ln50_11_reg_342;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_457)) then 
                    ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321 <= sext_ln50_1_reg_928;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter11_sext_ln50_19_reg_321;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln34_fu_472_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_254 <= add_ln34_fu_478_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_254 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    k_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln34_reg_995 = ap_const_lv1_0))) then 
                k_reg_265 <= add_ln39_reg_1024;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0))) then 
                k_reg_265 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    maximum_reg_287_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln34_reg_995_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                maximum_reg_287 <= select_ln34_1_fu_778_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0))) then 
                maximum_reg_287 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    oc_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                oc_fu_144 <= ap_const_lv7_0;
            elsif (((icmp_ln29_fu_414_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                oc_fu_144 <= add_ln27_reg_918;
            end if; 
        end if;
    end process;

    ox_reg_243_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
                ox_reg_243 <= add_ln31_reg_970;
            elsif (((icmp_ln29_fu_414_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                ox_reg_243 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    oy_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_1))) then 
                oy_reg_220 <= add_ln29_reg_947;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                oy_reg_220 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    p_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_reg_995_pp0_iter11_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                p_reg_276 <= select_ln34_reg_1037;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0))) then 
                p_reg_276 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    sext_ln50_16_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
                sext_ln50_16_reg_231 <= sext_ln50_18_reg_299;
            elsif (((icmp_ln29_fu_414_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                sext_ln50_16_reg_231 <= sext_ln50_15_reg_208;
            end if; 
        end if;
    end process;

    sext_ln50_18_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln34_reg_995_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sext_ln50_18_reg_299 <= sext_ln50_19_reg_321;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_0))) then 
                sext_ln50_18_reg_299 <= sext_ln50_16_reg_231;
            end if; 
        end if;
    end process;

    sext_ln50_19_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_predicate_pred402_state21 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (first_iter_1_mid2_reg_1033_pp0_iter14_reg = ap_const_lv1_1) and (first_iter_0_reg_1020_pp0_iter14_reg = ap_const_lv1_1) and (icmp_ln34_reg_995_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (first_iter_2_reg_981 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (first_iter_1_mid2_reg_1033_pp0_iter14_reg = ap_const_lv1_0) and (first_iter_0_reg_1020_pp0_iter14_reg = ap_const_lv1_1) and (icmp_ln34_reg_995_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (first_iter_0_reg_1020_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln34_reg_995_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                sext_ln50_19_reg_321 <= ap_phi_mux_sext_ln50_18_phi_fu_303_p4;
            elsif (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter15_sext_ln50_19_reg_321;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln27_reg_918 <= add_ln27_fu_372_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln29_reg_947 <= add_ln29_fu_420_p2;
                first_iter_3_reg_952 <= first_iter_3_fu_426_p2;
                shl_ln36_reg_961 <= shl_ln36_fu_436_p2;
                trunc_ln57_1_reg_956 <= trunc_ln57_1_fu_432_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln31_reg_970 <= add_ln31_fu_452_p2;
                first_iter_2_reg_981 <= first_iter_2_fu_458_p2;
                trunc_ln37_reg_990 <= trunc_ln37_fu_468_p1;
                    zext_ln31_reg_985(2 downto 0) <= zext_ln31_fu_464_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln39_reg_1024 <= add_ln39_fu_516_p2;
                ap_phi_reg_pp0_iter1_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter0_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter1_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter0_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    add_ln57_1_reg_934(14 downto 5) <= add_ln57_1_fu_405_p2(14 downto 5);
                sext_ln50_1_reg_928 <= sext_ln50_1_fu_383_p1;
                trunc_ln57_reg_939 <= trunc_ln57_fu_411_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter10_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter9_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter10_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter9_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter11_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter10_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter11_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter10_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter13_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter13_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter14_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter13_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter14_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter13_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter15_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter14_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter15_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter14_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter2_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter1_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter2_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter1_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter3_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter2_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter3_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter2_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter4_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter3_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter4_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter3_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter5_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter4_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter5_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter4_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter6_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter5_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter6_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter5_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter7_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter6_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter7_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter6_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter8_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter7_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter8_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter7_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter9_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter8_sext_ln50_11_reg_342;
                ap_phi_reg_pp0_iter9_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter8_sext_ln50_19_reg_321;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    ap_predicate_pred402_state21 <= ((first_iter_3_reg_952 = ap_const_lv1_0) and (first_iter_1_mid2_reg_1033_pp0_iter13_reg = ap_const_lv1_1) and (first_iter_0_reg_1020_pp0_iter13_reg = ap_const_lv1_1) and (icmp_ln34_reg_995_pp0_iter13_reg = ap_const_lv1_0) and (first_iter_2_reg_981 = ap_const_lv1_1));
                first_iter_0_reg_1020_pp0_iter10_reg <= first_iter_0_reg_1020_pp0_iter9_reg;
                first_iter_0_reg_1020_pp0_iter11_reg <= first_iter_0_reg_1020_pp0_iter10_reg;
                first_iter_0_reg_1020_pp0_iter12_reg <= first_iter_0_reg_1020_pp0_iter11_reg;
                first_iter_0_reg_1020_pp0_iter13_reg <= first_iter_0_reg_1020_pp0_iter12_reg;
                first_iter_0_reg_1020_pp0_iter14_reg <= first_iter_0_reg_1020_pp0_iter13_reg;
                first_iter_0_reg_1020_pp0_iter2_reg <= first_iter_0_reg_1020_pp0_iter1_reg;
                first_iter_0_reg_1020_pp0_iter3_reg <= first_iter_0_reg_1020_pp0_iter2_reg;
                first_iter_0_reg_1020_pp0_iter4_reg <= first_iter_0_reg_1020_pp0_iter3_reg;
                first_iter_0_reg_1020_pp0_iter5_reg <= first_iter_0_reg_1020_pp0_iter4_reg;
                first_iter_0_reg_1020_pp0_iter6_reg <= first_iter_0_reg_1020_pp0_iter5_reg;
                first_iter_0_reg_1020_pp0_iter7_reg <= first_iter_0_reg_1020_pp0_iter6_reg;
                first_iter_0_reg_1020_pp0_iter8_reg <= first_iter_0_reg_1020_pp0_iter7_reg;
                first_iter_0_reg_1020_pp0_iter9_reg <= first_iter_0_reg_1020_pp0_iter8_reg;
                first_iter_1_mid2_reg_1033 <= first_iter_1_mid2_fu_546_p3;
                first_iter_1_mid2_reg_1033_pp0_iter12_reg <= first_iter_1_mid2_reg_1033;
                first_iter_1_mid2_reg_1033_pp0_iter13_reg <= first_iter_1_mid2_reg_1033_pp0_iter12_reg;
                first_iter_1_mid2_reg_1033_pp0_iter14_reg <= first_iter_1_mid2_reg_1033_pp0_iter13_reg;
                icmp_ln34_1_reg_1044 <= icmp_ln34_1_fu_560_p2;
                icmp_ln34_1_reg_1044_pp0_iter12_reg <= icmp_ln34_1_reg_1044;
                icmp_ln34_1_reg_1044_pp0_iter13_reg <= icmp_ln34_1_reg_1044_pp0_iter12_reg;
                icmp_ln34_1_reg_1044_pp0_iter14_reg <= icmp_ln34_1_reg_1044_pp0_iter13_reg;
                icmp_ln34_1_reg_1044_pp0_iter15_reg <= icmp_ln34_1_reg_1044_pp0_iter14_reg;
                icmp_ln34_reg_995_pp0_iter10_reg <= icmp_ln34_reg_995_pp0_iter9_reg;
                icmp_ln34_reg_995_pp0_iter11_reg <= icmp_ln34_reg_995_pp0_iter10_reg;
                icmp_ln34_reg_995_pp0_iter12_reg <= icmp_ln34_reg_995_pp0_iter11_reg;
                icmp_ln34_reg_995_pp0_iter13_reg <= icmp_ln34_reg_995_pp0_iter12_reg;
                icmp_ln34_reg_995_pp0_iter14_reg <= icmp_ln34_reg_995_pp0_iter13_reg;
                icmp_ln34_reg_995_pp0_iter15_reg <= icmp_ln34_reg_995_pp0_iter14_reg;
                icmp_ln34_reg_995_pp0_iter2_reg <= icmp_ln34_reg_995_pp0_iter1_reg;
                icmp_ln34_reg_995_pp0_iter3_reg <= icmp_ln34_reg_995_pp0_iter2_reg;
                icmp_ln34_reg_995_pp0_iter4_reg <= icmp_ln34_reg_995_pp0_iter3_reg;
                icmp_ln34_reg_995_pp0_iter5_reg <= icmp_ln34_reg_995_pp0_iter4_reg;
                icmp_ln34_reg_995_pp0_iter6_reg <= icmp_ln34_reg_995_pp0_iter5_reg;
                icmp_ln34_reg_995_pp0_iter7_reg <= icmp_ln34_reg_995_pp0_iter6_reg;
                icmp_ln34_reg_995_pp0_iter8_reg <= icmp_ln34_reg_995_pp0_iter7_reg;
                icmp_ln34_reg_995_pp0_iter9_reg <= icmp_ln34_reg_995_pp0_iter8_reg;
                icmp_ln39_1_reg_1029_pp0_iter10_reg <= icmp_ln39_1_reg_1029_pp0_iter9_reg;
                icmp_ln39_1_reg_1029_pp0_iter11_reg <= icmp_ln39_1_reg_1029_pp0_iter10_reg;
                icmp_ln39_1_reg_1029_pp0_iter12_reg <= icmp_ln39_1_reg_1029_pp0_iter11_reg;
                icmp_ln39_1_reg_1029_pp0_iter13_reg <= icmp_ln39_1_reg_1029_pp0_iter12_reg;
                icmp_ln39_1_reg_1029_pp0_iter14_reg <= icmp_ln39_1_reg_1029_pp0_iter13_reg;
                icmp_ln39_1_reg_1029_pp0_iter15_reg <= icmp_ln39_1_reg_1029_pp0_iter14_reg;
                icmp_ln39_1_reg_1029_pp0_iter2_reg <= icmp_ln39_1_reg_1029_pp0_iter1_reg;
                icmp_ln39_1_reg_1029_pp0_iter3_reg <= icmp_ln39_1_reg_1029_pp0_iter2_reg;
                icmp_ln39_1_reg_1029_pp0_iter4_reg <= icmp_ln39_1_reg_1029_pp0_iter3_reg;
                icmp_ln39_1_reg_1029_pp0_iter5_reg <= icmp_ln39_1_reg_1029_pp0_iter4_reg;
                icmp_ln39_1_reg_1029_pp0_iter6_reg <= icmp_ln39_1_reg_1029_pp0_iter5_reg;
                icmp_ln39_1_reg_1029_pp0_iter7_reg <= icmp_ln39_1_reg_1029_pp0_iter6_reg;
                icmp_ln39_1_reg_1029_pp0_iter8_reg <= icmp_ln39_1_reg_1029_pp0_iter7_reg;
                icmp_ln39_1_reg_1029_pp0_iter9_reg <= icmp_ln39_1_reg_1029_pp0_iter8_reg;
                icmp_ln39_reg_1004_pp0_iter10_reg <= icmp_ln39_reg_1004_pp0_iter9_reg;
                icmp_ln39_reg_1004_pp0_iter11_reg <= icmp_ln39_reg_1004_pp0_iter10_reg;
                icmp_ln39_reg_1004_pp0_iter12_reg <= icmp_ln39_reg_1004_pp0_iter11_reg;
                icmp_ln39_reg_1004_pp0_iter13_reg <= icmp_ln39_reg_1004_pp0_iter12_reg;
                icmp_ln39_reg_1004_pp0_iter14_reg <= icmp_ln39_reg_1004_pp0_iter13_reg;
                icmp_ln39_reg_1004_pp0_iter15_reg <= icmp_ln39_reg_1004_pp0_iter14_reg;
                icmp_ln39_reg_1004_pp0_iter2_reg <= icmp_ln39_reg_1004_pp0_iter1_reg;
                icmp_ln39_reg_1004_pp0_iter3_reg <= icmp_ln39_reg_1004_pp0_iter2_reg;
                icmp_ln39_reg_1004_pp0_iter4_reg <= icmp_ln39_reg_1004_pp0_iter3_reg;
                icmp_ln39_reg_1004_pp0_iter5_reg <= icmp_ln39_reg_1004_pp0_iter4_reg;
                icmp_ln39_reg_1004_pp0_iter6_reg <= icmp_ln39_reg_1004_pp0_iter5_reg;
                icmp_ln39_reg_1004_pp0_iter7_reg <= icmp_ln39_reg_1004_pp0_iter6_reg;
                icmp_ln39_reg_1004_pp0_iter8_reg <= icmp_ln39_reg_1004_pp0_iter7_reg;
                icmp_ln39_reg_1004_pp0_iter9_reg <= icmp_ln39_reg_1004_pp0_iter8_reg;
                icmp_ln47_reg_1048 <= icmp_ln47_fu_686_p2;
                k_mid2_reg_1012_pp0_iter10_reg <= k_mid2_reg_1012_pp0_iter9_reg;
                k_mid2_reg_1012_pp0_iter11_reg <= k_mid2_reg_1012_pp0_iter10_reg;
                k_mid2_reg_1012_pp0_iter2_reg <= k_mid2_reg_1012_pp0_iter1_reg;
                k_mid2_reg_1012_pp0_iter3_reg <= k_mid2_reg_1012_pp0_iter2_reg;
                k_mid2_reg_1012_pp0_iter4_reg <= k_mid2_reg_1012_pp0_iter3_reg;
                k_mid2_reg_1012_pp0_iter5_reg <= k_mid2_reg_1012_pp0_iter4_reg;
                k_mid2_reg_1012_pp0_iter6_reg <= k_mid2_reg_1012_pp0_iter5_reg;
                k_mid2_reg_1012_pp0_iter7_reg <= k_mid2_reg_1012_pp0_iter6_reg;
                k_mid2_reg_1012_pp0_iter8_reg <= k_mid2_reg_1012_pp0_iter7_reg;
                k_mid2_reg_1012_pp0_iter9_reg <= k_mid2_reg_1012_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                first_iter_0_reg_1020 <= first_iter_0_fu_498_p2;
                first_iter_0_reg_1020_pp0_iter1_reg <= first_iter_0_reg_1020;
                icmp_ln34_reg_995 <= icmp_ln34_fu_472_p2;
                icmp_ln34_reg_995_pp0_iter1_reg <= icmp_ln34_reg_995;
                icmp_ln39_1_reg_1029 <= icmp_ln39_1_fu_522_p2;
                icmp_ln39_1_reg_1029_pp0_iter1_reg <= icmp_ln39_1_reg_1029;
                icmp_ln39_reg_1004 <= icmp_ln39_fu_484_p2;
                icmp_ln39_reg_1004_pp0_iter1_reg <= icmp_ln39_reg_1004;
                k_mid2_reg_1012 <= k_mid2_fu_490_p3;
                k_mid2_reg_1012_pp0_iter1_reg <= k_mid2_reg_1012;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln34_reg_995_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                maximum_2_fu_148 <= maximum_3_fu_871_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln34_reg_1037 <= select_ln34_fu_553_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_1))) then
                sext_ln50_15_reg_208 <= sext_ln50_16_reg_231;
            end if;
        end if;
    end process;
    add_ln57_1_reg_934(4 downto 0) <= "00000";
    zext_ln31_reg_985(9 downto 3) <= "0000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, icmp_ln31_fu_446_p2, ap_CS_fsm_state5, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, icmp_ln29_fu_414_p2, icmp_ln27_fu_366_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln27_fu_366_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln29_fu_414_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln31_fu_446_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    CONV3_BIAS_address0 <= zext_ln27_fu_378_p1(6 - 1 downto 0);

    CONV3_BIAS_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            CONV3_BIAS_ce0_local <= ap_const_logic_1;
        else 
            CONV3_BIAS_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    CONV3_WEIGHT_address0 <= zext_ln50_1_fu_744_p1(15 - 1 downto 0);

    CONV3_WEIGHT_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            CONV3_WEIGHT_ce0_local <= ap_const_logic_1;
        else 
            CONV3_WEIGHT_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    accumulator_1_mid2_fu_764_p3 <= 
        ap_phi_mux_sext_ln50_18_phi_fu_303_p4 when (icmp_ln39_reg_1004_pp0_iter14_reg(0) = '1') else 
        ap_phi_mux_accumulator_1_phi_fu_314_p4;
    add_ln1076_fu_805_p2 <= std_logic_vector(unsigned(zext_ln1075_fu_801_p1) + unsigned(ap_const_lv33_40));
    add_ln27_fu_372_p2 <= std_logic_vector(unsigned(oc_fu_144) + unsigned(ap_const_lv7_1));
    add_ln29_fu_420_p2 <= std_logic_vector(unsigned(oy_reg_220) + unsigned(ap_const_lv3_1));
    add_ln31_fu_452_p2 <= std_logic_vector(unsigned(ox_reg_243) + unsigned(ap_const_lv3_1));
    add_ln34_1_fu_528_p2 <= std_logic_vector(unsigned(ap_phi_mux_p_phi_fu_280_p4) + unsigned(ap_const_lv3_1));
    add_ln34_fu_478_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_254) + unsigned(ap_const_lv11_1));
    add_ln39_fu_516_p2 <= std_logic_vector(unsigned(k_mid2_fu_490_p3) + unsigned(ap_const_lv9_1));
    add_ln44_1_fu_623_p2 <= std_logic_vector(unsigned(trunc_ln42_1_fu_600_p4) + unsigned(ap_const_lv2_3));
    add_ln44_fu_614_p2 <= std_logic_vector(unsigned(zext_ln36_fu_578_p1) + unsigned(shl_ln36_reg_961));
    add_ln45_fu_650_p2 <= std_logic_vector(unsigned(trunc_ln43_fu_610_p1) + unsigned(ap_const_lv2_3));
    add_ln48_1_fu_728_p2 <= std_logic_vector(unsigned(shl_ln48_1_fu_720_p3) + unsigned(sext_ln45_1_fu_666_p1));
    add_ln48_fu_714_p2 <= std_logic_vector(signed(sext_ln48_fu_710_p1) + signed(shl_ln2_fu_702_p3));
    add_ln50_fu_739_p2 <= std_logic_vector(unsigned(zext_ln39_fu_582_p1) + unsigned(add_ln57_1_reg_934));
    add_ln57_1_fu_405_p2 <= std_logic_vector(unsigned(p_shl_fu_387_p3) + unsigned(zext_ln57_fu_401_p1));
    add_ln57_fu_880_p2 <= std_logic_vector(unsigned(zext_ln31_reg_985) + unsigned(shl_ln1_fu_785_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(5);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state23 <= ap_CS_fsm(6);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_457_assign_proc : process(first_iter_3_reg_952, first_iter_2_reg_981, icmp_ln34_reg_995_pp0_iter10_reg, first_iter_0_reg_1020_pp0_iter10_reg, first_iter_1_mid2_fu_546_p3)
    begin
                ap_condition_457 <= ((first_iter_3_reg_952 = ap_const_lv1_1) and (first_iter_1_mid2_fu_546_p3 = ap_const_lv1_1) and (first_iter_0_reg_1020_pp0_iter10_reg = ap_const_lv1_1) and (icmp_ln34_reg_995_pp0_iter10_reg = ap_const_lv1_0) and (first_iter_2_reg_981 = ap_const_lv1_1));
    end process;


    ap_condition_pp0_exit_iter15_state21_assign_proc : process(ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter15_state21 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter15_state21 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(icmp_ln34_fu_472_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln34_fu_472_p2 = ap_const_lv1_1))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln27_fu_366_p2)
    begin
        if ((((icmp_ln27_fu_366_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_accumulator_1_phi_fu_314_p4_assign_proc : process(accumulator_1_reg_311, icmp_ln34_reg_995_pp0_iter15_reg, ap_enable_reg_pp0_iter16, grp_fu_895_p3, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln34_reg_995_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_accumulator_1_phi_fu_314_p4 <= grp_fu_895_p3;
        else 
            ap_phi_mux_accumulator_1_phi_fu_314_p4 <= accumulator_1_reg_311;
        end if; 
    end process;


    ap_phi_mux_k_phi_fu_269_p4_assign_proc : process(k_reg_265, icmp_ln34_reg_995, ap_CS_fsm_pp0_stage0, add_ln39_reg_1024, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln34_reg_995 = ap_const_lv1_0))) then 
            ap_phi_mux_k_phi_fu_269_p4 <= add_ln39_reg_1024;
        else 
            ap_phi_mux_k_phi_fu_269_p4 <= k_reg_265;
        end if; 
    end process;


    ap_phi_mux_p_phi_fu_280_p4_assign_proc : process(p_reg_276, icmp_ln34_reg_995_pp0_iter11_reg, select_ln34_reg_1037, ap_enable_reg_pp0_iter12, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (icmp_ln34_reg_995_pp0_iter11_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_p_phi_fu_280_p4 <= select_ln34_reg_1037;
        else 
            ap_phi_mux_p_phi_fu_280_p4 <= p_reg_276;
        end if; 
    end process;


    ap_phi_mux_sext_ln50_11_phi_fu_345_p10_assign_proc : process(first_iter_3_reg_952, first_iter_2_reg_981, icmp_ln34_reg_995_pp0_iter14_reg, first_iter_0_reg_1020_pp0_iter14_reg, first_iter_1_mid2_reg_1033_pp0_iter14_reg, accumulator_1_mid2_fu_764_p3, ap_phi_reg_pp0_iter15_sext_ln50_11_reg_342)
    begin
        if ((((first_iter_3_reg_952 = ap_const_lv1_0) and (first_iter_1_mid2_reg_1033_pp0_iter14_reg = ap_const_lv1_1) and (first_iter_0_reg_1020_pp0_iter14_reg = ap_const_lv1_1) and (icmp_ln34_reg_995_pp0_iter14_reg = ap_const_lv1_0) and (first_iter_2_reg_981 = ap_const_lv1_1)) or ((first_iter_1_mid2_reg_1033_pp0_iter14_reg = ap_const_lv1_1) and (first_iter_0_reg_1020_pp0_iter14_reg = ap_const_lv1_1) and (icmp_ln34_reg_995_pp0_iter14_reg = ap_const_lv1_0) and (first_iter_2_reg_981 = ap_const_lv1_0)) or ((first_iter_1_mid2_reg_1033_pp0_iter14_reg = ap_const_lv1_0) and (first_iter_0_reg_1020_pp0_iter14_reg = ap_const_lv1_1) and (icmp_ln34_reg_995_pp0_iter14_reg = ap_const_lv1_0)) or ((first_iter_0_reg_1020_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln34_reg_995_pp0_iter14_reg = ap_const_lv1_0)))) then 
            ap_phi_mux_sext_ln50_11_phi_fu_345_p10 <= accumulator_1_mid2_fu_764_p3;
        else 
            ap_phi_mux_sext_ln50_11_phi_fu_345_p10 <= ap_phi_reg_pp0_iter15_sext_ln50_11_reg_342;
        end if; 
    end process;


    ap_phi_mux_sext_ln50_18_phi_fu_303_p4_assign_proc : process(sext_ln50_18_reg_299, sext_ln50_19_reg_321, icmp_ln34_reg_995_pp0_iter15_reg, ap_enable_reg_pp0_iter16, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln34_reg_995_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_sext_ln50_18_phi_fu_303_p4 <= sext_ln50_19_reg_321;
        else 
            ap_phi_mux_sext_ln50_18_phi_fu_303_p4 <= sext_ln50_18_reg_299;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_sext_ln50_11_reg_342 <= "XXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_sext_ln50_19_reg_321 <= "XXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln27_fu_366_p2)
    begin
        if (((icmp_ln27_fu_366_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_851_p2 <= (icmp_ln1078_fu_821_p2 or icmp_ln1074_fu_793_p2);
    first_iter_0_fu_498_p2 <= "1" when (k_mid2_fu_490_p3 = ap_const_lv9_0) else "0";
    first_iter_120_fu_540_p2 <= "1" when (ap_phi_mux_p_phi_fu_280_p4 = ap_const_lv3_0) else "0";
    first_iter_1_mid1_fu_534_p2 <= "1" when (add_ln34_1_fu_528_p2 = ap_const_lv3_0) else "0";
    first_iter_1_mid2_fu_546_p3 <= 
        first_iter_1_mid1_fu_534_p2 when (icmp_ln39_reg_1004_pp0_iter10_reg(0) = '1') else 
        first_iter_120_fu_540_p2;
    first_iter_2_fu_458_p2 <= "1" when (ox_reg_243 = ap_const_lv3_0) else "0";
    first_iter_3_fu_426_p2 <= "1" when (oy_reg_220 = ap_const_lv3_0) else "0";
    grp_fu_504_p1 <= ap_const_lv9_9(5 - 1 downto 0);
    grp_fu_510_p1 <= ap_const_lv9_3(3 - 1 downto 0);
    grp_fu_895_p1 <= grp_fu_895_p10(7 - 1 downto 0);
    grp_fu_895_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pixel_1_fu_749_p3),15));
    icmp_ln1074_fu_793_p2 <= "1" when (signed(grp_fu_895_p3) < signed(ap_const_lv23_1)) else "0";
    icmp_ln1078_fu_821_p2 <= "0" when (tmp_3_fu_811_p4 = ap_const_lv19_0) else "1";
    icmp_ln27_fu_366_p2 <= "1" when (oc_fu_144 = ap_const_lv7_40) else "0";
    icmp_ln29_fu_414_p2 <= "1" when (oy_reg_220 = ap_const_lv3_4) else "0";
    icmp_ln31_fu_446_p2 <= "1" when (ox_reg_243 = ap_const_lv3_4) else "0";
    icmp_ln34_1_fu_560_p2 <= "1" when (select_ln34_fu_553_p3 = ap_const_lv3_3) else "0";
    icmp_ln34_fu_472_p2 <= "1" when (indvar_flatten_reg_254 = ap_const_lv11_480) else "0";
    icmp_ln39_1_fu_522_p2 <= "1" when (add_ln39_fu_516_p2 = ap_const_lv9_120) else "0";
    icmp_ln39_fu_484_p2 <= "1" when (ap_phi_mux_k_phi_fu_269_p4 = ap_const_lv9_120) else "0";
    icmp_ln47_fu_686_p2 <= "1" when (tmp_2_fu_676_p4 = ap_const_lv2_0) else "0";
    icmp_ln55_fu_865_p2 <= "1" when (unsigned(value_fu_857_p3) > unsigned(select_ln34_1_fu_778_p3)) else "0";
    ix_fu_660_p2 <= std_logic_vector(signed(sext_ln45_fu_656_p1) + signed(zext_ln45_fu_646_p1));
    iy_fu_633_p2 <= std_logic_vector(signed(sext_ln44_fu_629_p1) + signed(zext_ln44_fu_619_p1));
    k_mid2_fu_490_p3 <= 
        ap_const_lv9_0 when (icmp_ln39_fu_484_p2(0) = '1') else 
        ap_phi_mux_k_phi_fu_269_p4;
    lshr_ln_fu_569_p4 <= select_ln34_reg_1037(2 downto 1);
    maximum_3_fu_871_p3 <= 
        value_fu_857_p3 when (icmp_ln55_fu_865_p2(0) = '1') else 
        select_ln34_1_fu_778_p3;
    mul_ln41_fu_588_p0 <= mul_ln41_fu_588_p00(9 - 1 downto 0);
    mul_ln41_fu_588_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_reg_1012_pp0_iter11_reg),19));
    mul_ln41_fu_588_p1 <= ap_const_lv19_38F(11 - 1 downto 0);
    mul_ln42_fu_594_p0 <= grp_fu_504_p2(5 - 1 downto 0);
    mul_ln42_fu_594_p1 <= ap_const_lv9_16(6 - 1 downto 0);
    not_icmp_ln1074_fu_837_p2 <= (icmp_ln1074_fu_793_p2 xor ap_const_lv1_1);
    or_ln47_fu_670_p2 <= (iy_fu_633_p2 or ix_fu_660_p2);
    p_shl_fu_387_p3 <= (oc_fu_144 & ap_const_lv8_0);
    pixel_1_fu_749_p3 <= 
        stage2_q0 when (icmp_ln47_reg_1048(0) = '1') else 
        ap_const_lv7_0;
    select_ln1078_cast_fu_843_p3 <= 
        ap_const_lv7_7F when (not_icmp_ln1074_fu_837_p2(0) = '1') else 
        ap_const_lv7_0;
    select_ln34_1_fu_778_p3 <= 
        maximum_2_fu_148 when (icmp_ln39_reg_1004_pp0_iter15_reg(0) = '1') else 
        maximum_reg_287;
    select_ln34_fu_553_p3 <= 
        add_ln34_1_fu_528_p2 when (icmp_ln39_reg_1004_pp0_iter10_reg(0) = '1') else 
        ap_phi_mux_p_phi_fu_280_p4;
        sext_ln1075_fu_798_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_895_p3),32));

        sext_ln44_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln44_1_fu_623_p2),5));

        sext_ln45_1_fu_666_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ix_fu_660_p2),11));

        sext_ln45_fu_656_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_fu_650_p2),5));

        sext_ln48_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(iy_fu_633_p2),8));

        sext_ln50_1_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(CONV3_BIAS_q0),23));

    shl_ln1_fu_785_p4 <= ((trunc_ln57_reg_939 & trunc_ln57_1_reg_956) & ap_const_lv2_0);
    shl_ln2_fu_702_p3 <= (tmp_1_fu_692_p4 & ap_const_lv3_0);
    shl_ln36_fu_436_p2 <= std_logic_vector(shift_left(unsigned(oy_reg_220),to_integer(unsigned('0' & ap_const_lv3_1(3-1 downto 0)))));
    shl_ln48_1_fu_720_p3 <= (add_ln48_fu_714_p2 & ap_const_lv3_0);
    stage2_address0 <= zext_ln48_fu_734_p1(11 - 1 downto 0);
    stage2_ce0 <= stage2_ce0_local;

    stage2_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stage2_ce0_local <= ap_const_logic_1;
        else 
            stage2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    stage3_address1 <= zext_ln57_1_fu_885_p1(10 - 1 downto 0);
    stage3_ce1 <= stage3_ce1_local;

    stage3_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stage3_ce1_local <= ap_const_logic_1;
        else 
            stage3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    stage3_d1 <= maximum_3_fu_871_p3;
    stage3_we1 <= stage3_we1_local;

    stage3_we1_local_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln39_1_reg_1029_pp0_iter15_reg, icmp_ln34_1_reg_1044_pp0_iter15_reg, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln34_1_reg_1044_pp0_iter15_reg = ap_const_lv1_1) and (icmp_ln39_1_reg_1029_pp0_iter15_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stage3_we1_local <= ap_const_logic_1;
        else 
            stage3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp4_fu_639_p3 <= (trunc_ln37_reg_990 & trunc_ln34_fu_566_p1);
    tmp_1_fu_692_p4 <= mul_ln41_fu_588_p2(17 downto 13);
    tmp_2_fu_676_p4 <= or_ln47_fu_670_p2(4 downto 3);
    tmp_3_fu_811_p4 <= add_ln1076_fu_805_p2(32 downto 14);
    tmp_fu_394_p3 <= (oc_fu_144 & ap_const_lv5_0);
    trunc_ln34_fu_566_p1 <= select_ln34_reg_1037(1 - 1 downto 0);
    trunc_ln37_fu_468_p1 <= ox_reg_243(2 - 1 downto 0);
    trunc_ln42_1_fu_600_p4 <= mul_ln42_fu_594_p2(7 downto 6);
    trunc_ln43_fu_610_p1 <= grp_fu_510_p2(2 - 1 downto 0);
    trunc_ln57_1_fu_432_p1 <= oy_reg_220(2 - 1 downto 0);
    trunc_ln57_fu_411_p1 <= oc_fu_144(6 - 1 downto 0);
    trunc_ln5_fu_827_p4 <= add_ln1076_fu_805_p2(13 downto 7);
    value_fu_857_p3 <= 
        select_ln1078_cast_fu_843_p3 when (empty_fu_851_p2(0) = '1') else 
        trunc_ln5_fu_827_p4;
    zext_ln1075_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1075_fu_798_p1),33));
    zext_ln27_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oc_fu_144),64));
    zext_ln31_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ox_reg_243),10));
    zext_ln36_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_569_p4),3));
    zext_ln39_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_reg_1012_pp0_iter11_reg),15));
    zext_ln44_fu_619_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln44_fu_614_p2),5));
    zext_ln45_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_fu_639_p3),5));
    zext_ln48_fu_734_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln48_1_fu_728_p2),64));
    zext_ln50_1_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln50_fu_739_p2),64));
    zext_ln57_1_fu_885_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln57_fu_880_p2),64));
    zext_ln57_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_394_p3),15));
end behav;
