-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cifar10_cnn_conv_relu_pool_32_64_8_7_s_CONV3_BIAS_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 9; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cifar10_cnn_conv_relu_pool_32_64_8_7_s_CONV3_BIAS_ROM_AUTO_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "010000101", 1 => "000111100", 2 => "000010001", 3 => "111101110", 
    4 => "111010100", 5 => "111100000", 6 => "000100111", 7 => "001001110", 
    8 => "111110011", 9 => "000011011", 10 => "001101000", 11 => "110110110", 
    12 => "111111010", 13 => "000010001", 14 => "000011000", 15 => "111100000", 
    16 => "111100111", 17 => "000000100", 18 => "111111110", 19 => "000110111", 
    20 => "000100100", 21 => "111110110", 22 => "000000001", 23 => "000010000", 
    24 => "111111111", 25 => "000011111", 26 => "111101001", 27 => "111100100", 
    28 => "110110101", 29 => "111111011", 30 => "001000011", 31 => "000111111", 
    32 => "000011111", 33 => "000101011", 34 => "111101111", 35 => "001100111", 
    36 => "001111111", 37 => "010000001", 38 => "111101010", 39 => "110100110", 
    40 => "000001111", 41 => "110111101", 42 => "111011011", 43 => "000101100", 
    44 => "111101010", 45 => "000111110", 46 => "110101011", 47 => "000010011", 
    48 => "111101111", 49 => "000100001", 50 => "000000110", 51 => "111111000", 
    52 => "000101000", 53 => "111111101", 54 => "111110000", 55 => "001010100", 
    56 => "111110101", 57 => "000000101", 58 => "111110101", 59 => "000111101", 
    60 => "000011011", 61 => "111101111", 62 => "111101110", 63 => "111111100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

