// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cifar10_cnn_conv_relu_pool_16_32_16_8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stage1_address0,
        stage1_ce0,
        stage1_q0,
        stage2_address1,
        stage2_ce1,
        stage2_we1,
        stage2_d1
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_pp0_stage0 = 7'd32;
parameter    ap_ST_fsm_state22 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] stage1_address0;
output   stage1_ce0;
input  [6:0] stage1_q0;
output  [10:0] stage2_address1;
output   stage2_ce1;
output   stage2_we1;
output  [6:0] stage2_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] CONV2_BIAS_address0;
wire   [10:0] CONV2_BIAS_q0;
wire   [12:0] CONV2_WEIGHT_address0;
wire  signed [7:0] CONV2_WEIGHT_q0;
reg   [9:0] indvar_flatten_reg_256;
reg   [7:0] k_reg_267;
reg   [2:0] p_reg_278;
reg   [6:0] maximum_reg_289;
reg   [22:0] sext_ln50_48_reg_301;
reg   [22:0] accumulator_5_reg_313;
reg   [22:0] sext_ln50_49_reg_323;
wire   [5:0] add_ln27_fu_374_p2;
reg   [5:0] add_ln27_reg_914;
wire    ap_CS_fsm_state2;
wire  signed [22:0] sext_ln50_4_fu_385_p1;
reg  signed [22:0] sext_ln50_4_reg_924;
wire    ap_CS_fsm_state3;
wire   [12:0] add_ln57_2_fu_407_p2;
reg   [12:0] add_ln57_2_reg_930;
wire   [4:0] trunc_ln57_fu_413_p1;
reg   [4:0] trunc_ln57_reg_935;
wire   [3:0] add_ln29_fu_422_p2;
reg   [3:0] add_ln29_reg_943;
wire    ap_CS_fsm_state4;
wire   [0:0] first_iter_3_fu_428_p2;
reg   [0:0] first_iter_3_reg_948;
wire   [2:0] trunc_ln57_3_fu_434_p1;
reg   [2:0] trunc_ln57_3_reg_952;
wire   [0:0] icmp_ln31_fu_442_p2;
wire    ap_CS_fsm_state5;
wire   [3:0] add_ln31_fu_448_p2;
reg   [3:0] add_ln31_reg_962;
wire   [0:0] first_iter_2_fu_454_p2;
reg   [0:0] first_iter_2_reg_973;
wire   [10:0] zext_ln31_fu_460_p1;
reg   [10:0] zext_ln31_reg_977;
wire   [2:0] trunc_ln37_fu_464_p1;
reg   [2:0] trunc_ln37_reg_982;
wire   [0:0] icmp_ln34_fu_468_p2;
reg   [0:0] icmp_ln34_reg_987;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln34_reg_987_pp0_iter1_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter2_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter3_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter4_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter5_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter6_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter7_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter8_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter9_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter10_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter11_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter12_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter13_reg;
reg   [0:0] icmp_ln34_reg_987_pp0_iter14_reg;
wire   [9:0] add_ln34_fu_474_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln39_fu_480_p2;
reg   [0:0] icmp_ln39_reg_996;
reg   [0:0] icmp_ln39_reg_996_pp0_iter1_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter2_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter3_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter4_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter5_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter6_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter7_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter8_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter9_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter10_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter11_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter12_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter13_reg;
reg   [0:0] icmp_ln39_reg_996_pp0_iter14_reg;
wire   [7:0] k_mid2_fu_486_p3;
reg   [7:0] k_mid2_reg_1004;
reg   [7:0] k_mid2_reg_1004_pp0_iter1_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter2_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter3_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter4_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter5_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter6_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter7_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter8_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter9_reg;
reg   [7:0] k_mid2_reg_1004_pp0_iter10_reg;
wire   [0:0] first_iter_0_fu_494_p2;
reg   [0:0] first_iter_0_reg_1012;
reg   [0:0] first_iter_0_reg_1012_pp0_iter1_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter2_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter3_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter4_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter5_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter6_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter7_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter8_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter9_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter10_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter11_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter12_reg;
reg   [0:0] first_iter_0_reg_1012_pp0_iter13_reg;
wire   [7:0] add_ln39_fu_512_p2;
reg   [7:0] add_ln39_reg_1016;
wire   [0:0] icmp_ln39_3_fu_518_p2;
reg   [0:0] icmp_ln39_3_reg_1021;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter1_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter2_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter3_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter4_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter5_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter6_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter7_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter8_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter9_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter10_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter11_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter12_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter13_reg;
reg   [0:0] icmp_ln39_3_reg_1021_pp0_iter14_reg;
wire   [0:0] first_iter_1_mid2_fu_542_p3;
reg   [0:0] first_iter_1_mid2_reg_1025;
reg   [0:0] first_iter_1_mid2_reg_1025_pp0_iter11_reg;
reg   [0:0] first_iter_1_mid2_reg_1025_pp0_iter12_reg;
reg   [0:0] first_iter_1_mid2_reg_1025_pp0_iter13_reg;
wire   [2:0] select_ln34_fu_549_p3;
reg   [2:0] select_ln34_reg_1029;
reg    ap_enable_reg_pp0_iter10;
wire   [0:0] icmp_ln34_3_fu_556_p2;
reg   [0:0] icmp_ln34_3_reg_1036;
reg   [0:0] icmp_ln34_3_reg_1036_pp0_iter11_reg;
reg   [0:0] icmp_ln34_3_reg_1036_pp0_iter12_reg;
reg   [0:0] icmp_ln34_3_reg_1036_pp0_iter13_reg;
reg   [0:0] icmp_ln34_3_reg_1036_pp0_iter14_reg;
wire   [0:0] icmp_ln47_fu_682_p2;
reg   [0:0] icmp_ln47_reg_1040;
wire   [6:0] select_ln34_3_fu_774_p3;
reg    ap_enable_reg_pp0_iter15;
wire  signed [22:0] grp_fu_891_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_condition_pp0_exit_iter14_state20;
reg   [22:0] sext_ln50_45_reg_210;
reg   [3:0] oy_reg_222;
reg   [22:0] sext_ln50_46_reg_233;
wire   [0:0] icmp_ln29_fu_416_p2;
wire    ap_CS_fsm_state22;
reg   [3:0] ox_reg_245;
reg   [7:0] ap_phi_mux_k_phi_fu_271_p4;
wire    ap_block_pp0_stage0;
reg   [2:0] ap_phi_mux_p_phi_fu_282_p4;
reg   [22:0] ap_phi_mux_sext_ln50_48_phi_fu_305_p4;
reg   [22:0] ap_phi_mux_accumulator_5_phi_fu_316_p4;
reg   [22:0] ap_phi_reg_pp0_iter14_sext_ln50_49_reg_323;
reg    ap_predicate_pred393_state20;
wire   [22:0] ap_phi_reg_pp0_iter0_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter1_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter2_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter3_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter4_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter5_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter6_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter7_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter8_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter9_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter10_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter12_sext_ln50_49_reg_323;
reg   [22:0] ap_phi_reg_pp0_iter13_sext_ln50_49_reg_323;
reg  signed [22:0] ap_phi_mux_sext_ln50_41_phi_fu_347_p10;
wire   [22:0] accumulator_5_mid2_fu_760_p3;
reg   [22:0] ap_phi_reg_pp0_iter14_sext_ln50_41_reg_344;
wire   [22:0] ap_phi_reg_pp0_iter0_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter1_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter2_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter3_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter4_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter5_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter6_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter7_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter8_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter9_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter10_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter12_sext_ln50_41_reg_344;
reg   [22:0] ap_phi_reg_pp0_iter13_sext_ln50_41_reg_344;
wire   [63:0] zext_ln27_fu_380_p1;
wire   [0:0] icmp_ln27_fu_368_p2;
wire   [63:0] zext_ln48_fu_730_p1;
wire   [63:0] zext_ln50_2_fu_740_p1;
wire   [63:0] zext_ln57_2_fu_881_p1;
reg   [5:0] oc_fu_146;
reg   [6:0] maximum_6_fu_150;
wire   [6:0] maximum_7_fu_867_p3;
reg    CONV2_BIAS_ce0_local;
reg    stage1_ce0_local;
reg    CONV2_WEIGHT_ce0_local;
reg    stage2_we1_local;
reg    stage2_ce1_local;
wire   [9:0] tmp_fu_396_p3;
wire   [12:0] p_shl_fu_389_p3;
wire   [12:0] zext_ln57_fu_403_p1;
wire   [4:0] grp_fu_500_p1;
wire   [2:0] grp_fu_506_p1;
wire   [2:0] add_ln34_3_fu_524_p2;
wire   [0:0] first_iter_1_mid1_fu_530_p2;
wire   [0:0] first_iter_120_fu_536_p2;
wire   [7:0] mul_ln41_fu_578_p0;
wire   [9:0] mul_ln41_fu_578_p1;
wire   [7:0] grp_fu_500_p2;
wire   [4:0] mul_ln42_fu_588_p0;
wire   [5:0] mul_ln42_fu_588_p1;
wire   [8:0] mul_ln42_fu_588_p2;
wire   [1:0] grp_fu_506_p2;
wire   [0:0] tmp_6_fu_565_p3;
wire   [3:0] tmp1_fu_608_p3;
wire   [1:0] trunc_ln42_3_fu_594_p4;
wire   [1:0] add_ln44_fu_619_p2;
wire  signed [5:0] sext_ln44_fu_625_p1;
wire   [5:0] zext_ln44_fu_615_p1;
wire   [0:0] trunc_ln34_fu_562_p1;
wire   [3:0] tmp4_fu_635_p3;
wire   [1:0] trunc_ln43_fu_604_p1;
wire   [1:0] add_ln45_fu_646_p2;
wire  signed [5:0] sext_ln45_fu_652_p1;
wire   [5:0] zext_ln45_fu_642_p1;
wire  signed [5:0] ix_fu_656_p2;
wire  signed [5:0] iy_fu_629_p2;
wire   [5:0] or_ln47_fu_666_p2;
wire   [1:0] tmp_7_fu_672_p4;
wire   [16:0] mul_ln41_fu_578_p2;
wire   [3:0] tmp_3_fu_688_p4;
wire  signed [7:0] sext_ln48_fu_706_p1;
wire   [7:0] shl_ln4_fu_698_p3;
wire   [7:0] add_ln48_fu_710_p2;
wire   [11:0] shl_ln48_3_fu_716_p3;
wire  signed [11:0] sext_ln45_3_fu_662_p1;
wire   [11:0] add_ln48_3_fu_724_p2;
wire   [12:0] zext_ln39_fu_572_p1;
wire   [12:0] add_ln50_fu_735_p2;
wire   [6:0] pixel_3_fu_745_p3;
wire  signed [31:0] sext_ln1075_fu_794_p1;
wire   [32:0] zext_ln1075_fu_797_p1;
wire   [32:0] add_ln1076_fu_801_p2;
wire   [17:0] tmp_8_fu_807_p4;
wire   [0:0] icmp_ln1074_fu_789_p2;
wire   [0:0] not_icmp_ln1074_fu_833_p2;
wire   [0:0] icmp_ln1078_fu_817_p2;
wire   [0:0] empty_fu_847_p2;
wire   [6:0] select_ln1078_cast_fu_839_p3;
wire   [6:0] trunc_ln_fu_823_p4;
wire   [6:0] value_fu_853_p3;
wire   [0:0] icmp_ln55_fu_861_p2;
wire   [10:0] shl_ln_fu_781_p4;
wire   [10:0] add_ln57_fu_876_p2;
wire   [6:0] grp_fu_891_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [14:0] grp_fu_891_p10;
wire   [16:0] mul_ln41_fu_578_p00;
wire   [8:0] mul_ln42_fu_588_p00;
reg    ap_condition_445;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 oc_fu_146 = 6'd0;
#0 maximum_6_fu_150 = 7'd0;
end

cifar10_cnn_conv_relu_pool_16_32_16_8_s_CONV2_BIAS_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
CONV2_BIAS_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONV2_BIAS_address0),
    .ce0(CONV2_BIAS_ce0_local),
    .q0(CONV2_BIAS_q0)
);

cifar10_cnn_conv_relu_pool_16_32_16_8_s_CONV2_WEIGHT_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 4608 ),
    .AddressWidth( 13 ))
CONV2_WEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONV2_WEIGHT_address0),
    .ce0(CONV2_WEIGHT_ce0_local),
    .q0(CONV2_WEIGHT_q0)
);

cifar10_cnn_urem_8ns_5ns_8_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
urem_8ns_5ns_8_12_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(k_mid2_fu_486_p3),
    .din1(grp_fu_500_p1),
    .ce(1'b1),
    .dout(grp_fu_500_p2)
);

cifar10_cnn_urem_8ns_3ns_2_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_8ns_3ns_2_12_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(k_mid2_fu_486_p3),
    .din1(grp_fu_506_p1),
    .ce(1'b1),
    .dout(grp_fu_506_p2)
);

cifar10_cnn_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U21(
    .din0(mul_ln41_fu_578_p0),
    .din1(mul_ln41_fu_578_p1),
    .dout(mul_ln41_fu_578_p2)
);

cifar10_cnn_mul_5ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_5ns_6ns_9_1_1_U22(
    .din0(mul_ln42_fu_588_p0),
    .din1(mul_ln42_fu_588_p1),
    .dout(mul_ln42_fu_588_p2)
);

cifar10_cnn_mac_muladd_8s_7ns_23s_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 23 ),
    .dout_WIDTH( 23 ))
mac_muladd_8s_7ns_23s_23_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(CONV2_WEIGHT_q0),
    .din1(grp_fu_891_p1),
    .din2(ap_phi_mux_sext_ln50_41_phi_fu_347_p10),
    .ce(1'b1),
    .dout(grp_fu_891_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end else if ((((ap_enable_reg_pp0_iter13 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter14_state20) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0)))) begin
            ap_enable_reg_pp0_iter14 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter14_state20) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter13;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter15 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln34_reg_987_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accumulator_5_reg_313 <= grp_fu_891_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0))) begin
        accumulator_5_reg_313 <= sext_ln50_46_reg_233;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_445)) begin
            ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344 <= sext_ln50_4_reg_924;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter10_sext_ln50_41_reg_344;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_445)) begin
            ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323 <= sext_ln50_4_reg_924;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter10_sext_ln50_49_reg_323;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_fu_468_p2 == 1'd0))) begin
        indvar_flatten_reg_256 <= add_ln34_fu_474_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0))) begin
        indvar_flatten_reg_256 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_987 == 1'd0))) begin
        k_reg_267 <= add_ln39_reg_1016;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0))) begin
        k_reg_267 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln34_reg_987_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        maximum_reg_289 <= select_ln34_3_fu_774_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0))) begin
        maximum_reg_289 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        oc_fu_146 <= 6'd0;
    end else if (((icmp_ln29_fu_416_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        oc_fu_146 <= add_ln27_reg_914;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ox_reg_245 <= add_ln31_reg_962;
    end else if (((icmp_ln29_fu_416_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ox_reg_245 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd1))) begin
        oy_reg_222 <= add_ln29_reg_943;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        oy_reg_222 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln34_reg_987_pp0_iter10_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_reg_278 <= select_ln34_reg_1029;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0))) begin
        p_reg_278 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        sext_ln50_46_reg_233 <= sext_ln50_48_reg_301;
    end else if (((icmp_ln29_fu_416_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sext_ln50_46_reg_233 <= sext_ln50_45_reg_210;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln34_reg_987_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sext_ln50_48_reg_301 <= sext_ln50_49_reg_323;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd0))) begin
        sext_ln50_48_reg_301 <= sext_ln50_46_reg_233;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_pred393_state20 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (first_iter_1_mid2_reg_1025_pp0_iter13_reg == 1'd1) & (first_iter_0_reg_1012_pp0_iter13_reg == 1'd1) & (icmp_ln34_reg_987_pp0_iter13_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_2_reg_973 == 1'd0)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (first_iter_1_mid2_reg_1025_pp0_iter13_reg == 1'd0) & (first_iter_0_reg_1012_pp0_iter13_reg == 1'd1) & (icmp_ln34_reg_987_pp0_iter13_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (first_iter_0_reg_1012_pp0_iter13_reg == 1'd0) & (icmp_ln34_reg_987_pp0_iter13_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sext_ln50_49_reg_323 <= ap_phi_mux_sext_ln50_48_phi_fu_305_p4;
    end else if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter14_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln27_reg_914 <= add_ln27_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln29_reg_943 <= add_ln29_fu_422_p2;
        first_iter_3_reg_948 <= first_iter_3_fu_428_p2;
        trunc_ln57_3_reg_952 <= trunc_ln57_3_fu_434_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln31_reg_962 <= add_ln31_fu_448_p2;
        first_iter_2_reg_973 <= first_iter_2_fu_454_p2;
        trunc_ln37_reg_982 <= trunc_ln37_fu_464_p1;
        zext_ln31_reg_977[3 : 0] <= zext_ln31_fu_460_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln39_reg_1016 <= add_ln39_fu_512_p2;
        ap_phi_reg_pp0_iter1_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter0_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter1_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter0_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln57_2_reg_930[12 : 4] <= add_ln57_2_fu_407_p2[12 : 4];
        sext_ln50_4_reg_924 <= sext_ln50_4_fu_385_p1;
        trunc_ln57_reg_935 <= trunc_ln57_fu_413_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter9_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter10_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter9_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter11_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter12_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter11_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter12_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter13_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter12_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter13_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter14_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter13_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter1_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter2_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter1_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter2_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter3_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter2_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter3_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter4_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter3_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter4_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter5_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter4_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter5_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter6_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter5_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter6_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter7_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter6_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter7_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter8_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter7_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_sext_ln50_41_reg_344 <= ap_phi_reg_pp0_iter8_sext_ln50_41_reg_344;
        ap_phi_reg_pp0_iter9_sext_ln50_49_reg_323 <= ap_phi_reg_pp0_iter8_sext_ln50_49_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_predicate_pred393_state20 <= ((first_iter_3_reg_948 == 1'd0) & (first_iter_1_mid2_reg_1025_pp0_iter12_reg == 1'd1) & (first_iter_0_reg_1012_pp0_iter12_reg == 1'd1) & (icmp_ln34_reg_987_pp0_iter12_reg == 1'd0) & (first_iter_2_reg_973 == 1'd1));
        first_iter_0_reg_1012_pp0_iter10_reg <= first_iter_0_reg_1012_pp0_iter9_reg;
        first_iter_0_reg_1012_pp0_iter11_reg <= first_iter_0_reg_1012_pp0_iter10_reg;
        first_iter_0_reg_1012_pp0_iter12_reg <= first_iter_0_reg_1012_pp0_iter11_reg;
        first_iter_0_reg_1012_pp0_iter13_reg <= first_iter_0_reg_1012_pp0_iter12_reg;
        first_iter_0_reg_1012_pp0_iter2_reg <= first_iter_0_reg_1012_pp0_iter1_reg;
        first_iter_0_reg_1012_pp0_iter3_reg <= first_iter_0_reg_1012_pp0_iter2_reg;
        first_iter_0_reg_1012_pp0_iter4_reg <= first_iter_0_reg_1012_pp0_iter3_reg;
        first_iter_0_reg_1012_pp0_iter5_reg <= first_iter_0_reg_1012_pp0_iter4_reg;
        first_iter_0_reg_1012_pp0_iter6_reg <= first_iter_0_reg_1012_pp0_iter5_reg;
        first_iter_0_reg_1012_pp0_iter7_reg <= first_iter_0_reg_1012_pp0_iter6_reg;
        first_iter_0_reg_1012_pp0_iter8_reg <= first_iter_0_reg_1012_pp0_iter7_reg;
        first_iter_0_reg_1012_pp0_iter9_reg <= first_iter_0_reg_1012_pp0_iter8_reg;
        first_iter_1_mid2_reg_1025 <= first_iter_1_mid2_fu_542_p3;
        first_iter_1_mid2_reg_1025_pp0_iter11_reg <= first_iter_1_mid2_reg_1025;
        first_iter_1_mid2_reg_1025_pp0_iter12_reg <= first_iter_1_mid2_reg_1025_pp0_iter11_reg;
        first_iter_1_mid2_reg_1025_pp0_iter13_reg <= first_iter_1_mid2_reg_1025_pp0_iter12_reg;
        icmp_ln34_3_reg_1036 <= icmp_ln34_3_fu_556_p2;
        icmp_ln34_3_reg_1036_pp0_iter11_reg <= icmp_ln34_3_reg_1036;
        icmp_ln34_3_reg_1036_pp0_iter12_reg <= icmp_ln34_3_reg_1036_pp0_iter11_reg;
        icmp_ln34_3_reg_1036_pp0_iter13_reg <= icmp_ln34_3_reg_1036_pp0_iter12_reg;
        icmp_ln34_3_reg_1036_pp0_iter14_reg <= icmp_ln34_3_reg_1036_pp0_iter13_reg;
        icmp_ln34_reg_987_pp0_iter10_reg <= icmp_ln34_reg_987_pp0_iter9_reg;
        icmp_ln34_reg_987_pp0_iter11_reg <= icmp_ln34_reg_987_pp0_iter10_reg;
        icmp_ln34_reg_987_pp0_iter12_reg <= icmp_ln34_reg_987_pp0_iter11_reg;
        icmp_ln34_reg_987_pp0_iter13_reg <= icmp_ln34_reg_987_pp0_iter12_reg;
        icmp_ln34_reg_987_pp0_iter14_reg <= icmp_ln34_reg_987_pp0_iter13_reg;
        icmp_ln34_reg_987_pp0_iter2_reg <= icmp_ln34_reg_987_pp0_iter1_reg;
        icmp_ln34_reg_987_pp0_iter3_reg <= icmp_ln34_reg_987_pp0_iter2_reg;
        icmp_ln34_reg_987_pp0_iter4_reg <= icmp_ln34_reg_987_pp0_iter3_reg;
        icmp_ln34_reg_987_pp0_iter5_reg <= icmp_ln34_reg_987_pp0_iter4_reg;
        icmp_ln34_reg_987_pp0_iter6_reg <= icmp_ln34_reg_987_pp0_iter5_reg;
        icmp_ln34_reg_987_pp0_iter7_reg <= icmp_ln34_reg_987_pp0_iter6_reg;
        icmp_ln34_reg_987_pp0_iter8_reg <= icmp_ln34_reg_987_pp0_iter7_reg;
        icmp_ln34_reg_987_pp0_iter9_reg <= icmp_ln34_reg_987_pp0_iter8_reg;
        icmp_ln39_3_reg_1021_pp0_iter10_reg <= icmp_ln39_3_reg_1021_pp0_iter9_reg;
        icmp_ln39_3_reg_1021_pp0_iter11_reg <= icmp_ln39_3_reg_1021_pp0_iter10_reg;
        icmp_ln39_3_reg_1021_pp0_iter12_reg <= icmp_ln39_3_reg_1021_pp0_iter11_reg;
        icmp_ln39_3_reg_1021_pp0_iter13_reg <= icmp_ln39_3_reg_1021_pp0_iter12_reg;
        icmp_ln39_3_reg_1021_pp0_iter14_reg <= icmp_ln39_3_reg_1021_pp0_iter13_reg;
        icmp_ln39_3_reg_1021_pp0_iter2_reg <= icmp_ln39_3_reg_1021_pp0_iter1_reg;
        icmp_ln39_3_reg_1021_pp0_iter3_reg <= icmp_ln39_3_reg_1021_pp0_iter2_reg;
        icmp_ln39_3_reg_1021_pp0_iter4_reg <= icmp_ln39_3_reg_1021_pp0_iter3_reg;
        icmp_ln39_3_reg_1021_pp0_iter5_reg <= icmp_ln39_3_reg_1021_pp0_iter4_reg;
        icmp_ln39_3_reg_1021_pp0_iter6_reg <= icmp_ln39_3_reg_1021_pp0_iter5_reg;
        icmp_ln39_3_reg_1021_pp0_iter7_reg <= icmp_ln39_3_reg_1021_pp0_iter6_reg;
        icmp_ln39_3_reg_1021_pp0_iter8_reg <= icmp_ln39_3_reg_1021_pp0_iter7_reg;
        icmp_ln39_3_reg_1021_pp0_iter9_reg <= icmp_ln39_3_reg_1021_pp0_iter8_reg;
        icmp_ln39_reg_996_pp0_iter10_reg <= icmp_ln39_reg_996_pp0_iter9_reg;
        icmp_ln39_reg_996_pp0_iter11_reg <= icmp_ln39_reg_996_pp0_iter10_reg;
        icmp_ln39_reg_996_pp0_iter12_reg <= icmp_ln39_reg_996_pp0_iter11_reg;
        icmp_ln39_reg_996_pp0_iter13_reg <= icmp_ln39_reg_996_pp0_iter12_reg;
        icmp_ln39_reg_996_pp0_iter14_reg <= icmp_ln39_reg_996_pp0_iter13_reg;
        icmp_ln39_reg_996_pp0_iter2_reg <= icmp_ln39_reg_996_pp0_iter1_reg;
        icmp_ln39_reg_996_pp0_iter3_reg <= icmp_ln39_reg_996_pp0_iter2_reg;
        icmp_ln39_reg_996_pp0_iter4_reg <= icmp_ln39_reg_996_pp0_iter3_reg;
        icmp_ln39_reg_996_pp0_iter5_reg <= icmp_ln39_reg_996_pp0_iter4_reg;
        icmp_ln39_reg_996_pp0_iter6_reg <= icmp_ln39_reg_996_pp0_iter5_reg;
        icmp_ln39_reg_996_pp0_iter7_reg <= icmp_ln39_reg_996_pp0_iter6_reg;
        icmp_ln39_reg_996_pp0_iter8_reg <= icmp_ln39_reg_996_pp0_iter7_reg;
        icmp_ln39_reg_996_pp0_iter9_reg <= icmp_ln39_reg_996_pp0_iter8_reg;
        icmp_ln47_reg_1040 <= icmp_ln47_fu_682_p2;
        k_mid2_reg_1004_pp0_iter10_reg <= k_mid2_reg_1004_pp0_iter9_reg;
        k_mid2_reg_1004_pp0_iter2_reg <= k_mid2_reg_1004_pp0_iter1_reg;
        k_mid2_reg_1004_pp0_iter3_reg <= k_mid2_reg_1004_pp0_iter2_reg;
        k_mid2_reg_1004_pp0_iter4_reg <= k_mid2_reg_1004_pp0_iter3_reg;
        k_mid2_reg_1004_pp0_iter5_reg <= k_mid2_reg_1004_pp0_iter4_reg;
        k_mid2_reg_1004_pp0_iter6_reg <= k_mid2_reg_1004_pp0_iter5_reg;
        k_mid2_reg_1004_pp0_iter7_reg <= k_mid2_reg_1004_pp0_iter6_reg;
        k_mid2_reg_1004_pp0_iter8_reg <= k_mid2_reg_1004_pp0_iter7_reg;
        k_mid2_reg_1004_pp0_iter9_reg <= k_mid2_reg_1004_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_1012 <= first_iter_0_fu_494_p2;
        first_iter_0_reg_1012_pp0_iter1_reg <= first_iter_0_reg_1012;
        icmp_ln34_reg_987 <= icmp_ln34_fu_468_p2;
        icmp_ln34_reg_987_pp0_iter1_reg <= icmp_ln34_reg_987;
        icmp_ln39_3_reg_1021 <= icmp_ln39_3_fu_518_p2;
        icmp_ln39_3_reg_1021_pp0_iter1_reg <= icmp_ln39_3_reg_1021;
        icmp_ln39_reg_996 <= icmp_ln39_fu_480_p2;
        icmp_ln39_reg_996_pp0_iter1_reg <= icmp_ln39_reg_996;
        k_mid2_reg_1004 <= k_mid2_fu_486_p3;
        k_mid2_reg_1004_pp0_iter1_reg <= k_mid2_reg_1004;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln34_reg_987_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        maximum_6_fu_150 <= maximum_7_fu_867_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln34_reg_1029 <= select_ln34_fu_549_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd1))) begin
        sext_ln50_45_reg_210 <= sext_ln50_46_reg_233;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        CONV2_BIAS_ce0_local = 1'b1;
    end else begin
        CONV2_BIAS_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        CONV2_WEIGHT_ce0_local = 1'b1;
    end else begin
        CONV2_WEIGHT_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (ap_enable_reg_pp0_iter13 == 1'b0))) begin
        ap_condition_pp0_exit_iter14_state20 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter14_state20 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln34_fu_468_p2 == 1'd1))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln27_fu_368_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln34_reg_987_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_accumulator_5_phi_fu_316_p4 = grp_fu_891_p3;
    end else begin
        ap_phi_mux_accumulator_5_phi_fu_316_p4 = accumulator_5_reg_313;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln34_reg_987 == 1'd0))) begin
        ap_phi_mux_k_phi_fu_271_p4 = add_ln39_reg_1016;
    end else begin
        ap_phi_mux_k_phi_fu_271_p4 = k_reg_267;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln34_reg_987_pp0_iter10_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_phi_fu_282_p4 = select_ln34_reg_1029;
    end else begin
        ap_phi_mux_p_phi_fu_282_p4 = p_reg_278;
    end
end

always @ (*) begin
    if ((((first_iter_3_reg_948 == 1'd0) & (first_iter_1_mid2_reg_1025_pp0_iter13_reg == 1'd1) & (first_iter_0_reg_1012_pp0_iter13_reg == 1'd1) & (icmp_ln34_reg_987_pp0_iter13_reg == 1'd0) & (first_iter_2_reg_973 == 1'd1)) | ((first_iter_1_mid2_reg_1025_pp0_iter13_reg == 1'd1) & (first_iter_0_reg_1012_pp0_iter13_reg == 1'd1) & (icmp_ln34_reg_987_pp0_iter13_reg == 1'd0) & (first_iter_2_reg_973 == 1'd0)) | ((first_iter_1_mid2_reg_1025_pp0_iter13_reg == 1'd0) & (first_iter_0_reg_1012_pp0_iter13_reg == 1'd1) & (icmp_ln34_reg_987_pp0_iter13_reg == 1'd0)) | ((first_iter_0_reg_1012_pp0_iter13_reg == 1'd0) & (icmp_ln34_reg_987_pp0_iter13_reg == 1'd0)))) begin
        ap_phi_mux_sext_ln50_41_phi_fu_347_p10 = accumulator_5_mid2_fu_760_p3;
    end else begin
        ap_phi_mux_sext_ln50_41_phi_fu_347_p10 = ap_phi_reg_pp0_iter14_sext_ln50_41_reg_344;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln34_reg_987_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_sext_ln50_48_phi_fu_305_p4 = sext_ln50_49_reg_323;
    end else begin
        ap_phi_mux_sext_ln50_48_phi_fu_305_p4 = sext_ln50_48_reg_301;
    end
end

always @ (*) begin
    if (((icmp_ln27_fu_368_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stage1_ce0_local = 1'b1;
    end else begin
        stage1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stage2_ce1_local = 1'b1;
    end else begin
        stage2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln34_3_reg_1036_pp0_iter14_reg == 1'd1) & (icmp_ln39_3_reg_1021_pp0_iter14_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stage2_we1_local = 1'b1;
    end else begin
        stage2_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln27_fu_368_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln29_fu_416_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_442_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter14 == 1'b1) & (ap_enable_reg_pp0_iter13 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter14 == 1'b1) & (ap_enable_reg_pp0_iter13 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CONV2_BIAS_address0 = zext_ln27_fu_380_p1;

assign CONV2_WEIGHT_address0 = zext_ln50_2_fu_740_p1;

assign accumulator_5_mid2_fu_760_p3 = ((icmp_ln39_reg_996_pp0_iter13_reg[0:0] == 1'b1) ? ap_phi_mux_sext_ln50_48_phi_fu_305_p4 : ap_phi_mux_accumulator_5_phi_fu_316_p4);

assign add_ln1076_fu_801_p2 = (zext_ln1075_fu_797_p1 + 33'd128);

assign add_ln27_fu_374_p2 = (oc_fu_146 + 6'd1);

assign add_ln29_fu_422_p2 = (oy_reg_222 + 4'd1);

assign add_ln31_fu_448_p2 = (ox_reg_245 + 4'd1);

assign add_ln34_3_fu_524_p2 = (ap_phi_mux_p_phi_fu_282_p4 + 3'd1);

assign add_ln34_fu_474_p2 = (indvar_flatten_reg_256 + 10'd1);

assign add_ln39_fu_512_p2 = (k_mid2_fu_486_p3 + 8'd1);

assign add_ln44_fu_619_p2 = ($signed(trunc_ln42_3_fu_594_p4) + $signed(2'd3));

assign add_ln45_fu_646_p2 = ($signed(trunc_ln43_fu_604_p1) + $signed(2'd3));

assign add_ln48_3_fu_724_p2 = ($signed(shl_ln48_3_fu_716_p3) + $signed(sext_ln45_3_fu_662_p1));

assign add_ln48_fu_710_p2 = ($signed(sext_ln48_fu_706_p1) + $signed(shl_ln4_fu_698_p3));

assign add_ln50_fu_735_p2 = (zext_ln39_fu_572_p1 + add_ln57_2_reg_930);

assign add_ln57_2_fu_407_p2 = (p_shl_fu_389_p3 + zext_ln57_fu_403_p1);

assign add_ln57_fu_876_p2 = (zext_ln31_reg_977 + shl_ln_fu_781_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_445 = ((first_iter_3_reg_948 == 1'd1) & (first_iter_1_mid2_fu_542_p3 == 1'd1) & (first_iter_0_reg_1012_pp0_iter9_reg == 1'd1) & (icmp_ln34_reg_987_pp0_iter9_reg == 1'd0) & (first_iter_2_reg_973 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_sext_ln50_41_reg_344 = 'bx;

assign ap_phi_reg_pp0_iter0_sext_ln50_49_reg_323 = 'bx;

assign empty_fu_847_p2 = (icmp_ln1078_fu_817_p2 | icmp_ln1074_fu_789_p2);

assign first_iter_0_fu_494_p2 = ((k_mid2_fu_486_p3 == 8'd0) ? 1'b1 : 1'b0);

assign first_iter_120_fu_536_p2 = ((ap_phi_mux_p_phi_fu_282_p4 == 3'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid1_fu_530_p2 = ((add_ln34_3_fu_524_p2 == 3'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid2_fu_542_p3 = ((icmp_ln39_reg_996_pp0_iter9_reg[0:0] == 1'b1) ? first_iter_1_mid1_fu_530_p2 : first_iter_120_fu_536_p2);

assign first_iter_2_fu_454_p2 = ((ox_reg_245 == 4'd0) ? 1'b1 : 1'b0);

assign first_iter_3_fu_428_p2 = ((oy_reg_222 == 4'd0) ? 1'b1 : 1'b0);

assign grp_fu_500_p1 = 8'd9;

assign grp_fu_506_p1 = 8'd3;

assign grp_fu_891_p1 = grp_fu_891_p10;

assign grp_fu_891_p10 = pixel_3_fu_745_p3;

assign icmp_ln1074_fu_789_p2 = (($signed(grp_fu_891_p3) < $signed(23'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1078_fu_817_p2 = ((tmp_8_fu_807_p4 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_368_p2 = ((oc_fu_146 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_416_p2 = ((oy_reg_222 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_442_p2 = ((ox_reg_245 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln34_3_fu_556_p2 = ((select_ln34_fu_549_p3 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_468_p2 = ((indvar_flatten_reg_256 == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln39_3_fu_518_p2 = ((add_ln39_fu_512_p2 == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_480_p2 = ((ap_phi_mux_k_phi_fu_271_p4 == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_682_p2 = ((tmp_7_fu_672_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_861_p2 = ((value_fu_853_p3 > select_ln34_3_fu_774_p3) ? 1'b1 : 1'b0);

assign ix_fu_656_p2 = ($signed(sext_ln45_fu_652_p1) + $signed(zext_ln45_fu_642_p1));

assign iy_fu_629_p2 = ($signed(sext_ln44_fu_625_p1) + $signed(zext_ln44_fu_615_p1));

assign k_mid2_fu_486_p3 = ((icmp_ln39_fu_480_p2[0:0] == 1'b1) ? 8'd0 : ap_phi_mux_k_phi_fu_271_p4);

assign maximum_7_fu_867_p3 = ((icmp_ln55_fu_861_p2[0:0] == 1'b1) ? value_fu_853_p3 : select_ln34_3_fu_774_p3);

assign mul_ln41_fu_578_p0 = mul_ln41_fu_578_p00;

assign mul_ln41_fu_578_p00 = k_mid2_reg_1004_pp0_iter10_reg;

assign mul_ln41_fu_578_p1 = 17'd456;

assign mul_ln42_fu_588_p0 = mul_ln42_fu_588_p00;

assign mul_ln42_fu_588_p00 = grp_fu_500_p2;

assign mul_ln42_fu_588_p1 = 9'd22;

assign not_icmp_ln1074_fu_833_p2 = (icmp_ln1074_fu_789_p2 ^ 1'd1);

assign or_ln47_fu_666_p2 = (iy_fu_629_p2 | ix_fu_656_p2);

assign p_shl_fu_389_p3 = {{oc_fu_146}, {7'd0}};

assign pixel_3_fu_745_p3 = ((icmp_ln47_reg_1040[0:0] == 1'b1) ? stage1_q0 : 7'd0);

assign select_ln1078_cast_fu_839_p3 = ((not_icmp_ln1074_fu_833_p2[0:0] == 1'b1) ? 7'd127 : 7'd0);

assign select_ln34_3_fu_774_p3 = ((icmp_ln39_reg_996_pp0_iter14_reg[0:0] == 1'b1) ? maximum_6_fu_150 : maximum_reg_289);

assign select_ln34_fu_549_p3 = ((icmp_ln39_reg_996_pp0_iter9_reg[0:0] == 1'b1) ? add_ln34_3_fu_524_p2 : ap_phi_mux_p_phi_fu_282_p4);

assign sext_ln1075_fu_794_p1 = grp_fu_891_p3;

assign sext_ln44_fu_625_p1 = $signed(add_ln44_fu_619_p2);

assign sext_ln45_3_fu_662_p1 = ix_fu_656_p2;

assign sext_ln45_fu_652_p1 = $signed(add_ln45_fu_646_p2);

assign sext_ln48_fu_706_p1 = iy_fu_629_p2;

assign sext_ln50_4_fu_385_p1 = $signed(CONV2_BIAS_q0);

assign shl_ln48_3_fu_716_p3 = {{add_ln48_fu_710_p2}, {4'd0}};

assign shl_ln4_fu_698_p3 = {{tmp_3_fu_688_p4}, {4'd0}};

assign shl_ln_fu_781_p4 = {{{trunc_ln57_reg_935}, {trunc_ln57_3_reg_952}}, {3'd0}};

assign stage1_address0 = zext_ln48_fu_730_p1;

assign stage1_ce0 = stage1_ce0_local;

assign stage2_address1 = zext_ln57_2_fu_881_p1;

assign stage2_ce1 = stage2_ce1_local;

assign stage2_d1 = maximum_7_fu_867_p3;

assign stage2_we1 = stage2_we1_local;

assign tmp1_fu_608_p3 = {{trunc_ln57_3_reg_952}, {tmp_6_fu_565_p3}};

assign tmp4_fu_635_p3 = {{trunc_ln37_reg_982}, {trunc_ln34_fu_562_p1}};

assign tmp_3_fu_688_p4 = {{mul_ln41_fu_578_p2[15:12]}};

assign tmp_6_fu_565_p3 = select_ln34_reg_1029[32'd1];

assign tmp_7_fu_672_p4 = {{or_ln47_fu_666_p2[5:4]}};

assign tmp_8_fu_807_p4 = {{add_ln1076_fu_801_p2[32:15]}};

assign tmp_fu_396_p3 = {{oc_fu_146}, {4'd0}};

assign trunc_ln34_fu_562_p1 = select_ln34_reg_1029[0:0];

assign trunc_ln37_fu_464_p1 = ox_reg_245[2:0];

assign trunc_ln42_3_fu_594_p4 = {{mul_ln42_fu_588_p2[7:6]}};

assign trunc_ln43_fu_604_p1 = grp_fu_506_p2[1:0];

assign trunc_ln57_3_fu_434_p1 = oy_reg_222[2:0];

assign trunc_ln57_fu_413_p1 = oc_fu_146[4:0];

assign trunc_ln_fu_823_p4 = {{add_ln1076_fu_801_p2[14:8]}};

assign value_fu_853_p3 = ((empty_fu_847_p2[0:0] == 1'b1) ? select_ln1078_cast_fu_839_p3 : trunc_ln_fu_823_p4);

assign zext_ln1075_fu_797_p1 = $unsigned(sext_ln1075_fu_794_p1);

assign zext_ln27_fu_380_p1 = oc_fu_146;

assign zext_ln31_fu_460_p1 = ox_reg_245;

assign zext_ln39_fu_572_p1 = k_mid2_reg_1004_pp0_iter10_reg;

assign zext_ln44_fu_615_p1 = tmp1_fu_608_p3;

assign zext_ln45_fu_642_p1 = tmp4_fu_635_p3;

assign zext_ln48_fu_730_p1 = add_ln48_3_fu_724_p2;

assign zext_ln50_2_fu_740_p1 = add_ln50_fu_735_p2;

assign zext_ln57_2_fu_881_p1 = add_ln57_fu_876_p2;

assign zext_ln57_fu_403_p1 = tmp_fu_396_p3;

always @ (posedge ap_clk) begin
    add_ln57_2_reg_930[3:0] <= 4'b0000;
    zext_ln31_reg_977[10:4] <= 7'b0000000;
end

endmodule //cifar10_cnn_conv_relu_pool_16_32_16_8_s
