// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cifar10_cnn_conv_relu_pool_32_64_8_7_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stage2_address0,
        stage2_ce0,
        stage2_q0,
        stage3_address1,
        stage3_ce1,
        stage3_we1,
        stage3_d1
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_pp0_stage0 = 7'd32;
parameter    ap_ST_fsm_state23 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] stage2_address0;
output   stage2_ce0;
input  [6:0] stage2_q0;
output  [9:0] stage3_address1;
output   stage3_ce1;
output   stage3_we1;
output  [6:0] stage3_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] CONV3_BIAS_address0;
wire   [8:0] CONV3_BIAS_q0;
wire   [14:0] CONV3_WEIGHT_address0;
wire  signed [7:0] CONV3_WEIGHT_q0;
reg   [10:0] indvar_flatten_reg_254;
reg   [8:0] k_reg_265;
reg   [2:0] p_reg_276;
reg   [6:0] maximum_reg_287;
reg   [22:0] sext_ln50_18_reg_299;
reg   [22:0] accumulator_1_reg_311;
reg   [22:0] sext_ln50_19_reg_321;
wire   [6:0] add_ln27_fu_372_p2;
reg   [6:0] add_ln27_reg_918;
wire    ap_CS_fsm_state2;
wire  signed [22:0] sext_ln50_1_fu_383_p1;
reg  signed [22:0] sext_ln50_1_reg_928;
wire    ap_CS_fsm_state3;
wire   [14:0] add_ln57_1_fu_405_p2;
reg   [14:0] add_ln57_1_reg_934;
wire   [5:0] trunc_ln57_fu_411_p1;
reg   [5:0] trunc_ln57_reg_939;
wire   [2:0] add_ln29_fu_420_p2;
reg   [2:0] add_ln29_reg_947;
wire    ap_CS_fsm_state4;
wire   [0:0] first_iter_3_fu_426_p2;
reg   [0:0] first_iter_3_reg_952;
wire   [1:0] trunc_ln57_1_fu_432_p1;
reg   [1:0] trunc_ln57_1_reg_956;
wire   [2:0] shl_ln36_fu_436_p2;
reg   [2:0] shl_ln36_reg_961;
wire   [0:0] icmp_ln31_fu_446_p2;
wire    ap_CS_fsm_state5;
wire   [2:0] add_ln31_fu_452_p2;
reg   [2:0] add_ln31_reg_970;
wire   [0:0] first_iter_2_fu_458_p2;
reg   [0:0] first_iter_2_reg_981;
wire   [9:0] zext_ln31_fu_464_p1;
reg   [9:0] zext_ln31_reg_985;
wire   [1:0] trunc_ln37_fu_468_p1;
reg   [1:0] trunc_ln37_reg_990;
wire   [0:0] icmp_ln34_fu_472_p2;
reg   [0:0] icmp_ln34_reg_995;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln34_reg_995_pp0_iter1_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter2_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter3_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter4_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter5_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter6_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter7_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter8_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter9_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter10_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter11_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter12_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter13_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter14_reg;
reg   [0:0] icmp_ln34_reg_995_pp0_iter15_reg;
wire   [10:0] add_ln34_fu_478_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln39_fu_484_p2;
reg   [0:0] icmp_ln39_reg_1004;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter1_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter2_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter3_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter4_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter5_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter6_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter7_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter8_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter9_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter10_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter11_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter12_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter13_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter14_reg;
reg   [0:0] icmp_ln39_reg_1004_pp0_iter15_reg;
wire   [8:0] k_mid2_fu_490_p3;
reg   [8:0] k_mid2_reg_1012;
reg   [8:0] k_mid2_reg_1012_pp0_iter1_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter2_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter3_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter4_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter5_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter6_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter7_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter8_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter9_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter10_reg;
reg   [8:0] k_mid2_reg_1012_pp0_iter11_reg;
wire   [0:0] first_iter_0_fu_498_p2;
reg   [0:0] first_iter_0_reg_1020;
reg   [0:0] first_iter_0_reg_1020_pp0_iter1_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter2_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter3_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter4_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter5_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter6_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter7_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter8_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter9_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter10_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter11_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter12_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter13_reg;
reg   [0:0] first_iter_0_reg_1020_pp0_iter14_reg;
wire   [8:0] add_ln39_fu_516_p2;
reg   [8:0] add_ln39_reg_1024;
wire   [0:0] icmp_ln39_1_fu_522_p2;
reg   [0:0] icmp_ln39_1_reg_1029;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter1_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter2_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter3_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter4_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter5_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter6_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter7_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter8_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter9_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter10_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter11_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter12_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter13_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter14_reg;
reg   [0:0] icmp_ln39_1_reg_1029_pp0_iter15_reg;
wire   [0:0] first_iter_1_mid2_fu_546_p3;
reg   [0:0] first_iter_1_mid2_reg_1033;
reg   [0:0] first_iter_1_mid2_reg_1033_pp0_iter12_reg;
reg   [0:0] first_iter_1_mid2_reg_1033_pp0_iter13_reg;
reg   [0:0] first_iter_1_mid2_reg_1033_pp0_iter14_reg;
wire   [2:0] select_ln34_fu_553_p3;
reg   [2:0] select_ln34_reg_1037;
reg    ap_enable_reg_pp0_iter11;
wire   [0:0] icmp_ln34_1_fu_560_p2;
reg   [0:0] icmp_ln34_1_reg_1044;
reg   [0:0] icmp_ln34_1_reg_1044_pp0_iter12_reg;
reg   [0:0] icmp_ln34_1_reg_1044_pp0_iter13_reg;
reg   [0:0] icmp_ln34_1_reg_1044_pp0_iter14_reg;
reg   [0:0] icmp_ln34_1_reg_1044_pp0_iter15_reg;
wire   [0:0] icmp_ln47_fu_686_p2;
reg   [0:0] icmp_ln47_reg_1048;
wire   [6:0] select_ln34_1_fu_778_p3;
reg    ap_enable_reg_pp0_iter16;
wire  signed [22:0] grp_fu_895_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_condition_pp0_exit_iter15_state21;
reg   [22:0] sext_ln50_15_reg_208;
reg   [2:0] oy_reg_220;
reg   [22:0] sext_ln50_16_reg_231;
wire   [0:0] icmp_ln29_fu_414_p2;
wire    ap_CS_fsm_state23;
reg   [2:0] ox_reg_243;
reg   [8:0] ap_phi_mux_k_phi_fu_269_p4;
wire    ap_block_pp0_stage0;
reg   [2:0] ap_phi_mux_p_phi_fu_280_p4;
reg   [22:0] ap_phi_mux_sext_ln50_18_phi_fu_303_p4;
reg   [22:0] ap_phi_mux_accumulator_1_phi_fu_314_p4;
reg   [22:0] ap_phi_reg_pp0_iter15_sext_ln50_19_reg_321;
reg    ap_predicate_pred402_state21;
wire   [22:0] ap_phi_reg_pp0_iter0_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter1_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter2_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter3_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter4_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter5_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter6_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter7_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter8_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter9_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter10_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter11_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter13_sext_ln50_19_reg_321;
reg   [22:0] ap_phi_reg_pp0_iter14_sext_ln50_19_reg_321;
reg  signed [22:0] ap_phi_mux_sext_ln50_11_phi_fu_345_p10;
wire   [22:0] accumulator_1_mid2_fu_764_p3;
reg   [22:0] ap_phi_reg_pp0_iter15_sext_ln50_11_reg_342;
wire   [22:0] ap_phi_reg_pp0_iter0_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter1_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter2_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter3_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter4_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter5_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter6_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter7_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter8_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter9_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter10_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter11_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter13_sext_ln50_11_reg_342;
reg   [22:0] ap_phi_reg_pp0_iter14_sext_ln50_11_reg_342;
wire   [63:0] zext_ln27_fu_378_p1;
wire   [0:0] icmp_ln27_fu_366_p2;
wire   [63:0] zext_ln48_fu_734_p1;
wire   [63:0] zext_ln50_1_fu_744_p1;
wire   [63:0] zext_ln57_1_fu_885_p1;
reg   [6:0] oc_fu_144;
reg   [6:0] maximum_2_fu_148;
wire   [6:0] maximum_3_fu_871_p3;
reg    CONV3_BIAS_ce0_local;
reg    stage2_ce0_local;
reg    CONV3_WEIGHT_ce0_local;
reg    stage3_we1_local;
reg    stage3_ce1_local;
wire   [11:0] tmp_fu_394_p3;
wire   [14:0] p_shl_fu_387_p3;
wire   [14:0] zext_ln57_fu_401_p1;
wire   [4:0] grp_fu_504_p1;
wire   [2:0] grp_fu_510_p1;
wire   [2:0] add_ln34_1_fu_528_p2;
wire   [0:0] first_iter_1_mid1_fu_534_p2;
wire   [0:0] first_iter_120_fu_540_p2;
wire   [1:0] lshr_ln_fu_569_p4;
wire   [8:0] mul_ln41_fu_588_p0;
wire   [10:0] mul_ln41_fu_588_p1;
wire  signed [4:0] mul_ln42_fu_594_p0;
wire  signed [8:0] grp_fu_504_p2;
wire   [5:0] mul_ln42_fu_594_p1;
wire   [8:0] mul_ln42_fu_594_p2;
wire   [1:0] grp_fu_510_p2;
wire   [2:0] zext_ln36_fu_578_p1;
wire   [2:0] add_ln44_fu_614_p2;
wire   [1:0] trunc_ln42_1_fu_600_p4;
wire   [1:0] add_ln44_1_fu_623_p2;
wire  signed [4:0] sext_ln44_fu_629_p1;
wire   [4:0] zext_ln44_fu_619_p1;
wire   [0:0] trunc_ln34_fu_566_p1;
wire   [2:0] tmp4_fu_639_p3;
wire   [1:0] trunc_ln43_fu_610_p1;
wire   [1:0] add_ln45_fu_650_p2;
wire  signed [4:0] sext_ln45_fu_656_p1;
wire   [4:0] zext_ln45_fu_646_p1;
wire  signed [4:0] ix_fu_660_p2;
wire  signed [4:0] iy_fu_633_p2;
wire   [4:0] or_ln47_fu_670_p2;
wire   [1:0] tmp_2_fu_676_p4;
wire   [18:0] mul_ln41_fu_588_p2;
wire   [4:0] tmp_1_fu_692_p4;
wire  signed [7:0] sext_ln48_fu_710_p1;
wire   [7:0] shl_ln2_fu_702_p3;
wire   [7:0] add_ln48_fu_714_p2;
wire   [10:0] shl_ln48_1_fu_720_p3;
wire  signed [10:0] sext_ln45_1_fu_666_p1;
wire   [10:0] add_ln48_1_fu_728_p2;
wire   [14:0] zext_ln39_fu_582_p1;
wire   [14:0] add_ln50_fu_739_p2;
wire   [6:0] pixel_1_fu_749_p3;
wire  signed [31:0] sext_ln1075_fu_798_p1;
wire   [32:0] zext_ln1075_fu_801_p1;
wire   [32:0] add_ln1076_fu_805_p2;
wire   [18:0] tmp_3_fu_811_p4;
wire   [0:0] icmp_ln1074_fu_793_p2;
wire   [0:0] not_icmp_ln1074_fu_837_p2;
wire   [0:0] icmp_ln1078_fu_821_p2;
wire   [0:0] empty_fu_851_p2;
wire   [6:0] select_ln1078_cast_fu_843_p3;
wire   [6:0] trunc_ln5_fu_827_p4;
wire   [6:0] value_fu_857_p3;
wire   [0:0] icmp_ln55_fu_865_p2;
wire   [9:0] shl_ln1_fu_785_p4;
wire   [9:0] add_ln57_fu_880_p2;
wire   [6:0] grp_fu_895_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [14:0] grp_fu_895_p10;
wire   [18:0] mul_ln41_fu_588_p00;
reg    ap_condition_457;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 oc_fu_144 = 7'd0;
#0 maximum_2_fu_148 = 7'd0;
end

cifar10_cnn_conv_relu_pool_32_64_8_7_s_CONV3_BIAS_ROM_AUTO_1R #(
    .DataWidth( 9 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
CONV3_BIAS_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONV3_BIAS_address0),
    .ce0(CONV3_BIAS_ce0_local),
    .q0(CONV3_BIAS_q0)
);

cifar10_cnn_conv_relu_pool_32_64_8_7_s_CONV3_WEIGHT_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 18432 ),
    .AddressWidth( 15 ))
CONV3_WEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CONV3_WEIGHT_address0),
    .ce0(CONV3_WEIGHT_ce0_local),
    .q0(CONV3_WEIGHT_q0)
);

cifar10_cnn_urem_9ns_5ns_9_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 9 ))
urem_9ns_5ns_9_13_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(k_mid2_fu_490_p3),
    .din1(grp_fu_504_p1),
    .ce(1'b1),
    .dout(grp_fu_504_p2)
);

cifar10_cnn_urem_9ns_3ns_2_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_9ns_3ns_2_13_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(k_mid2_fu_490_p3),
    .din1(grp_fu_510_p1),
    .ce(1'b1),
    .dout(grp_fu_510_p2)
);

cifar10_cnn_mul_9ns_11ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
mul_9ns_11ns_19_1_1_U34(
    .din0(mul_ln41_fu_588_p0),
    .din1(mul_ln41_fu_588_p1),
    .dout(mul_ln41_fu_588_p2)
);

cifar10_cnn_mul_5s_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_5s_6ns_9_1_1_U35(
    .din0(mul_ln42_fu_594_p0),
    .din1(mul_ln42_fu_594_p1),
    .dout(mul_ln42_fu_594_p2)
);

cifar10_cnn_mac_muladd_8s_7ns_23s_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 23 ),
    .dout_WIDTH( 23 ))
mac_muladd_8s_7ns_23s_23_4_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(CONV3_WEIGHT_q0),
    .din1(grp_fu_895_p1),
    .din2(ap_phi_mux_sext_ln50_11_phi_fu_345_p10),
    .ce(1'b1),
    .dout(grp_fu_895_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end else if ((((ap_enable_reg_pp0_iter14 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter15_state21) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0)))) begin
            ap_enable_reg_pp0_iter15 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter15_state21) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter14;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter16 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln34_reg_995_pp0_iter15_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accumulator_1_reg_311 <= grp_fu_895_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0))) begin
        accumulator_1_reg_311 <= sext_ln50_16_reg_231;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_457)) begin
            ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342 <= sext_ln50_1_reg_928;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter11_sext_ln50_11_reg_342;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_457)) begin
            ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321 <= sext_ln50_1_reg_928;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter11_sext_ln50_19_reg_321;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_fu_472_p2 == 1'd0))) begin
        indvar_flatten_reg_254 <= add_ln34_fu_478_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0))) begin
        indvar_flatten_reg_254 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln34_reg_995 == 1'd0))) begin
        k_reg_265 <= add_ln39_reg_1024;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0))) begin
        k_reg_265 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln34_reg_995_pp0_iter15_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        maximum_reg_287 <= select_ln34_1_fu_778_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0))) begin
        maximum_reg_287 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        oc_fu_144 <= 7'd0;
    end else if (((icmp_ln29_fu_414_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        oc_fu_144 <= add_ln27_reg_918;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ox_reg_243 <= add_ln31_reg_970;
    end else if (((icmp_ln29_fu_414_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ox_reg_243 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd1))) begin
        oy_reg_220 <= add_ln29_reg_947;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        oy_reg_220 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_reg_995_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_reg_276 <= select_ln34_reg_1037;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0))) begin
        p_reg_276 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        sext_ln50_16_reg_231 <= sext_ln50_18_reg_299;
    end else if (((icmp_ln29_fu_414_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sext_ln50_16_reg_231 <= sext_ln50_15_reg_208;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln34_reg_995_pp0_iter15_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sext_ln50_18_reg_299 <= sext_ln50_19_reg_321;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd0))) begin
        sext_ln50_18_reg_299 <= sext_ln50_16_reg_231;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_pred402_state21 == 1'b1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (first_iter_1_mid2_reg_1033_pp0_iter14_reg == 1'd1) & (first_iter_0_reg_1020_pp0_iter14_reg == 1'd1) & (icmp_ln34_reg_995_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_2_reg_981 == 1'd0)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (first_iter_1_mid2_reg_1033_pp0_iter14_reg == 1'd0) & (first_iter_0_reg_1020_pp0_iter14_reg == 1'd1) & (icmp_ln34_reg_995_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (first_iter_0_reg_1020_pp0_iter14_reg == 1'd0) & (icmp_ln34_reg_995_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sext_ln50_19_reg_321 <= ap_phi_mux_sext_ln50_18_phi_fu_303_p4;
    end else if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter15_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln27_reg_918 <= add_ln27_fu_372_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln29_reg_947 <= add_ln29_fu_420_p2;
        first_iter_3_reg_952 <= first_iter_3_fu_426_p2;
        shl_ln36_reg_961 <= shl_ln36_fu_436_p2;
        trunc_ln57_1_reg_956 <= trunc_ln57_1_fu_432_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln31_reg_970 <= add_ln31_fu_452_p2;
        first_iter_2_reg_981 <= first_iter_2_fu_458_p2;
        trunc_ln37_reg_990 <= trunc_ln37_fu_468_p1;
        zext_ln31_reg_985[2 : 0] <= zext_ln31_fu_464_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln39_reg_1024 <= add_ln39_fu_516_p2;
        ap_phi_reg_pp0_iter1_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter0_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter1_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter0_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln57_1_reg_934[14 : 5] <= add_ln57_1_fu_405_p2[14 : 5];
        sext_ln50_1_reg_928 <= sext_ln50_1_fu_383_p1;
        trunc_ln57_reg_939 <= trunc_ln57_fu_411_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter9_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter10_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter9_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter10_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter11_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter10_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter12_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter13_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter12_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter13_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter14_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter13_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter15_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter14_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter15_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter14_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter1_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter2_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter1_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter2_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter3_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter2_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter3_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter4_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter3_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter4_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter5_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter4_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter5_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter6_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter5_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter6_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter7_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter6_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter7_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter8_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter7_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_sext_ln50_11_reg_342 <= ap_phi_reg_pp0_iter8_sext_ln50_11_reg_342;
        ap_phi_reg_pp0_iter9_sext_ln50_19_reg_321 <= ap_phi_reg_pp0_iter8_sext_ln50_19_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_predicate_pred402_state21 <= ((first_iter_3_reg_952 == 1'd0) & (first_iter_1_mid2_reg_1033_pp0_iter13_reg == 1'd1) & (first_iter_0_reg_1020_pp0_iter13_reg == 1'd1) & (icmp_ln34_reg_995_pp0_iter13_reg == 1'd0) & (first_iter_2_reg_981 == 1'd1));
        first_iter_0_reg_1020_pp0_iter10_reg <= first_iter_0_reg_1020_pp0_iter9_reg;
        first_iter_0_reg_1020_pp0_iter11_reg <= first_iter_0_reg_1020_pp0_iter10_reg;
        first_iter_0_reg_1020_pp0_iter12_reg <= first_iter_0_reg_1020_pp0_iter11_reg;
        first_iter_0_reg_1020_pp0_iter13_reg <= first_iter_0_reg_1020_pp0_iter12_reg;
        first_iter_0_reg_1020_pp0_iter14_reg <= first_iter_0_reg_1020_pp0_iter13_reg;
        first_iter_0_reg_1020_pp0_iter2_reg <= first_iter_0_reg_1020_pp0_iter1_reg;
        first_iter_0_reg_1020_pp0_iter3_reg <= first_iter_0_reg_1020_pp0_iter2_reg;
        first_iter_0_reg_1020_pp0_iter4_reg <= first_iter_0_reg_1020_pp0_iter3_reg;
        first_iter_0_reg_1020_pp0_iter5_reg <= first_iter_0_reg_1020_pp0_iter4_reg;
        first_iter_0_reg_1020_pp0_iter6_reg <= first_iter_0_reg_1020_pp0_iter5_reg;
        first_iter_0_reg_1020_pp0_iter7_reg <= first_iter_0_reg_1020_pp0_iter6_reg;
        first_iter_0_reg_1020_pp0_iter8_reg <= first_iter_0_reg_1020_pp0_iter7_reg;
        first_iter_0_reg_1020_pp0_iter9_reg <= first_iter_0_reg_1020_pp0_iter8_reg;
        first_iter_1_mid2_reg_1033 <= first_iter_1_mid2_fu_546_p3;
        first_iter_1_mid2_reg_1033_pp0_iter12_reg <= first_iter_1_mid2_reg_1033;
        first_iter_1_mid2_reg_1033_pp0_iter13_reg <= first_iter_1_mid2_reg_1033_pp0_iter12_reg;
        first_iter_1_mid2_reg_1033_pp0_iter14_reg <= first_iter_1_mid2_reg_1033_pp0_iter13_reg;
        icmp_ln34_1_reg_1044 <= icmp_ln34_1_fu_560_p2;
        icmp_ln34_1_reg_1044_pp0_iter12_reg <= icmp_ln34_1_reg_1044;
        icmp_ln34_1_reg_1044_pp0_iter13_reg <= icmp_ln34_1_reg_1044_pp0_iter12_reg;
        icmp_ln34_1_reg_1044_pp0_iter14_reg <= icmp_ln34_1_reg_1044_pp0_iter13_reg;
        icmp_ln34_1_reg_1044_pp0_iter15_reg <= icmp_ln34_1_reg_1044_pp0_iter14_reg;
        icmp_ln34_reg_995_pp0_iter10_reg <= icmp_ln34_reg_995_pp0_iter9_reg;
        icmp_ln34_reg_995_pp0_iter11_reg <= icmp_ln34_reg_995_pp0_iter10_reg;
        icmp_ln34_reg_995_pp0_iter12_reg <= icmp_ln34_reg_995_pp0_iter11_reg;
        icmp_ln34_reg_995_pp0_iter13_reg <= icmp_ln34_reg_995_pp0_iter12_reg;
        icmp_ln34_reg_995_pp0_iter14_reg <= icmp_ln34_reg_995_pp0_iter13_reg;
        icmp_ln34_reg_995_pp0_iter15_reg <= icmp_ln34_reg_995_pp0_iter14_reg;
        icmp_ln34_reg_995_pp0_iter2_reg <= icmp_ln34_reg_995_pp0_iter1_reg;
        icmp_ln34_reg_995_pp0_iter3_reg <= icmp_ln34_reg_995_pp0_iter2_reg;
        icmp_ln34_reg_995_pp0_iter4_reg <= icmp_ln34_reg_995_pp0_iter3_reg;
        icmp_ln34_reg_995_pp0_iter5_reg <= icmp_ln34_reg_995_pp0_iter4_reg;
        icmp_ln34_reg_995_pp0_iter6_reg <= icmp_ln34_reg_995_pp0_iter5_reg;
        icmp_ln34_reg_995_pp0_iter7_reg <= icmp_ln34_reg_995_pp0_iter6_reg;
        icmp_ln34_reg_995_pp0_iter8_reg <= icmp_ln34_reg_995_pp0_iter7_reg;
        icmp_ln34_reg_995_pp0_iter9_reg <= icmp_ln34_reg_995_pp0_iter8_reg;
        icmp_ln39_1_reg_1029_pp0_iter10_reg <= icmp_ln39_1_reg_1029_pp0_iter9_reg;
        icmp_ln39_1_reg_1029_pp0_iter11_reg <= icmp_ln39_1_reg_1029_pp0_iter10_reg;
        icmp_ln39_1_reg_1029_pp0_iter12_reg <= icmp_ln39_1_reg_1029_pp0_iter11_reg;
        icmp_ln39_1_reg_1029_pp0_iter13_reg <= icmp_ln39_1_reg_1029_pp0_iter12_reg;
        icmp_ln39_1_reg_1029_pp0_iter14_reg <= icmp_ln39_1_reg_1029_pp0_iter13_reg;
        icmp_ln39_1_reg_1029_pp0_iter15_reg <= icmp_ln39_1_reg_1029_pp0_iter14_reg;
        icmp_ln39_1_reg_1029_pp0_iter2_reg <= icmp_ln39_1_reg_1029_pp0_iter1_reg;
        icmp_ln39_1_reg_1029_pp0_iter3_reg <= icmp_ln39_1_reg_1029_pp0_iter2_reg;
        icmp_ln39_1_reg_1029_pp0_iter4_reg <= icmp_ln39_1_reg_1029_pp0_iter3_reg;
        icmp_ln39_1_reg_1029_pp0_iter5_reg <= icmp_ln39_1_reg_1029_pp0_iter4_reg;
        icmp_ln39_1_reg_1029_pp0_iter6_reg <= icmp_ln39_1_reg_1029_pp0_iter5_reg;
        icmp_ln39_1_reg_1029_pp0_iter7_reg <= icmp_ln39_1_reg_1029_pp0_iter6_reg;
        icmp_ln39_1_reg_1029_pp0_iter8_reg <= icmp_ln39_1_reg_1029_pp0_iter7_reg;
        icmp_ln39_1_reg_1029_pp0_iter9_reg <= icmp_ln39_1_reg_1029_pp0_iter8_reg;
        icmp_ln39_reg_1004_pp0_iter10_reg <= icmp_ln39_reg_1004_pp0_iter9_reg;
        icmp_ln39_reg_1004_pp0_iter11_reg <= icmp_ln39_reg_1004_pp0_iter10_reg;
        icmp_ln39_reg_1004_pp0_iter12_reg <= icmp_ln39_reg_1004_pp0_iter11_reg;
        icmp_ln39_reg_1004_pp0_iter13_reg <= icmp_ln39_reg_1004_pp0_iter12_reg;
        icmp_ln39_reg_1004_pp0_iter14_reg <= icmp_ln39_reg_1004_pp0_iter13_reg;
        icmp_ln39_reg_1004_pp0_iter15_reg <= icmp_ln39_reg_1004_pp0_iter14_reg;
        icmp_ln39_reg_1004_pp0_iter2_reg <= icmp_ln39_reg_1004_pp0_iter1_reg;
        icmp_ln39_reg_1004_pp0_iter3_reg <= icmp_ln39_reg_1004_pp0_iter2_reg;
        icmp_ln39_reg_1004_pp0_iter4_reg <= icmp_ln39_reg_1004_pp0_iter3_reg;
        icmp_ln39_reg_1004_pp0_iter5_reg <= icmp_ln39_reg_1004_pp0_iter4_reg;
        icmp_ln39_reg_1004_pp0_iter6_reg <= icmp_ln39_reg_1004_pp0_iter5_reg;
        icmp_ln39_reg_1004_pp0_iter7_reg <= icmp_ln39_reg_1004_pp0_iter6_reg;
        icmp_ln39_reg_1004_pp0_iter8_reg <= icmp_ln39_reg_1004_pp0_iter7_reg;
        icmp_ln39_reg_1004_pp0_iter9_reg <= icmp_ln39_reg_1004_pp0_iter8_reg;
        icmp_ln47_reg_1048 <= icmp_ln47_fu_686_p2;
        k_mid2_reg_1012_pp0_iter10_reg <= k_mid2_reg_1012_pp0_iter9_reg;
        k_mid2_reg_1012_pp0_iter11_reg <= k_mid2_reg_1012_pp0_iter10_reg;
        k_mid2_reg_1012_pp0_iter2_reg <= k_mid2_reg_1012_pp0_iter1_reg;
        k_mid2_reg_1012_pp0_iter3_reg <= k_mid2_reg_1012_pp0_iter2_reg;
        k_mid2_reg_1012_pp0_iter4_reg <= k_mid2_reg_1012_pp0_iter3_reg;
        k_mid2_reg_1012_pp0_iter5_reg <= k_mid2_reg_1012_pp0_iter4_reg;
        k_mid2_reg_1012_pp0_iter6_reg <= k_mid2_reg_1012_pp0_iter5_reg;
        k_mid2_reg_1012_pp0_iter7_reg <= k_mid2_reg_1012_pp0_iter6_reg;
        k_mid2_reg_1012_pp0_iter8_reg <= k_mid2_reg_1012_pp0_iter7_reg;
        k_mid2_reg_1012_pp0_iter9_reg <= k_mid2_reg_1012_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_1020 <= first_iter_0_fu_498_p2;
        first_iter_0_reg_1020_pp0_iter1_reg <= first_iter_0_reg_1020;
        icmp_ln34_reg_995 <= icmp_ln34_fu_472_p2;
        icmp_ln34_reg_995_pp0_iter1_reg <= icmp_ln34_reg_995;
        icmp_ln39_1_reg_1029 <= icmp_ln39_1_fu_522_p2;
        icmp_ln39_1_reg_1029_pp0_iter1_reg <= icmp_ln39_1_reg_1029;
        icmp_ln39_reg_1004 <= icmp_ln39_fu_484_p2;
        icmp_ln39_reg_1004_pp0_iter1_reg <= icmp_ln39_reg_1004;
        k_mid2_reg_1012 <= k_mid2_fu_490_p3;
        k_mid2_reg_1012_pp0_iter1_reg <= k_mid2_reg_1012;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln34_reg_995_pp0_iter15_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        maximum_2_fu_148 <= maximum_3_fu_871_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln34_reg_1037 <= select_ln34_fu_553_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd1))) begin
        sext_ln50_15_reg_208 <= sext_ln50_16_reg_231;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        CONV3_BIAS_ce0_local = 1'b1;
    end else begin
        CONV3_BIAS_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        CONV3_WEIGHT_ce0_local = 1'b1;
    end else begin
        CONV3_WEIGHT_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b0))) begin
        ap_condition_pp0_exit_iter15_state21 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter15_state21 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln34_fu_472_p2 == 1'd1))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln27_fu_366_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln34_reg_995_pp0_iter15_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_accumulator_1_phi_fu_314_p4 = grp_fu_895_p3;
    end else begin
        ap_phi_mux_accumulator_1_phi_fu_314_p4 = accumulator_1_reg_311;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln34_reg_995 == 1'd0))) begin
        ap_phi_mux_k_phi_fu_269_p4 = add_ln39_reg_1024;
    end else begin
        ap_phi_mux_k_phi_fu_269_p4 = k_reg_265;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln34_reg_995_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_phi_fu_280_p4 = select_ln34_reg_1037;
    end else begin
        ap_phi_mux_p_phi_fu_280_p4 = p_reg_276;
    end
end

always @ (*) begin
    if ((((first_iter_3_reg_952 == 1'd0) & (first_iter_1_mid2_reg_1033_pp0_iter14_reg == 1'd1) & (first_iter_0_reg_1020_pp0_iter14_reg == 1'd1) & (icmp_ln34_reg_995_pp0_iter14_reg == 1'd0) & (first_iter_2_reg_981 == 1'd1)) | ((first_iter_1_mid2_reg_1033_pp0_iter14_reg == 1'd1) & (first_iter_0_reg_1020_pp0_iter14_reg == 1'd1) & (icmp_ln34_reg_995_pp0_iter14_reg == 1'd0) & (first_iter_2_reg_981 == 1'd0)) | ((first_iter_1_mid2_reg_1033_pp0_iter14_reg == 1'd0) & (first_iter_0_reg_1020_pp0_iter14_reg == 1'd1) & (icmp_ln34_reg_995_pp0_iter14_reg == 1'd0)) | ((first_iter_0_reg_1020_pp0_iter14_reg == 1'd0) & (icmp_ln34_reg_995_pp0_iter14_reg == 1'd0)))) begin
        ap_phi_mux_sext_ln50_11_phi_fu_345_p10 = accumulator_1_mid2_fu_764_p3;
    end else begin
        ap_phi_mux_sext_ln50_11_phi_fu_345_p10 = ap_phi_reg_pp0_iter15_sext_ln50_11_reg_342;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln34_reg_995_pp0_iter15_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_sext_ln50_18_phi_fu_303_p4 = sext_ln50_19_reg_321;
    end else begin
        ap_phi_mux_sext_ln50_18_phi_fu_303_p4 = sext_ln50_18_reg_299;
    end
end

always @ (*) begin
    if (((icmp_ln27_fu_366_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stage2_ce0_local = 1'b1;
    end else begin
        stage2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stage3_ce1_local = 1'b1;
    end else begin
        stage3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln34_1_reg_1044_pp0_iter15_reg == 1'd1) & (icmp_ln39_1_reg_1029_pp0_iter15_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stage3_we1_local = 1'b1;
    end else begin
        stage3_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln27_fu_366_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln29_fu_414_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln31_fu_446_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter15 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter15 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CONV3_BIAS_address0 = zext_ln27_fu_378_p1;

assign CONV3_WEIGHT_address0 = zext_ln50_1_fu_744_p1;

assign accumulator_1_mid2_fu_764_p3 = ((icmp_ln39_reg_1004_pp0_iter14_reg[0:0] == 1'b1) ? ap_phi_mux_sext_ln50_18_phi_fu_303_p4 : ap_phi_mux_accumulator_1_phi_fu_314_p4);

assign add_ln1076_fu_805_p2 = (zext_ln1075_fu_801_p1 + 33'd64);

assign add_ln27_fu_372_p2 = (oc_fu_144 + 7'd1);

assign add_ln29_fu_420_p2 = (oy_reg_220 + 3'd1);

assign add_ln31_fu_452_p2 = (ox_reg_243 + 3'd1);

assign add_ln34_1_fu_528_p2 = (ap_phi_mux_p_phi_fu_280_p4 + 3'd1);

assign add_ln34_fu_478_p2 = (indvar_flatten_reg_254 + 11'd1);

assign add_ln39_fu_516_p2 = (k_mid2_fu_490_p3 + 9'd1);

assign add_ln44_1_fu_623_p2 = ($signed(trunc_ln42_1_fu_600_p4) + $signed(2'd3));

assign add_ln44_fu_614_p2 = (zext_ln36_fu_578_p1 + shl_ln36_reg_961);

assign add_ln45_fu_650_p2 = ($signed(trunc_ln43_fu_610_p1) + $signed(2'd3));

assign add_ln48_1_fu_728_p2 = ($signed(shl_ln48_1_fu_720_p3) + $signed(sext_ln45_1_fu_666_p1));

assign add_ln48_fu_714_p2 = ($signed(sext_ln48_fu_710_p1) + $signed(shl_ln2_fu_702_p3));

assign add_ln50_fu_739_p2 = (zext_ln39_fu_582_p1 + add_ln57_1_reg_934);

assign add_ln57_1_fu_405_p2 = (p_shl_fu_387_p3 + zext_ln57_fu_401_p1);

assign add_ln57_fu_880_p2 = (zext_ln31_reg_985 + shl_ln1_fu_785_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_457 = ((first_iter_3_reg_952 == 1'd1) & (first_iter_1_mid2_fu_546_p3 == 1'd1) & (first_iter_0_reg_1020_pp0_iter10_reg == 1'd1) & (icmp_ln34_reg_995_pp0_iter10_reg == 1'd0) & (first_iter_2_reg_981 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_sext_ln50_11_reg_342 = 'bx;

assign ap_phi_reg_pp0_iter0_sext_ln50_19_reg_321 = 'bx;

assign empty_fu_851_p2 = (icmp_ln1078_fu_821_p2 | icmp_ln1074_fu_793_p2);

assign first_iter_0_fu_498_p2 = ((k_mid2_fu_490_p3 == 9'd0) ? 1'b1 : 1'b0);

assign first_iter_120_fu_540_p2 = ((ap_phi_mux_p_phi_fu_280_p4 == 3'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid1_fu_534_p2 = ((add_ln34_1_fu_528_p2 == 3'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid2_fu_546_p3 = ((icmp_ln39_reg_1004_pp0_iter10_reg[0:0] == 1'b1) ? first_iter_1_mid1_fu_534_p2 : first_iter_120_fu_540_p2);

assign first_iter_2_fu_458_p2 = ((ox_reg_243 == 3'd0) ? 1'b1 : 1'b0);

assign first_iter_3_fu_426_p2 = ((oy_reg_220 == 3'd0) ? 1'b1 : 1'b0);

assign grp_fu_504_p1 = 9'd9;

assign grp_fu_510_p1 = 9'd3;

assign grp_fu_895_p1 = grp_fu_895_p10;

assign grp_fu_895_p10 = pixel_1_fu_749_p3;

assign icmp_ln1074_fu_793_p2 = (($signed(grp_fu_895_p3) < $signed(23'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1078_fu_821_p2 = ((tmp_3_fu_811_p4 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_366_p2 = ((oc_fu_144 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_414_p2 = ((oy_reg_220 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_446_p2 = ((ox_reg_243 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln34_1_fu_560_p2 = ((select_ln34_fu_553_p3 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_472_p2 = ((indvar_flatten_reg_254 == 11'd1152) ? 1'b1 : 1'b0);

assign icmp_ln39_1_fu_522_p2 = ((add_ln39_fu_516_p2 == 9'd288) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_484_p2 = ((ap_phi_mux_k_phi_fu_269_p4 == 9'd288) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_686_p2 = ((tmp_2_fu_676_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_865_p2 = ((value_fu_857_p3 > select_ln34_1_fu_778_p3) ? 1'b1 : 1'b0);

assign ix_fu_660_p2 = ($signed(sext_ln45_fu_656_p1) + $signed(zext_ln45_fu_646_p1));

assign iy_fu_633_p2 = ($signed(sext_ln44_fu_629_p1) + $signed(zext_ln44_fu_619_p1));

assign k_mid2_fu_490_p3 = ((icmp_ln39_fu_484_p2[0:0] == 1'b1) ? 9'd0 : ap_phi_mux_k_phi_fu_269_p4);

assign lshr_ln_fu_569_p4 = {{select_ln34_reg_1037[2:1]}};

assign maximum_3_fu_871_p3 = ((icmp_ln55_fu_865_p2[0:0] == 1'b1) ? value_fu_857_p3 : select_ln34_1_fu_778_p3);

assign mul_ln41_fu_588_p0 = mul_ln41_fu_588_p00;

assign mul_ln41_fu_588_p00 = k_mid2_reg_1012_pp0_iter11_reg;

assign mul_ln41_fu_588_p1 = 19'd911;

assign mul_ln42_fu_594_p0 = grp_fu_504_p2;

assign mul_ln42_fu_594_p1 = 9'd22;

assign not_icmp_ln1074_fu_837_p2 = (icmp_ln1074_fu_793_p2 ^ 1'd1);

assign or_ln47_fu_670_p2 = (iy_fu_633_p2 | ix_fu_660_p2);

assign p_shl_fu_387_p3 = {{oc_fu_144}, {8'd0}};

assign pixel_1_fu_749_p3 = ((icmp_ln47_reg_1048[0:0] == 1'b1) ? stage2_q0 : 7'd0);

assign select_ln1078_cast_fu_843_p3 = ((not_icmp_ln1074_fu_837_p2[0:0] == 1'b1) ? 7'd127 : 7'd0);

assign select_ln34_1_fu_778_p3 = ((icmp_ln39_reg_1004_pp0_iter15_reg[0:0] == 1'b1) ? maximum_2_fu_148 : maximum_reg_287);

assign select_ln34_fu_553_p3 = ((icmp_ln39_reg_1004_pp0_iter10_reg[0:0] == 1'b1) ? add_ln34_1_fu_528_p2 : ap_phi_mux_p_phi_fu_280_p4);

assign sext_ln1075_fu_798_p1 = grp_fu_895_p3;

assign sext_ln44_fu_629_p1 = $signed(add_ln44_1_fu_623_p2);

assign sext_ln45_1_fu_666_p1 = ix_fu_660_p2;

assign sext_ln45_fu_656_p1 = $signed(add_ln45_fu_650_p2);

assign sext_ln48_fu_710_p1 = iy_fu_633_p2;

assign sext_ln50_1_fu_383_p1 = $signed(CONV3_BIAS_q0);

assign shl_ln1_fu_785_p4 = {{{trunc_ln57_reg_939}, {trunc_ln57_1_reg_956}}, {2'd0}};

assign shl_ln2_fu_702_p3 = {{tmp_1_fu_692_p4}, {3'd0}};

assign shl_ln36_fu_436_p2 = oy_reg_220 << 3'd1;

assign shl_ln48_1_fu_720_p3 = {{add_ln48_fu_714_p2}, {3'd0}};

assign stage2_address0 = zext_ln48_fu_734_p1;

assign stage2_ce0 = stage2_ce0_local;

assign stage3_address1 = zext_ln57_1_fu_885_p1;

assign stage3_ce1 = stage3_ce1_local;

assign stage3_d1 = maximum_3_fu_871_p3;

assign stage3_we1 = stage3_we1_local;

assign tmp4_fu_639_p3 = {{trunc_ln37_reg_990}, {trunc_ln34_fu_566_p1}};

assign tmp_1_fu_692_p4 = {{mul_ln41_fu_588_p2[17:13]}};

assign tmp_2_fu_676_p4 = {{or_ln47_fu_670_p2[4:3]}};

assign tmp_3_fu_811_p4 = {{add_ln1076_fu_805_p2[32:14]}};

assign tmp_fu_394_p3 = {{oc_fu_144}, {5'd0}};

assign trunc_ln34_fu_566_p1 = select_ln34_reg_1037[0:0];

assign trunc_ln37_fu_468_p1 = ox_reg_243[1:0];

assign trunc_ln42_1_fu_600_p4 = {{mul_ln42_fu_594_p2[7:6]}};

assign trunc_ln43_fu_610_p1 = grp_fu_510_p2[1:0];

assign trunc_ln57_1_fu_432_p1 = oy_reg_220[1:0];

assign trunc_ln57_fu_411_p1 = oc_fu_144[5:0];

assign trunc_ln5_fu_827_p4 = {{add_ln1076_fu_805_p2[13:7]}};

assign value_fu_857_p3 = ((empty_fu_851_p2[0:0] == 1'b1) ? select_ln1078_cast_fu_843_p3 : trunc_ln5_fu_827_p4);

assign zext_ln1075_fu_801_p1 = $unsigned(sext_ln1075_fu_798_p1);

assign zext_ln27_fu_378_p1 = oc_fu_144;

assign zext_ln31_fu_464_p1 = ox_reg_243;

assign zext_ln36_fu_578_p1 = lshr_ln_fu_569_p4;

assign zext_ln39_fu_582_p1 = k_mid2_reg_1012_pp0_iter11_reg;

assign zext_ln44_fu_619_p1 = add_ln44_fu_614_p2;

assign zext_ln45_fu_646_p1 = tmp4_fu_639_p3;

assign zext_ln48_fu_734_p1 = add_ln48_1_fu_728_p2;

assign zext_ln50_1_fu_744_p1 = add_ln50_fu_739_p2;

assign zext_ln57_1_fu_885_p1 = add_ln57_fu_880_p2;

assign zext_ln57_fu_401_p1 = tmp_fu_394_p3;

always @ (posedge ap_clk) begin
    add_ln57_1_reg_934[4:0] <= 5'b00000;
    zext_ln31_reg_985[9:3] <= 7'b0000000;
end

endmodule //cifar10_cnn_conv_relu_pool_32_64_8_7_s
